using System;
using System.Collections.Generic;

using Kingmaker.Visual.LightSelector;
using Kingmaker.Visual.HitSystem;
using Kingmaker.Tutorial.Triggers;
using Kingmaker.Tutorial.Solvers;
using Kingmaker.QA.Arbiter;
using Kingmaker.Globalmap.Blueprints;
using Kingmaker.Dungeon.Blueprints.Boons;
using Kingmaker.DialogSystem;
using Kingmaker.Crusade.GlobalMagic;
using Kingmaker.Corruption;
using Kingmaker.Blueprints;
using Kingmaker.Blueprints.TurnBasedModifiers;
using Kingmaker.Blueprints.Quests.Logic;
using Kingmaker.Blueprints.Quests.Logic.CrusadeQuests;
using Kingmaker.Blueprints.Items.Ecnchantments;
using Kingmaker.Blueprints.Items.Components;
using Kingmaker.Blueprints.Classes;
using Kingmaker.Blueprints.Classes.Prerequisites;
using Kingmaker.Blueprints.Area;
using Kingmaker.UnitLogic.Interaction;
using Kingmaker.UnitLogic.FactLogic;
using Kingmaker.UnitLogic.Class.Kineticist.Properties;
using Kingmaker.UnitLogic.Buffs;
using Kingmaker.UnitLogic.Buffs.Components;
using Kingmaker.UnitLogic.ActivatableAbilities;
using Kingmaker.UnitLogic.ActivatableAbilities.Restrictions;
using Kingmaker.UnitLogic.Mechanics.Properties;
using Kingmaker.UnitLogic.Mechanics.Components;
using Kingmaker.UnitLogic.Abilities.Components;
using Kingmaker.UnitLogic.Abilities.Components.TargetCheckers;
using Kingmaker.Kingdom.Settlements.BuildingComponents;
using Kingmaker.Kingdom.Buffs;
using Kingmaker.Kingdom.Blueprints;
using Kingmaker.Armies.TacticalCombat.LeaderSkills.UnitBuffComponents;
using Kingmaker.Armies.TacticalCombat.Components;
using Kingmaker.Armies.Components;
using Kingmaker.Assets.UnitLogic.Mechanics.Properties;
using Kingmaker.Designers.Quests.Common;
using Kingmaker.Designers.Mechanics.EquipmentEnchants;
using Kingmaker.Designers.Mechanics.Facts;
using Kingmaker.Designers.Mechanics.Buffs;
using Kingmaker.Designers.EventConditionActionSystem.Actions;
using Kingmaker.Designers.EventConditionActionSystem.Events;
using Kingmaker.AreaLogic.Etudes;
using Kingmaker.AreaLogic.Cutscenes.Components;

namespace BlueprintCoreGen.CodeGen.Overrides.Ignored
{
  // Examples generated by TypeUsageAnalyzer
  internal static class IgnoredBlueprintComponents
  {
    public static readonly List<Type> Types =
      new()
      {
        typeof(EventDynamicCostFeast),
        typeof(TimeOfDaySettingsOverride),
        typeof(SplitDismemberComponent),
        typeof(TutorialTriggerEnemyHasVulnerability),
        typeof(TutorialTriggerLowGroupHealth),
        typeof(TutorialSolverAllFromTrigger),
        typeof(TutorialSolverItemFromTrigger),
        typeof(ArbiterWeaponTest),
        typeof(LocationRevealedTrigger),
        typeof(BoonLogicExperience),
        typeof(BoonLogicExperienceRate),
        typeof(BoonLogicGold),
        typeof(BoonLogicItem),
        typeof(BoonLogicPartyBuff),
        typeof(ActingCompanion),
        typeof(ChangeGlobalMagicPower),
        typeof(EtudeDisableCooking),
        typeof(EtudeOverrideCorruptionGrowth),
        typeof(DualCompanionComponent),
        typeof(LockedCompanionComponent),
        typeof(UnlockableFlagComponent),
        typeof(AbilityActivateWithUnitCommandInTurnBased),
        typeof(QuestComponentDelegate<>),
        typeof(QuestComponentDelegate),
        typeof(QuestObjectiveCallback),
        typeof(QuestRelatesToCompanionStory),
        typeof(TimedObjectiveTrigger),
        typeof(CrusadeMissionComponent),
        typeof(NobilityArmyRequestComponent),
        typeof(NobilityBuildingsRequestComponent),
        typeof(NobilityIncomeRequestComponent),
        typeof(NobilitySettlementsRequestComponent),
        typeof(RoyalCourtLeaderRequestComponent),
        typeof(RoyalCourtMissionsRequestComponent),
        typeof(RoyalCourtRanksRequestComponent),
        typeof(RoyalCourtVictoryRequestComponent),
        typeof(ItemEnchantmentEnableWhileEtudePlaying),
        typeof(WeaponDamageReroll),
        typeof(EquipmentRestrictionSpecialUnit),
        typeof(IdentifySkillReplacement),
        typeof(AddClassLevelsToPets),
        typeof(LevelUpRecommendation),
        typeof(PrerequisiteLoreMaster),
        typeof(AreaSettlementLink),
        typeof(BarkOnClick),
        typeof(AddGoldenDragonSkillBonus),
        typeof(AddIncomingDamageMaximum),
        typeof(AddOppositionDescriptor),
        typeof(AddParametrizedClassSkill),
        typeof(AddParametrizedStatBonus),
        typeof(AddPostLoadActions),
        typeof(AddSpellLevelLimit),
        typeof(AlchemistInfusionFeat),
        typeof(AreaEffectSpawnLogic),
        typeof(BookOfDreamsSummonUnitsCountLogic),
        typeof(ConfusionRollTrigger),
        typeof(DisableAttackType),
        typeof(DisableDeathFXs),
        typeof(ForbidSpellbook),
        typeof(LimbsApartDismembermentRestricted),
        typeof(OverrideUnitHP),
        typeof(ReplaceDamageDice),
        typeof(SpellLinkEvocation),
        typeof(LevelBasedPropertyWithFeatureList),
        typeof(RemoveBuffOnLoad),
        typeof(AddBuffActions),
        typeof(AddEffectProtectionFromElement),
        typeof(AddSpellSchool),
        typeof(SetBuffOnsetDelay),
        typeof(AddActivatableAbilityComponent),
        typeof(RestrictionHasPet),
        typeof(CustomPropertyGetter),
        typeof(UnitWeaponEnhancementGetter),
        typeof(UnitPropertyComponent),
        typeof(InitiatorRuleDealDamageTrigger),
        typeof(NonHumanoidCompanion),
        typeof(AbilityOnInBattleUnits),
        typeof(AbilityCustomAttack),
        typeof(AbilityCustomMove),
        typeof(AbilityDemonCharge),
        typeof(AbilityEffectRunActionOnClickedPoint),
        typeof(AbilityEffectRunActionOnClickedUnit),
        typeof(AbilitySwtichDualCompanionChecker),
        typeof(AbilityTargetIsFavoredEnemy),
        typeof(AdjacencyRestriction),
        typeof(AlignmentRestriction),
        typeof(ArtisanRestriction),
        typeof(Aviary),
        typeof(BuildingAdjacentGrowthIncrease),
        typeof(BuildingAdjacentResourceIncrease),
        typeof(BuildingCountsAs),
        typeof(BuildingGlobalGrowthIncrease),
        typeof(BuildingLoneSlotBonus),
        typeof(BuildingMoraleChangeBonus),
        typeof(BuildingUpgradeBonus),
        typeof(CaptalLevelRestriction),
        typeof(DLCRestriction),
        typeof(LoneSlotRestriction),
        typeof(ProjectRestriction),
        typeof(StatRankRestriction),
        typeof(BirthdayTrigger),
        typeof(BuildingSequenceCostMultiplierReduce),
        typeof(BuildingTrigger),
        typeof(EventResolutonTrigger),
        typeof(EventStartTrigger),
        typeof(KingdomConditionalStatChange),
        typeof(KingdomEventFixedBonus),
        typeof(KingdomEventModifier),
        typeof(KingdomIncomePerSettlement),
        typeof(KingdomIncomePerStat),
        typeof(KingdomIncomePerUnrest),
        typeof(KingdomUnrestChangeTrigger),
        typeof(MaxArmySquadsBonus),
        typeof(RegionBasedPartyBuff),
        typeof(SettlementTrigger),
        typeof(EventAISolution),
        typeof(EventRecurrence),
        typeof(ExclusiveProjects),
        typeof(MarkAsCrusadeProject),
        typeof(AttackBonusAgainstTacticalOwner),
        typeof(AttackBonusAgainstTacticalTarget),
        typeof(DamageBonusAgainstTacticalOwner),
        typeof(ArmyForceMelee),
        typeof(TacticalCombatChangeFaction),
        typeof(TacticalCombatEndMovementTrigger),
        typeof(ArmyAbilityTags),
        typeof(ModifyArmyUnitSpellPower),
        typeof(CustomProgressionPropertyGetter),
        typeof(MaxAttributeBonusGetter),
        typeof(ChangeObjectiveOnUnlockTrigger),
        typeof(GiveUnlockOnObjectiveTrigger),
        typeof(SummonPoolCountTrigger),
        typeof(AddSavesFixerArmorRecalculator),
        typeof(EnchantmentAddBuffWhileInStealth),
        typeof(ImproveEnhancmentIfHasEnchantment),
        typeof(ModifyWeaponStatsConditional),
        typeof(NaturalDamageStatReplacement),
        typeof(WeaponGroupAttackBonusEquipment),
        typeof(WeaponGroupDamageBonusEquipment),
        typeof(AddFactIfArchetype),
        typeof(AllSpellsParamsOverride),
        typeof(AttackDiceBonusOnce),
        typeof(AttackOfOpportunityAttackBonusAgainstFactOwner),
        typeof(CannyDefense),
        typeof(DRWithPool),
        typeof(DamageBonusAgainstSize),
        typeof(DefaultSourceBone),
        typeof(DisableIntelligence),
        typeof(DungeonClassRestrictedBuff),
        typeof(EvasionAgainstDescriptor),
        typeof(HarmoniousMage),
        typeof(IgnoreDamageGrowthByDifficulty),
        typeof(IncreaseWeaponDamageByBuffStack),
        typeof(RecalculateFeatures),
        typeof(RemoveAfterCast),
        typeof(ReplaceCasterLevelOfFeature),
        typeof(SaturationAuraComponent),
        typeof(SpellFixedCL),
        typeof(SpellLevelByRank),
        typeof(SpendChargesOnSpellCast),
        typeof(SwitchOffAtCombatEnd),
        typeof(TwoWeaponDefense),
        typeof(VolleyFireAttackBonus),
        typeof(WeaponCritAutoconfirmAgainstSize),
        typeof(WeaponImprovised),
        typeof(WeaponParametersCriticalMultiplierIncrease),
        typeof(AddStatBonusIfHasSkill),
        typeof(AfterbuffIfHasFact),
        typeof(ApplyBuffOnHit),
        typeof(BuffMiraculousHealing),
        typeof(BuffPerceptionBonus),
        typeof(BuffSaveOrDieEachRound),
        typeof(BuffStatPenaltyDice),
        typeof(BuffStrengthSkillsBonus),
        typeof(DamageOnRemove),
        typeof(DamageWithDescriptorRecievedTrigger),
        typeof(GreaterSnapShotBonus),
        typeof(HealOverTime),
        typeof(HealOverTimeIfHasFact),
        typeof(TemporaryHitPointsEqualCasterLevel),
        typeof(AddEquipmentToPet),
        typeof(CompanionRecruitTrigger),
        typeof(CompanionUnrecruitTrigger),
        typeof(CustomEventTrigger),
        typeof(DamageTypeTrigger),
        typeof(ExperienceTrigger),
        typeof(MapObjectDestroyTrigger),
        typeof(MapObjectPerceptionTrigger),
        typeof(PlayerOpenItemDescriptionFirstTimeTrigger),
        typeof(SkillCheckInteractionTrigger),
        typeof(EtudeBracketShowObjects),
        typeof(EtudeGameOverTrigger),
        typeof(DestroyCutsceneOnLoad),
      };
  }
}
