using System;
using System.Collections.Generic;

namespace BlueprintCoreGen.CodeGen.Overrides.Ignored
{
  // Examples generated by TypeUsageAnalyzer
  internal static class IgnoredBlueprintScriptableObjects
  {
    public static readonly List<Type> Types =
      new()
      {
        typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonArea),
        typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonBoon),
        typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonRoot),
        typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonShrine),
        typeof(Kingmaker.Dungeon.Blueprints.BlueprintGenericPackLoot),
        typeof(Kingmaker.Blueprints.BlueprintPet),
        typeof(Kingmaker.Blueprints.BlueprintActionList),
        typeof(Kingmaker.Blueprints.Items.Equipment.BlueprintItemEquipmentHandSimple),
        typeof(Kingmaker.Blueprints.Encyclopedia.BlueprintEncyclopediaSkillPage),
        typeof(Kingmaker.Kingdom.Artisans.ArtisanItemDeck),
        typeof(Kingmaker.Kingdom.Artisans.BlueprintKingdomArtisan),
        typeof(Kingmaker.Kingdom.Blueprints.BlueprintKingdomClaim),
        typeof(Kingmaker.Kingdom.Blueprints.BlueprintKingdomUpgrade),
        typeof(Kingmaker.Armies.TacticalCombat.Brain.BlueprintTacticalCombatAiPostponeTurn),
        typeof(Kingmaker.Designers.Mechanics.Collections.BuffCollection),
        typeof(Kingmaker.AI.Blueprints.BlueprintAiRandomMove),
        typeof(Kingmaker.AI.Blueprints.BlueprintAiRunAway),
        typeof(Kingmaker.AI.Blueprints.Considerations.ConsiderationCustom),
        typeof(Kingmaker.AI.Blueprints.Considerations.IsEngagedConsideration),
        typeof(Kingmaker.AI.Blueprints.Considerations.SavingThrowConsideration),
        typeof(Kingmaker.AI.Blueprints.Considerations.SpecificUnitBlueprintConsideration),
      };
  }
}
