using System;
using System.Collections.Generic;
using Kingmaker.Dungeon.Blueprints;
using Kingmaker.Blueprints;
using Kingmaker.Blueprints.Items.Equipment;
using Kingmaker.Blueprints.Encyclopedia;
using Kingmaker.Kingdom.Artisans;
using Kingmaker.Kingdom.Blueprints;
using Kingmaker.Armies.TacticalCombat.Brain;
using Kingmaker.Designers.Mechanics.Collections;
using Kingmaker.AI.Blueprints;
using Kingmaker.AI.Blueprints.Considerations;

namespace BlueprintCoreGen.CodeGen.Overrides.Ignored
{
  // Examples generated by TypeUsageAnalyzer
  internal static class IgnoredBlueprintScriptableObjects
  {
    public static readonly List<Type> Types =
      new()
      {
        typeof(BlueprintDungeonArea),
        typeof(BlueprintDungeonBoon),
        typeof(BlueprintDungeonRoot),
        typeof(BlueprintDungeonShrine),
        typeof(BlueprintGenericPackLoot),
        typeof(BlueprintPet),
        typeof(BlueprintActionList),
        typeof(BlueprintItemEquipmentHandSimple),
        typeof(BlueprintEncyclopediaSkillPage),
        typeof(ArtisanItemDeck),
        typeof(BlueprintKingdomArtisan),
        typeof(BlueprintKingdomClaim),
        typeof(BlueprintKingdomUpgrade),
        typeof(BlueprintTacticalCombatAiPostponeTurn),
        typeof(BuffCollection),
        typeof(BlueprintAiRandomMove),
        typeof(BlueprintAiRunAway),
        typeof(ConsiderationCustom),
        typeof(IsEngagedConsideration),
        typeof(SavingThrowConsideration),
        typeof(SpecificUnitBlueprintConsideration),
      };
  }
}
