using BlueprintCoreGen.CodeGen.Methods;
using System;
using System.Collections.Generic;

namespace BlueprintCoreGen.CodeGen.Overrides.Examples
{
  // Examples generated by TypeUsageAnalyzer
  internal static class ExampleConditions
  {
    public static readonly Dictionary<Type, List<Blueprint>> Examples =
      new()
      {

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.ItemsEnough),
          new()
          {
            new Blueprint("AcidButton1_CheckPassedActions", "2a969038211346358597f80d271d9b94"),
            new Blueprint("Banter_Seelah_ch5_2", "d10472a181109b94aa8cbf156f8b91d9"),
            new Blueprint("ZeorisDagger_ReforgeProject", "22e8219563e84f11b6aed62661030770"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsCaster),
          new()
          {
            new Blueprint("AllRoundDefenseAreaEffect", "5e56c4ff29094864aa23ec9b5b4ccf57"),
            new Blueprint("GhoulTouchAreaEffect", "e6a5bbb2af2448aa894e6126ef1e9187"),
            new Blueprint("ZeroState", "c6195ff24255d3f46a26323de9f1187a"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsAlly),
          new()
          {
            new Blueprint("AcidBomb", "fd101fbc4aacf5d48b76a65e3aa5db6d"),
            new Blueprint("EnforcedVigor", "29d7f1e36132b874084402c207847ad1"),
            new Blueprint("WrathOfTheUndeadArea", "22e31702587142ddb99391d589ba538b"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionTargetIsYourself),
          new()
          {
            new Blueprint("ArcanistExploitArmoredMaskAbility", "2d7d510c6e2e3e54ab9eee84a41fa2cf"),
            new Blueprint("FiendTotemGreaterArea", "9ebde3219b12ca84c8e734a8430a57f8"),
            new Blueprint("WreckingBlowsEffectBuff", "15dd42009de61334692b22fd7a576b79"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.TargetHasArmyTag),
          new()
          {
            new Blueprint("Aeon5BaneOfDemonsAbility", "843145bc1b9b45229c40b1a2128095f0"),
            new Blueprint("RangerBlindingTrapArea", "b4b532d5cd6f81642a6783a93ace06d1"),
            new Blueprint("RitualHealAbility", "08c5571e87eccfc47a8325f530e3693c"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionCasterHasFact),
          new()
          {
            new Blueprint("AcidBomb", "fd101fbc4aacf5d48b76a65e3aa5db6d"),
            new Blueprint("InflictSeriousWoundsMass", "820170444d4d2a14abc480fcbdb49535"),
            new Blueprint("WrathOfAncestorEnchantment", "4dbc03bd6223b484d8cd9afc3e0369b0"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionAlignment),
          new()
          {
            new Blueprint("AeonAoOGazeArea", "bc346635e3d04df7968249d59ea756ba"),
            new Blueprint("HolySmiteFlesheater", "03d6ca89591b42a4af3ea9eee27a80f0"),
            new Blueprint("WordOfChaos", "69f2e7aff2d1cd148b8075ee476515b1"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionHasBuff),
          new()
          {
            new Blueprint("AirBlastAbility", "31f668b12011e344aa542aa07ab6c8d9"),
            new Blueprint("FlameAoe", "69e3532f0321e4144bcc0d0d3f372ca5"),
            new Blueprint("ZeorisDaggerRing_BetrayalFeature", "1f6fabee66d54992bc912236d36b50f8"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionHasFact),
          new()
          {
            new Blueprint("1_FirstDeathAbility", "4445d9d1c21141c6a0bb24baf373ef78"),
            new Blueprint("GraspingFrostEnchantment", "3e9a8fdd71ea0b64d8aeaa44b8b6ea3b"),
            new Blueprint("ZeorisDaggerRing_GoverningAllyBuff", "02680be495534b629d543daa89b47079"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionSharedValueHigher),
          new()
          {
            new Blueprint("AmiriCampBuff", "f04177fdba7bb324589b7f2b0fd67604"),
            new Blueprint("ShadowShamanShadowsAbility", "085b4d4d0c5747bb8b1173e914c24d20"),
            new Blueprint("WitchHexMajorHealingAbility", "3408c351753aa9049af25af31ebef624"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsEnemy),
          new()
          {
            new Blueprint("AcidBombMaceAbility", "100a5f494cf264f4690ae931a10d2d94"),
            new Blueprint("HexChannelerChannelNegativeEnergy", "fb2df4978dd4fd745a7aaecfd1068512"),
            new Blueprint("ZippyMagicFeature", "30b4200f897ba25419ba3a292aed4053"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionHasBuffFromCaster),
          new()
          {
            new Blueprint("AnomalyDistortionBuff", "599b46d94d454526bf5893a4724d4fbe"),
            new Blueprint("GowrowSonicShortspearFeature", "b0b7b2b56b0c75841bab1861724d3a99"),
            new Blueprint("WoundWormsLair_BlackDragonFrightfulPresenceArea", "382910feb429e1449b3f8f2a633e3244"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.TacticalCombatSquadHitPointsCondition),
          new()
          {
            new Blueprint("ArmyFingerOfDeath", "16da1e53252444cc9f14bcf1c72f58fb"),
            new Blueprint("ArmyMeleeCounterAttackFeature", "9f86b8f30438920458feda7313591ec2"),
            new Blueprint("ArmyRangedCounterAttackFeature", "4d59f676f59579944948f8c461731ab8"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionStatValue),
          new()
          {
            new Blueprint("AeonAoOGazeAllyBuff", "a85b9737fba146dcb3468526d67fbc0e"),
            new Blueprint("FeintAbility", "1bb6f0b196aa457ba80bdb312dc64952"),
            new Blueprint("WeaponFocus", "1e1f627d26ad36f43bbd26cc2bf8ac7e"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.GreaterThan),
          new()
          {
            new Blueprint("Aeon_CheckCountersAfterCh3", "5cc29b42d3264930b8e56d6005dad1d7"),
            new Blueprint("CommandUnitAttack5", "761bc17b6b2e4224840a5846c9fbe8b2"),
            new Blueprint("VaultOfGraves_MythicDemonChapter03", "e3fb405c90492e946a02e176a10268ef"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Conditions.KingdomRegionIsConquered),
          new()
          {
            new Blueprint("FlagDiplomacy7CrusadeResourcesForRegions", "8663e81969a647fe9d6e8c3afd7d9172"),
            new Blueprint("KingdomMoraleFlagChapter5Regions", "b01624ee06444738964b678259f31a20"),
            new Blueprint("Obj2_1", "31325a3a01ba44a69d3c205784cc1816"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsMainTarget),
          new()
          {
            new Blueprint("AbandonedKeep_AcidTrap", "e7dadeb8b1d78a341bb4357b502da424"),
            new Blueprint("ExplodingArrowsIceBlastAbility", "35d2f23a727a4e358ea230525c6afd9d"),
            new Blueprint("WideSweepAbility", "69811d984ba4ab8419873b09c1641e36"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionCasterHasBuffWithDescriptor),
          new()
          {
            new Blueprint("AnimalisticPerseveranceFeature", "1a3d8a5e342c47a7b721ca699a9613ed"),
            new Blueprint("BracersOfAnimalFuryFeature", "0556a23dd7591fb49a18af3095be631d"),
            new Blueprint("ShadowMadnessBuff", "79aa1817f0b0447d8c81e59ec5c79b30"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionDifficultyHigherThan),
          new()
          {
            new Blueprint("AngelRepelTheProfaneBuff", "50a18ee630a4973479e9950011425748"),
            new Blueprint("GhoulParalysisFeature", "d781b144ccf19b84a89cb0d45cbfb7ee"),
            new Blueprint("WightEnergyDrainAbility", "35a7f7e6ad5b4374e812fc10ec1c836c"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionWeaponAnimationStyle),
          new()
          {
            new Blueprint("FuriousFocus", "f09b89812cc94b89a09069671002b899"),
            new Blueprint("GreyGarrison_SuperMythicBuff", "4b11247a4988c254fb9d1cd67f0b1e4a"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsInCombat),
          new()
          {
            new Blueprint("AngelHaloArea", "7aa654dc15f051b4e865dc82b6765b0c"),
            new Blueprint("DLC3_VeryHotIslandMediumArmorArmorBuff", "586d56b36b9c491db83da4f38c51c0d8"),
            new Blueprint("ZonKuthonScarBuff", "fbb677d91f924b99a3610ae79f6468fa"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsPartyMember),
          new()
          {
            new Blueprint("AloneinTheDarkLastManStandingFeature", "3ca1d2a2633c46b69236fbc637db6980"),
            new Blueprint("FafnheirWildMagicBuff", "c3fffad183c54cf29c58bcfd63bbbae1"),
            new Blueprint("WoundingBattleaxeBleedBuff", "b6452a2ac912260409a18aa8e69e60f7"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.EtudeStatus),
          new()
          {
            new Blueprint(" DLC5_b2_warlord_dialogue ", "7044ec8b144e416395eae35d5a2eba82"),
            new Blueprint("Cue_0010", "0ab65fc5bbd26e1418f37be70ef0166d"),
            new Blueprint("ZombiesOnStreets", "ffcf5bca11694784686d9947ed226a88"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.CurrentAreaIs),
          new()
          {
            new Blueprint("AeonEyeEnemyVisualBuff", "9815f77129674e8e886de2d458ecdf49"),
            new Blueprint("Cue_53", "51afcdfbe2584ed6a196361bd8cae8fb"),
            new Blueprint("WoljifQ", "d79f05dbd35b468fa16312f30d61a5e1"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.QuestStatus),
          new()
          {
            new Blueprint("30_HeroicVictory", "a43192eddffb455db6004059811ac92d"),
            new Blueprint("Cue_0018", "1503b0f31a2f54a43a31248b9ce487c7"),
            new Blueprint("ZigguratNoMoreLich", "ca82ea555e8408c4e8839cdd5079e099"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.HasBuff),
          new()
          {
            new Blueprint("2Wave", "4e1dcba08c1e4a89aea4aaa07f8f89ae"),
            new Blueprint("DLC1_SpinnerLair", "20b90b6349c54efaac72075bf9d533f0"),
            new Blueprint("WhispersOfMadnessAttach", "72d6ba35e78ff9e4f8e59ef16f192c60"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionCompare),
          new()
          {
            new Blueprint("Areelu_UnbreakableDefenseBuff", "57572f514d5b49bf98432026c80382c3"),
            new Blueprint("DragonLevel1MaxAbilityWisdomFeature", "b0b5d090fb6e45acb818d6efedf7b872"),
            new Blueprint("TransmutationSchoolStrengthAbility", "aadee249a033b2747b63344a758e91be"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsInCombat),
          new()
          {
            new Blueprint("AneviaDialog", "85d9ab0f99b3f914bb10671c9c63f6a3"),
            new Blueprint("Graveyard_2WP_Skipped_SZ", "4701a72e8988461e85a3e7f87ed5ac00"),
            new Blueprint("WP_1_ScriptZone", "0613d54edb72463e8bcada03f359bf91"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionSize),
          new()
          {
            new Blueprint("AeonNormalizeSizeGazeEnemyBuff", "dc42e955adbd444fbb3082687080117b"),
            new Blueprint("DLC6PrimalInevitable_Buff_AeonGazeEnemy", "16b4793b6eba42779fbc5677028f82fa"),
            new Blueprint("WintersMarkEnchantment", "0641db56869d87c4bb387e5ae4a18a0e"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionBuffRank),
          new()
          {
            new Blueprint("AlchemistBombsFeature", "c59b2f256f5a70a4d896568658315b7d"),
            new Blueprint("ExtraDiscoverySelection", "537965879fc24ad3948aaffa7a1a3a66"),
            new Blueprint("VengefulCometsBuff", "df180c5adffa4d6dbb16e57fc1c48232"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.HasFact),
          new()
          {
            new Blueprint("AmuletOfUnforgivingElementsFeature", "2cc9b7e8d7117a9458285333822bf95d"),
            new Blueprint("CommandDelay 23", "c1ca606efdb69534da31e82867e55bef"),
            new Blueprint("UncotrollableRageBuff", "06bf19096c1f4d9c9252cf60a08e0e2c"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionTargetIsArcaneCaster),
          new()
          {
            new Blueprint("DLC3_IllusionIslandCasterBuff", "3f2bbe4dbb22461aa8392a5e46de62bc"),
            new Blueprint("Feeblemind", "444eed6e26f773a40ab6e4d160c67faa"),
            new Blueprint("SorceriousGownFeature", "40c8515843864766844ab8b69ef1f29b"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionHasUniqueBuff),
          new()
          {
            new Blueprint("DLC3_RageConfusionIsland", "6401e7d62cf6424a95a858bff65b2000"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionCompareTargetHP),
          new()
          {
            new Blueprint("BoneSpearConjure", "ca8bc7d438e6b004a87222f3c32572f2"),
            new Blueprint("Kakuen_takaRepairShieldAreaEffect", "55fc2bd8179a4bcb9034a65706609eb4"),
            new Blueprint("Unused_SZ_1", "204c7132bafa41c993ffdb9ae675d5eb"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsWeaponEquipped),
          new()
          {
            new Blueprint("AnomalyTemplateDefensiveRandomizerBuff", "1a72d85f20f14f1b84d20b8b6e44734e"),
            new Blueprint("FinesseTrainingTentacle", "59ba33d61ab94872813900e403ccc078"),
            new Blueprint("WeaponFocus", "1e1f627d26ad36f43bbd26cc2bf8ac7e"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitArmor),
          new()
          {
            new Blueprint("ArmorFocusHeavyMythicFeatureOffenceBuff", "fcd913568e1544108eceb8db2a90cd0f"),
            new Blueprint("ArmorFocusMediumMythicFeatureOffenceBuff", "a9446282d567471496566a3b464559dc"),
            new Blueprint("DLC3_VeryHotIslandMod", "a9352268e6a74a9fb7db6defb71cc55a"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.DungeonIsTier),
          new()
          {
            new Blueprint("Blessing_Interaction", "ff4a347df77e4cad971249c25d9a1589"),
            new Blueprint("DLC3_WildMagic_Spells_Tier3", "9966b4a4042745aca41d79420dc0d271"),
            new Blueprint("RewardTrader_Tier3", "b92e487220524c0f945a36436994d2f8"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitIsDead),
          new()
          {
            new Blueprint("AasimarGirlSlave_Actions", "4c1760ddc1a183b4f94ee50cc47f4c37"),
            new Blueprint("CommandMoveUnit1", "fa02f90950884855bb003c789fa30b05"),
            new Blueprint("WenduTraitor_DrezensStreet", "aaa0452f52514e46bbc9a52fa95f467b"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.PartyUnits),
          new()
          {
            new Blueprint("BossCastSpell_zone", "5efbf1ebdf0387041b437ba46fc2773c"),
            new Blueprint("Leaver_D4", "bb1882474ed5493cb1c7b8aa8209d006"),
            new Blueprint("WatchPoint_SZWall_FoW", "0f1fdc5a42ea41a4b87da4021e89dabd"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionHasBuffWithDescriptor),
          new()
          {
            new Blueprint("AngelfireApostleVersatileChannelRestorationLesser", "95e3e99ea2f5932408b0310ebc7e9af1"),
            new Blueprint("MantisZealotMantisSwarmFeature", "aba4b42c3cad4bcdaaf79b1a52778591"),
            new Blueprint("ZonKuthonBuff", "83ee9bf48b4249858df8f8ea5fe6ef06"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsUnconscious),
          new()
          {
            new Blueprint("DeepSlumber", "7658b74f626c56a49939d9c20580885e"),
            new Blueprint("RainbowPattern", "4b8265132f9c8174f87ce7fa6d0fe47b"),
            new Blueprint("ZonKuthonScarBuff", "fbb677d91f924b99a3610ae79f6468fa"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionCompareCasterHP),
          new()
          {
            new Blueprint("BracersOfOverwhelmingVigorFeature", "b34921b9358e1154783b98fb6aac3cae"),
            new Blueprint("PlagueDeathQuarterstaffFeature", "357d9df84a28fa949a575e8841c4e75e"),
            new Blueprint("ZonKuthonScarHalfHPTriggerBuff", "b5eb1d0094f744889ca22bb4cfc1e648"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionCharacterClass),
          new()
          {
            new Blueprint("AasimarHaloToggleAbility", "248bbb747c273684d9fdf2ed38935def"),
            new Blueprint("DogFamiliarAbility", "c1d499b277b473a47a026a732e036ca4"),
            new Blueprint("WrathOfArodenAbility", "77a36621c53f41adab893ac850c70c64"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.OrAndLogic),
          new()
          {
            new Blueprint("!Octavia_Companion_Warrior_Test", "0f5938a10fd0d3644be33747d6d2b11c"),
            new Blueprint("Cue_0011", "0b6c62f7ee00470e961154ca4f968886"),
            new Blueprint("ZigguratZachariusInZiggurat", "2844d387f27a0bb468f72603dd15eda2"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.False),
          new()
          {
            new Blueprint("2ALR_BlueprintAreaTransition", "caa1a113bb2c18e4bb187348664d4c99"),
            new Blueprint("IntoIllusion_BlueprintAreaTransition", "ba5a1373eb755be43af952e131b96dec"),
            new Blueprint("ZigguratEnter_AreaTransition", "c8a709930aa977d499dc797c22f42bb9"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionDistanceToTarget),
          new()
          {
            new Blueprint("BurstOfSonicEnergy", "b5a2d0e400dd38e428c953f8a2be5f0b"),
            new Blueprint("MajorConsumeFleshUndeadAreaEffect", "6d1317c8ca3b462c9b0db3d5f4d11e68"),
            new Blueprint("WitheringFleshAreaEffect", "7ba9b0377e784c24abf75fe651fd1cea"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsAnimalCompanion),
          new()
          {
            new Blueprint("AnimalInsightArea", "d3c9117d43833df49a253df19377bbfe"),
            new Blueprint("FafnheirDeathCurseFeature", "0167db2f420141c4860851b62c5d0d55"),
            new Blueprint("HippogriffFlyingAttackAbility", "7d0bc62733414cabae1466df04f04910"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionProperty),
          new()
          {
            new Blueprint("CavalierRetributionAllyBuff", "8bce0264674d4e79bfc8cf524790ba9a"),
            new Blueprint("CavalierStandAgainstDarknessAllyBuff", "6876867a0faf46b6a7d8527efee98682"),
            new Blueprint("ComeAndGetMeEffectBuff", "bfe8c363c0a8438a944ec21d9bb896ce"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionHasBuffImmunityWithDescriptor),
          new()
          {
            new Blueprint("DLC6_FirstDragonBreathWeapon", "d56ae3d0f38c44a2a1d385e234aef613"),
            new Blueprint("PurpleWormSwallowWholeFeature", "dee864aec4a0d344b913dd27a4b504cb"),
            new Blueprint("VrockSporesAbility", "19400435d35a3064b975861ef0a2c462"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionInContext),
          new()
          {
            new Blueprint("CarrionStormDamageAbility", "71fef7b9e4564e4a915983e46e2c708d"),
            new Blueprint("KakuentakaDamageAbility", "a5f6e16e23724b9ebaab9f828cb6e7bf"),
            new Blueprint("WrathOfArodenAbility", "77a36621c53f41adab893ac850c70c64"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionHitDice),
          new()
          {
            new Blueprint("Arbitrament", "0f5bd128c76dd374b8cb9111e3b5186b"),
            new Blueprint("ColorSpraySnowball221", "8edf1ce73f4d4ce6a7064178aaf63b21"),
            new Blueprint("WoundWormsLair_BlackDragonFrightfulPresenceArea", "382910feb429e1449b3f8f2a633e3244"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionTargetCanSeeInvisible),
          new()
          {
            new Blueprint("BlinkBuff", "c168c6a0e471e924b8c69b31c6352587"),
            new Blueprint("CallingForAFeastBlinkBuff", "cf9a122d832a498395b56a92233af763"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsPetDead),
          new()
          {
            new Blueprint("AnimalFocusBearBuff", "fa25fec82271c93478194c52a20ce733"),
            new Blueprint("AnimalFocusMouseBuff", "127de9efe375a364d94fc68d94ad231a"),
            new Blueprint("AnimalFocusTigerBuff", "18e0d3842308de14ca3fde356bf92b92"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionSharedValueHitDice),
          new()
          {
            new Blueprint("BloodHazeEffectBuff", "06bd4a59646b7fa468166d1c745f31dc"),
            new Blueprint("SecretOfHookingAndSummoning", "72ae181281075c74ea2d1ae74ad95597"),
            new Blueprint("WitchHexLayToRestAbility", "1bb5466b9bfcb5e47b9f667dad5784f9"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionAlive),
          new()
          {
            new Blueprint("AngelBringBackTouch", "067035da0186d6e43bb4138f433911ee"),
            new Blueprint("GhoulTouchAreaEffect", "e6a5bbb2af2448aa894e6126ef1e9187"),
            new Blueprint("SwarmFeastArea", "23d8c63c3af634843aa11f5a169683b5"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionMaximumBurn),
          new()
          {
            new Blueprint("ElementalEngineBurnoutTriggerFeature", "090d39a5813d4537ba24b55fff7fe6be"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsEqual),
          new()
          {
            new Blueprint("AirBlastAbility", "31f668b12011e344aa542aa07ab6c8d9"),
            new Blueprint("ExtendedRangeWaterBlastAbility", "11eba1184c7108846a665d8ca317963f"),
            new Blueprint("XO_Puzzle_2_complete", "8288ad6ec196461f963d6160edbfaca4"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionFavoredEnemy),
          new()
          {
            new Blueprint("FavoredEnemySpellcasting", "0226d84afe68462da8a392798f1225b8"),
            new Blueprint("MasterSpyCasterBuff", "ff2e84b215b187347a406670ab2f5cf7"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.DayTime),
          new()
          {
            new Blueprint("AeonQ3Scene_DayTime", "ffb3b99adfa368444b4a46ea36e5aec9"),
            new Blueprint("DLC4_Wolf_Night", "e06f060f459e4a6191e559fca3fd636a"),
            new Blueprint("WenduagQ1Drill", "76c88c9c00369e5419d8b0c70b67eef6"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionTargetIsBlueprint),
          new()
          {
            new Blueprint("EnhancementBonusWilloWisp", "012f72c2749c2e94eb3c389f3f077aac"),
            new Blueprint("FXActionHolder", "8b6dfee48d134485ae553b510662f601"),
            new Blueprint("ThunderingClawPet", "e95c2acd75e1d964eaece4a9958d31d5"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.FlagUnlocked),
          new()
          {
            new Blueprint("!Octavia_Companion_Warrior_Test", "0f5938a10fd0d3644be33747d6d2b11c"),
            new Blueprint("Cue_0010", "7113be742a194992b4f27504895bae86"),
            new Blueprint("ZigguratRiot", "5ecb3695c95e4bd4b836a0deac1ecfd7"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextSwarmHasEnemiesInInnerCircle),
          new()
          {
            new Blueprint("BloodlineSerpentineDenOfSpidersSpiderSwarmDamageBuff", "9c414efda39e67344846171c1547edc1"),
            new Blueprint("LocustSwarmDamageBuff", "e9e341bff1efce2469bdf6577672bb4d"),
            new Blueprint("VescavorSwarmDamageBuff", "ddc847a49246ded4f93fe2bf0e2a7dab"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionAlignmentDifference),
          new()
          {
            new Blueprint("DeterminedZeal", "a59b08fdf85465a48b036fd9ef4bcc71"),
            new Blueprint("DivineAnathema", "1777a6ff0ae558749b76766a7a575802"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionArea),
          new()
          {
            new Blueprint("GeomancyAbilityAreaEffect", "e624d8c0c594408bbf413e0b353098e5"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsShieldEquipped),
          new()
          {
            new Blueprint("AbruptEndEnchantment", "66f1ac1f205e99f4e83c9b3aa8f0b0b1"),
            new Blueprint("MagicalVestmentShield", "adcda176d1756eb45bd5ec9592073b09"),
            new Blueprint("WarpriestShieldbearerChannelPositiveHarm", "894e20539c353c74ab2733a056351947"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.SettingBoolValue),
          new()
          {
            new Blueprint("AutoSave_Interaction_ForceDisable", "3e60eb76712c47b492ef33da5e8f12d8"),
            new Blueprint("SaveTutorial", "9e1cc5dc3d5945b6a19f9de0cf7d1373"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.ItemFromCollectionCondition),
          new()
          {
            new Blueprint("Darkness_AlushinyrraHub", "cbd58d1c17f043618053e6633e70b4df"),
            new Blueprint("DungeonLootMagic", "24e7b8fe37484e06bc88738c9f032da2"),
            new Blueprint("Mimic_Items_Books", "1edfca79fc5347f6a76dd105879a7fe9"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.ItemBlueprint),
          new()
          {
            new Blueprint("Bowl_ItemRestriction", "10283016767d4ed3b36db71bea8c450d"),
            new Blueprint("Purple_Slot_1_3_Art_1_2f", "4d8f9308cb80ab3488acb8ed79eda4ed"),
            new Blueprint("YellowPuzzleSolveChecker", "00016e6128651a548b2c50f23456a3e0"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.DungeonIsTierReached),
          new()
          {
            new Blueprint("RewardLoot_BesmaraBoss", "bc8bf25e3038475e9a2cc9cfddfc1ee6"),
            new Blueprint("RewardLoot_ConsumablePotion_Tier1_close", "f96a1f37fcd6427d81c85cf0cd7ba92b"),
            new Blueprint("RewardObject_LegacyExp_close", "36158ab6a3f54e75bdbb462453871efa"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionHasItemCharges),
          new()
          {
            new Blueprint("BaneNonHumanFeature", "54aa118979b44497b4db1bb861f78db5"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionCasterWeaponInTwoHands),
          new()
          {
            new Blueprint("BracersOfDominanceFeature", "cdc4f29bc423d454e9af87a514a14de7"),
            new Blueprint("TwoWeaponFeintBuff", "621523572cfe4dc48ee1bdddba2f4725"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionPeaceful),
          new()
          {
            new Blueprint("SoulsCloakCurseBuff", "40f948d8e5ee2534eb3d701f256f96b5"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsUnitLevelLessThan),
          new()
          {
            new Blueprint("CommandUnitCastSpell1", "e434cffdc4d847089f84b666dce699a8"),
            new Blueprint("CommandUnitCastSpell3", "c7cbbb646d6a4e78ac0acbcf8413a89e"),
            new Blueprint("SoulsCloakCurseBuff", "40f948d8e5ee2534eb3d701f256f96b5"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsFlanked),
          new()
          {
            new Blueprint("MarksmansSteadyHandFeature", "86baea5d6bde19d4b9845c5c33eeec1b"),
            new Blueprint("TricksterSneakyQuack", "bf41d492ff138ae4e9775e6fd9c8011e"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsFlatFooted),
          new()
          {
            new Blueprint("AmbuscadingSpell", "2fb48bed3746431bb3080c34f11597da"),
            new Blueprint("StagHelmetFeature", "32c73d4df6c4f4746a748bc1f140d629"),
            new Blueprint("VigilantWatchFeature", "d4cf7afc49b81e34989f2dfa76889fed"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionUnconsciousAllyFarThan),
          new()
          {
            new Blueprint("ParagonOfDefendersAuraBuff", "b348cf228b07b534cb315e7c54f95379"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.InCapital),
          new()
          {
            new Blueprint("Test_Bebilith Blueprint Camping Encounter", "f2f8355d4bc8aa34195eeb2f5cf66645"),
            new Blueprint("TriceratopsStatuetteCorrectBuff", "4366d9550c8345da8bedece00a19b7a8"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsTwoHandedEquipped),
          new()
          {
            new Blueprint("AbruptEndEnchantment", "66f1ac1f205e99f4e83c9b3aa8f0b0b1"),
            new Blueprint("FuriousFocus", "f09b89812cc94b89a09069671002b899"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionCasterWeaponGrip),
          new()
          {
            new Blueprint("FuriousFocus", "f09b89812cc94b89a09069671002b899"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionDamageTransferIsApplicable),
          new()
          {
            new Blueprint("ShiftersEdgeCheckBuff", "8522c7e3c56e4bfc8cde0c298243290f"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.ObjectiveStatus),
          new()
          {
            new Blueprint("!Octavia_Companion_Warrior_Test", "0f5938a10fd0d3644be33747d6d2b11c"),
            new Blueprint("Cue_0016", "2b0dff5e82ca3254388557c797b5f3e2"),
            new Blueprint("Ziggurat_ZachariusBeginRitual", "8a020a9f01405ae4fa417500e1efd2e6"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.CompanionInParty),
          new()
          {
            new Blueprint("Alushinyrra_HigherCity_VellodusMansion", "d062cf7333b145b8bb85d4400dbea44d"),
            new Blueprint("Cue_0027", "d840080822d64e14fac385010630d8c3"),
            new Blueprint("Yozz_GreyborQ2Bark_Conditions", "e25cbb4124873114ba3b75176e004517"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsDLCEnabled),
          new()
          {
            new Blueprint("AasimarRace", "b7f02ba92b363064fb873963bec275ee"),
            new Blueprint("Edge_SarkorianWedding_Chapter05_Army14", "b3c8bd9291a34edc88b62353f2f847f9"),
            new Blueprint("UlbrigCompanion", "9a8d5b9a632a405dbc8e3af8f647a471"),
          }
        },

        {
          typeof(Kingmaker.Assets.Designers.EventConditionActionSystem.Conditions.DialogSeen),
          new()
          {
            new Blueprint("[MainHall] [Tall_DesnaPriest] Final_Bark_Conditions", "7f8be13550ec4db894002cae58c9b811"),
            new Blueprint("Banter_SeelahArueshalae_banter3", "269f77cc37f7b044296659ce4f97a368"),
            new Blueprint("ZigguratDeadRomanceTimer", "587df869a564f7046a48bbf27f017619"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.CueSeen),
          new()
          {
            new Blueprint("[Kerz]_BarkCondition", "59c232c2fa5e7c54baa235fee0e049d6"),
            new Blueprint("CommandAction", "056996bdf46140ef8673a387ccccea49"),
            new Blueprint("ZanedraInTemple", "0d22fd186d557a049b46c0fb3d623f04"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.PlayerSignificantClassIs),
          new()
          {
            new Blueprint("Answer_0001", "2a5615c36b154ef79b0f7bff878081a0"),
            new Blueprint("Cue_0060", "6ea88ed6d7ac02c42b1eb4d641db14ad"),
            new Blueprint("Gift_From_Stranger_Notification", "e688d0cd0791435eaf84bbe4561624bc"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Conditions.KingdomBuffIsActive),
          new()
          {
            new Blueprint("Aeon2FireElementals", "63364fac363349a99dd7fe96ca86dc7c"),
            new Blueprint("Event71DumpExcavation", "b0ca7e2b70c9447da43f7be86164d43c"),
            new Blueprint("Trickster5ThugPaladin", "e83a6a99081d467fb56d8afe1de6a4d5"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Conditions.KingdomProjectIsAvailable),
          new()
          {
            new Blueprint("Add4_GotoMoltenScar", "f6694c696284e2046b0f064f83c320c2"),
            new Blueprint("Event61DrakePoison", "23bd72781ce34695bc9af2468456b8af"),
            new Blueprint("Trickster5ThugPaladin", "e83a6a99081d467fb56d8afe1de6a4d5"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionHasItem),
          new()
          {
            new Blueprint("123", "535217378b8a4ca3ba5a45f0002de07c"),
            new Blueprint("Cue_0018", "31cfc8141e134d189d64631a3ce69d93"),
            new Blueprint("ZeorisDaggerEtude", "ad64557f3ad74ff0b36fce6364df6ab2"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionGarrisonClear),
          new()
          {
            new Blueprint("CreateSettlementFort21", "0b7377f7c46c6aa43bf66af6ec618836"),
            new Blueprint("CreateSettlementFort56", "ece5ff5b715642444b692d9d93b64b9c"),
            new Blueprint("CreateSettlementRiverGarrison", "947bf6259557aeb449557e4bc5228ead"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Conditions.KingdomProjectIsDone),
          new()
          {
            new Blueprint("CreateSettlementFort21", "0b7377f7c46c6aa43bf66af6ec618836"),
            new Blueprint("CreateSettlementNearRegill", "8b4cd3ebd7b3f3b4ea201bbfed62fa28"),
            new Blueprint("PF-412703", "8cddb1adab904075a656a7d4bf226271"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Conditions.KingdomStatCheck),
          new()
          {
            new Blueprint("26!_SadisticGD_Checker_Sum", "561508e5aeba4d37b7418a363411964d"),
            new Blueprint("LogisticsRankUp3Project", "de0bfee4dca3ebc4aae466ca6e799e01"),
            new Blueprint("PF-252649", "403f8687be754fe39430819391be0c73"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Conditions.KingdomRankUpConditions),
          new()
          {
            new Blueprint("Chapter05", "5b01aa690202e584888dfc600a4aac0a"),
            new Blueprint("LogisticsRankUp2Project", "e2c032467f1cf0b4d9ee4da1da92857a"),
            new Blueprint("MilitaryRankUp8Project", "11904fe03bcc431d8f8fb0a2d4ca3704"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Kingdom.Flags.KingdomMoraleFlagCondition),
          new()
          {
            new Blueprint("MoraleFlagSiegeChapter3Controller_buff", "bd5bfbd23acd4098b3a89100b61c3ce0"),
            new Blueprint("MoraleFlagSiegeChapter5Controller_buff", "30d599366a9e46fe992f9ca6fdf9365a"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Kingdom.Conditions.KingdomSettlementCount),
          new()
          {
            new Blueprint("SettlementsTracker_buff", "71dd611cd70443fcb04f0dce3bda76ef"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsCampaign),
          new()
          {
            new Blueprint("Answer_0006", "13e54e84a1344930b2d35ec4fba205ff"),
            new Blueprint("Cue_0029", "323a1a0007534614907ab14bf9e1b78f"),
            new Blueprint("Ship_translocate", "2b46c98f1687478e93b8625670f996ba"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsMainCharacter),
          new()
          {
            new Blueprint("AeonMythicClass", "15a85e67b7d69554cab9ed5830d0268e"),
            new Blueprint("FafnheirDeathCurseTimerBuff", "848cac6881f04d1fa7ddf285d740efe7"),
            new Blueprint("SwarmProtectCorpseArea", "4634d1da7c394ec4a49cb38e59e91f44"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitClass),
          new()
          {
            new Blueprint("AeonMythicClass", "15a85e67b7d69554cab9ed5830d0268e"),
            new Blueprint("Cue_0016", "3443b336153f4377a199216f7d211d72"),
            new Blueprint("TrueRazmirLoser_dialogue", "a8c8f86b2f6d4d11958e459937d8846b"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.LessThan),
          new()
          {
            new Blueprint("AddAfterThreeCourts", "4c9fddeb883f3ec459128e484d3d5ff8"),
            new Blueprint("Cue_0002", "dca3e52af2d62fc4fa74bf1d65696953"),
            new Blueprint("VrockSpawn2", "1afdb2a002bb1f54da2aedb2ec61a963"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsUnitMythicLevel),
          new()
          {
            new Blueprint("Answer_0014", "e150a8363c8e4723a0fbb0f5de6d931a"),
            new Blueprint("EveryoneIsMortal", "11dbdcadc7d74dc09e70ef386931a14f"),
            new Blueprint("SwarmThatWalksClass", "5295b8e13c2303f4c88bdb3d7760a757"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.HasTacticalMorale),
          new()
          {
            new Blueprint("Test_Bebilith Blueprint Camping Encounter", "f2f8355d4bc8aa34195eeb2f5cf66645"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitInScriptZone),
          new()
          {
            new Blueprint("Answer_0002", "d38052d00f394118945e8861f00574f5"),
            new Blueprint("DLC1_IZ_Irabeth_startDialog", "5bc8820627af4f2080c6e19d4ab8c223"),
            new Blueprint("TrueLootHideZone9", "168ca19a2ced8d448a9944c2f0f01d72"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.MapObjectRevealed),
          new()
          {
            new Blueprint("chap0", "95c4212a36594186b509e87d00d2d480"),
            new Blueprint("TheiflingRevealDoor3", "9a143d61a83c0fd4ea52262ed924ff72"),
            new Blueprint("Thieflings01_TrapReveal5", "799191689150bff488597bddf7f86c35"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.AnswerSelected),
          new()
          {
            new Blueprint("AfterNotDate_dialog", "cbe4991d3d5bad14dac33ca4e67ae2ce"),
            new Blueprint("Answer_0042", "c3eff7b7ee174c5458feea12de3078de"),
            new Blueprint("YozzTeleportsToShamirasPalase", "03e68d18fd2a47fc95917ba3f45d720d"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.CurrentChapter),
          new()
          {
            new Blueprint("Answer_8", "c3827533bf2b4c6ba276a53dcf826dc7"),
            new Blueprint("PF-217333", "e99f249471e442279e2687a1a5ef5264"),
            new Blueprint("Stone_FirstTouch_dialogue", "6a5ffbc344124764b096bf21b3662046"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitIsInAreaPart),
          new()
          {
            new Blueprint("Answer_0010", "8bbacd42e94344f8a0267b59dfbb4b8b"),
            new Blueprint("Cue_0016", "2cec7e312adf465989d916ac69358412"),
            new Blueprint("Venduag_Q2_interlude_spawnConditions", "7d2e7755a041e0241ad6babe959f8454"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Kingdom.Conditions.KingdomChapterWeek),
          new()
          {
            new Blueprint("PF-218150", "d7696062df7c4b948e1ce3e1b769fc9a"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.FlagInRange),
          new()
          {
            new Blueprint("10State_0", "1f815765df0d4d7ba19f731dfa064081"),
            new Blueprint("Cue_0039", "cd1da96cf45e49c0ab54c5b5f98dec4e"),
            new Blueprint("Zacharius_FinalBetrayal_dialogue", "5ec3e47a05de18c46b36f08c8dfbeafb"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Conditions.AutoKingdom),
          new()
          {
            new Blueprint("Add3_SearchMoltenScar", "39a11378f06fff740b8211686247d943"),
            new Blueprint("Cue_0479_DaeEvilHeir", "72401afde04343f4c898efba4b4d1880"),
            new Blueprint("WarCamp_CrusadeAnnouncement", "d95152499fa0696478cc6af83e44f029"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Conditions.KingdomEventIsBeingResolved),
          new()
          {
            new Blueprint("CrusadeEvent04", "e55f2d8389a14e6e999e23a7d1a6d736"),
            new Blueprint("CrusadeEvent46", "4f210692d86841d4bcc6cbeb28bbeeca"),
            new Blueprint("PF-378483", "f5dad497239a41fd96a12d4d1b1b38ef"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.AnotherEtudeOfGroupIsPlaying),
          new()
          {
            new Blueprint("Aeon_FirstKTC_Ch5", "a165ac24237977340b5bfceac10a67a8"),
            new Blueprint("KTC_Malessa", "ed0ec52c7c9cbcd4c87eaf97195da4a7"),
            new Blueprint("YozzTeleportsToShamirasPalase", "03e68d18fd2a47fc95917ba3f45d720d"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Kingdom.Flags.AnySettlementUnderSiege),
          new()
          {
            new Blueprint("PF-236233", "78ddb7dcceaf4dd5b6178807c258909c"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.LocationRevealed),
          new()
          {
            new Blueprint("PF-257814", "49a5027d61ec4ab7886acfb6e1daddea"),
            new Blueprint("RegillNotInParty_KickedOut", "2b2cfaa1727070c43b10729920112730"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.AnswerListShown),
          new()
          {
            new Blueprint("Answer_0008", "a3a7361d053ff5741a1fa619c6882d87"),
            new Blueprint("AnswersList_0001", "e5da46510ef941a284e5280a914ec174"),
            new Blueprint("PF-277910", "7792579c4cbc48eb896c9c0d3ef478cc"),
          }
        },

        {
          typeof(Kingmaker.Assets.Designers.EventConditionActionSystem.Conditions.AreaVisited),
          new()
          {
            new Blueprint("Answer_0007", "4df71c9b1ab9d174eaf66587e483dc61"),
            new Blueprint("PF-424113", "fe7866961dd849eabea8c01ae5c0e9a9"),
            new Blueprint("YellowPuzzleMechanic", "7e0ebe7249b75724a836537405e988bb"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Kingdom.Conditions.ArmyInLocationDefeated),
          new()
          {
            new Blueprint("PF-296978", "983af9815687400f897ef380ec8e6b09"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsLootEmpty),
          new()
          {
            new Blueprint("CavesShortcutUnlocked", "d1f433e953409144d914f15597db6e34"),
            new Blueprint("Green_Slot_1_2_IsNotEmpty", "d44ba5b7fee49e64684ce203920e5c08"),
            new Blueprint("Slot_3_3_IsNotEmpty", "85c097fd43ebd3940b6ea98b57e6f35e"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitIsNull),
          new()
          {
            new Blueprint("CommandAction", "3943d90f59434f979bae0d2f0c7937e6"),
            new Blueprint("CommandSetCombatMode 2", "6dbcd56d8a6c4974382459bcf30a8c79"),
            new Blueprint("Sitting_Param", "02c9b508081b1954e4329af6db335091"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitFromSpawnerIsDead),
          new()
          {
            new Blueprint("52_TrulyImportantDeed_Checker_Tavern", "5470ea99ea3b4bc7a7048d7f12ecb18e"),
            new Blueprint("CommandDelay7", "26ebc8012baa4d12a3ea017a57b657c5"),
            new Blueprint("VillodusBrokenFight(Convert)", "3106ac332876402b9199aa6a7b3fe10c"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.CompanionStoryUnlocked),
          new()
          {
            new Blueprint("PF-390709_EvilArushaStory", "e933ae2b386c45f4bd080bebb152ccfd"),
            new Blueprint("PF-478038", "4f81e1eb17d0488cb0577baadf4b7a21"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitWithBlueprintExists),
          new()
          {
            new Blueprint("PF-420292_1", "1d5a4ed0b3ba47c2a7718ea0a2bc2a94"),
            new Blueprint("PF-420292_2", "d47c4adaa34049aa8b5d717874cd03c2"),
            new Blueprint("PF-420292_3", "98d9def66e2c4e4495fe06c93900fbcf"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.SummonPoolCount),
          new()
          {
            new Blueprint("CommandAction", "07930ce9ce7a4211a6e0aacfa91c3585"),
            new Blueprint("DLC5_PrisonersBarks_Actions", "da00c07cd04b457997b687b0c3141c63"),
            new Blueprint("PF-487847", "685b8dc82e8b4131b3155baa846ffe8f"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.DifficultyHigherThan),
          new()
          {
            new Blueprint("ChainedDarkness_Buff_NegativeLevelController", "45b2ab2feef04dc089d5875982f7fc45"),
            new Blueprint("CommandSetCombatMode9", "0cf101aae70646d682444a0900a3781e"),
            new Blueprint("Valmallos_Feature_CombatTrigger", "f4621cc70bec4fe7b0373ed152e40570"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitIsHidden),
          new()
          {
            new Blueprint("Answer_0017", "e5bf1752b172c084f8b70351d9037e1d"),
            new Blueprint("CommandMoveUnit9", "6c3bc83b962c4c3d93bfa51b98ff17d1"),
            new Blueprint("XCOM_StartCutscene", "94342ced3cb04f96bc1f7c2914ee99f4"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitEqual),
          new()
          {
            new Blueprint("AlarmZone", "a7081ca4e21e8594f93bc84a4eb2a7a8"),
            new Blueprint("CommandUnitPlayCutsceneAnimation 93", "7036a0b60c9b45e99480d18d165fc88b"),
            new Blueprint("Ziggurat_ZachariusBeginRitual", "8a020a9f01405ae4fa417500e1efd2e6"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsCampaignImported),
          new()
          {
            new Blueprint("Answer_0001", "25507e334eab48a49c148163a087f190"),
            new Blueprint("DLC5_FrozenTemplePart", "ee12fc5bb7d446fdb1f2b0fb8c81a6de"),
            new Blueprint("Sendri_DefaultActor", "fbdd6de122cd4c8899e230778c20d0d3"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.CompanionIsDead),
          new()
          {
            new Blueprint("Answer_0015", "72050eac97c4b944f9a99ce16a680f16"),
            new Blueprint("DLC6_GreyborDiedOutsideKenabres", "fff61aabdc5f4e28ab2e5b1e7abaaeca"),
            new Blueprint("UlbrigNotInParty_Dead", "4863a2dfe7f847e588df50710ebf2a3f"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsDlcActive),
          new()
          {
            new Blueprint("PF-524476", "e84963bdacf842d69a2d7562d49ebaab"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitBlueprint),
          new()
          {
            new Blueprint("Answer_0023", "7b20b077ed8be9842a561843f40fa0c9"),
            new Blueprint("Cue_0126", "7dcd9dc63ea06594294d9961f13272a9"),
            new Blueprint("Muse_Abad_info_cutscene", "098c81e45ba142f9a761d6c2ff02507e"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsInTurnBasedCombat),
          new()
          {
            new Blueprint("Tutor_TBM_DH_Buff", "8827906427fe4a5da2c33e8d67d57a23"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionHasBuffFromThisAreaEffect),
          new()
          {
            new Blueprint("PillarOfLifeaArea", "7d0cebd89884679469533be8b680d55c"),
            new Blueprint("VescavorQueenGibberAreaEffect", "acbb8f87c5d98164dbdc1aee0f9eda2b"),
            new Blueprint("VescavorSwarmGibberAreaEffect", "a80c90f3223d8324ea0c1d75c45bd331"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Buffs.Conditions.BuffConditionCheckRoundNumber),
          new()
          {
            new Blueprint("ResonatingWordBuff", "45dadc2e291367b45b1110d3be039cad"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.AlignmentCheck),
          new()
          {
            new Blueprint("LootCondition", "d1d246fc5c3df5d48aaee5dd199e75ab"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.PlayerAlignmentIs),
          new()
          {
            new Blueprint("Aeon_Chapter04_Quests", "715233cf827adfe4e8a3e1adf8babad4"),
            new Blueprint("Cue_0074_PleaseFix", "17e298c6166609e438a721a714e7e7af"),
            new Blueprint("TestCrusadeEvent", "c8bcf035a7d947e09386fad55e986753"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.GameModeActive),
          new()
          {
            new Blueprint("CrusadeTutorial_01_Chapter2Intro", "20073002e0594c88b5af911060e8dde8"),
            new Blueprint("Tutorials_Chapter02", "b21b9dcb071cb2e4eaf91c66c0431e6d"),
            new Blueprint("Tutorials_Chapter04", "6321277cfb08bb5469b148e2a7a7cc12"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Conditions.KingdomExists),
          new()
          {
            new Blueprint("Chapter03", "15e0048c7daf0ac4999c2313b58df0e3"),
            new Blueprint("CrusadeTutorial_01_Chapter2Intro", "20073002e0594c88b5af911060e8dde8"),
            new Blueprint("CrusadeTutorial_01_Chapter2Intro_Gamepad", "a7ddb70f04c74468b7c05cb6b4275c65"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionGender),
          new()
          {
            new Blueprint("NereidBeguilingAuraAreaEffect", "466ec47d91f209646aa1b66a797b7d8d"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionTargetIsDivineCaster),
          new()
          {
            new Blueprint("DemodandTarryLairMiniboss_TitansGodslayer", "e990ddcda355abd4396fac5e49895578"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitFromSummonPool),
          new()
          {
            new Blueprint("Aranka_Area_InspireCourage", "3c0cbe32b0e1cce48b4407fd637ea203"),
            new Blueprint("CommandAction 1", "84156b459d057844a9a8427faa9562ef"),
            new Blueprint("FulsomeQueen_scene_2_failsafe", "470b6c480eedb4a46be293bca9ee705b"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionHasTouchSpellCharge),
          new()
          {
            new Blueprint("Mageblade", "eb130f652be2dc14b9a5f63608672021"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsHelpless),
          new()
          {
            new Blueprint("MusicOfDeathEnchantment", "183a4d2cc996c6f4db8641bed4b3b0c1"),
            new Blueprint("SoundOfVoidEnchantment", "69df5e137a08d9b4ead5d87bf4d5d0ac"),
            new Blueprint("TheDissectorEnchantment", "3e90ab8205854cd591538c1aff04b901"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsAmuletEquipped),
          new()
          {
            new Blueprint("HammerOfMasterpieceAbility", "0781ebffe79c5ee4caf127956b9574eb"),
            new Blueprint("HammerOfMasterpieceEnchantment", "f0a7d830ec5bfa44ba77996938db980f"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsRing2Equipped),
          new()
          {
            new Blueprint("HammerOfMasterpieceAbility", "0781ebffe79c5ee4caf127956b9574eb"),
            new Blueprint("HammerOfMasterpieceEnchantment", "f0a7d830ec5bfa44ba77996938db980f"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionIsRing1Equipped),
          new()
          {
            new Blueprint("HammerOfMasterpieceAbility", "0781ebffe79c5ee4caf127956b9574eb"),
            new Blueprint("HammerOfMasterpieceEnchantment", "f0a7d830ec5bfa44ba77996938db980f"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionCasterHasTwoWeapons),
          new()
          {
            new Blueprint("CrimsonVerdictBuff", "1c402ad36651467abe616e30549fa7fc"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Actions.ContextConditionEngaged),
          new()
          {
            new Blueprint("UltraThinEdgeFeature", "4b0308a41e4b48e09f1fee095d11b484"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsPartyInNaturalSetting),
          new()
          {
            new Blueprint("SE_IngerMaggor", "40ad6b04835d4c26b4fe62bb267a6143"),
            new Blueprint("SE_RenownExplorer", "b7204ae38aa346f3a584982fd8486ac2"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.PcRace),
          new()
          {
            new Blueprint("Answer_0005", "f2c31b4d7efe2fd49a391e65f44d8b6e"),
            new Blueprint("Cue_0033", "bfab14e84cdc6b04ca914029e263cdf6"),
            new Blueprint("WarCamp_TheatreFirstVisit", "f546a7d95bfda0e4f9cb798f00b69db3"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.CheckPassed),
          new()
          {
            new Blueprint("Answer_0001", "d902f8aff72348e882f84fc6aa9c8c2e"),
            new Blueprint("Cue_0029", "940ac039c81a0da4499e8f72291899f5"),
            new Blueprint("ReiforceTrixterBefore", "8e1bf1034cd7b6c449477b3888d2a659"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.PcMale),
          new()
          {
            new Blueprint("Answer_0029", "c4d69d3fb9060c14497b2123fc408845"),
            new Blueprint("CommandAction", "e13b97f1aad64f599a2d4d3f1b537714"),
            new Blueprint("Cue_0234", "7364becdf5cc4b94dba30a9fe7c3b790"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.NoOthersCutscenes),
          new()
          {
            new Blueprint("CommandAction", "a2f7a7c5bda46e746bc0ed3857c8c5e9"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.EnlargedEncountersCapacity),
          new()
          {
            new Blueprint("CommandAction 3", "651c3ea9f9323e943823ed497736ac74"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.PartyInScriptZone),
          new()
          {
            new Blueprint("Answer_9", "0b7d208f5f234f9791097f5aa1d5b8d5"),
            new Blueprint("CommandUnitCastSpell2", "33608356b8364cafa4c9305443372913"),
            new Blueprint("WatchPoint_SZWall_FoW", "0f1fdc5a42ea41a4b87da4021e89dabd"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.PartyCanUseAbility),
          new()
          {
            new Blueprint("Answer_0003", "5939379b7bd42484da6ba4aeb42e47f4"),
            new Blueprint("Answer_0007", "67824493fd984374d8b283a57a859a55"),
            new Blueprint("CommandUnitCastSpell", "6de48df0278243acaaffcc635326001b"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitRace),
          new()
          {
            new Blueprint("CommandPlayTimeline", "d0e106608bfc47e5ab6db68564a9d2ba"),
            new Blueprint("CommandUnitPlayCutsceneAnimation 65", "af72cbe757254361a539cc94e09f213d"),
            new Blueprint("CommandUnitPlayCutsceneAnimation9", "a30f0a0be203495195fbd73fc732bc24"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Assets.Designers.EventConditionActionSystem.Conditions.Platform),
          new()
          {
            new Blueprint("CommandAction23", "9440e15c37f34a63ad1be07e03feb53a"),
            new Blueprint("DLC6_TavernRebuilded_ThirdStage", "57d81855ec5d48799e1457c9de0bda0a"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitGender),
          new()
          {
            new Blueprint("CommandAction", "4825507512d7234448eaa92ad6384268"),
            new Blueprint("CommandUnitPlayCutsceneAnimation 67", "b63766d2c96a45acb9a9ca1308024417"),
            new Blueprint("DLC6_SpawnedUnitBecomesCosplayer_Actions_CutsceneNeutral", "360a220ca7be40a3a52b9bc56c3f4987"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsUnconscious),
          new()
          {
            new Blueprint("CommandUnitLookAt", "0a467c59d8cf78b4c911aeb922b54ef1"),
            new Blueprint("Cue_0002", "7abec2ad3309e6241a77216ee24925b6"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsPartyMember),
          new()
          {
            new Blueprint("AneviaStart", "e537a72ee38591847ad2f231ab1a1f9e"),
            new Blueprint("NecromantInMall", "1b52d48e18fb11848912a24a90694ae9"),
            new Blueprint("YakerDialogue", "c0b7b22035f586d48b0f32bd094473d6"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsEnemy),
          new()
          {
            new Blueprint("CommandAction", "5d0de4fd6d752294e932745a29b0a4d9"),
            new Blueprint("ShowPartySelection", "cb81a7635afad1e4a9fb3a5dae1b0bb3"),
            new Blueprint("Unused_SZ_1", "204c7132bafa41c993ffdb9ae675d5eb"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsLegendPathSelected),
          new()
          {
            new Blueprint("CommandAction1", "bb530e9345434933ba412402ca787bf1"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsUnitCustomCompanion),
          new()
          {
            new Blueprint("CommandAction 1", "41b3f8f33a2c0404e8f8aab17f04911a"),
            new Blueprint("CommandAction 3", "37d0bc9b4ebab6f4e9fe53edffaf4cf1"),
          }
        },

        {
          typeof(Kingmaker.Assets.Designers.EventConditionActionSystem.Conditions.BarkBanterPlayed),
          new()
          {
            new Blueprint("Banter_CameliaDaeran_banter7_pack2", "9ee702a55f580d0489e3a2529681a691"),
            new Blueprint("Banter_NenioLann_banter2", "c4592758c5cc69548b7a69f8e4775841"),
            new Blueprint("Banter_WoljifEmber_banter6", "5a59dc95c91885a459a834e464c99a1f"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.CheckFailed),
          new()
          {
            new Blueprint("Answer_0018", "8d05fd803d64f5c4ab9ffc8bf61d816b"),
            new Blueprint("Cue_0062", "58f7300ad7ecc804ca03cdf989db589c"),
            new Blueprint("Cue_9", "32716e33b77e4b6983a8dbcd2e128f49"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.PlayerTopClassIs),
          new()
          {
            new Blueprint("Cue_0003", "5ab2e262087a41ef9840818c0943ccfe"),
            new Blueprint("Cue_0011", "b52f80037fa9479b8cec3f0eb4f3d053"),
            new Blueprint("Cue_9", "5a3c9ac7639c47ac9489e9b840b6ce19"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.PcFemale),
          new()
          {
            new Blueprint("Answer_0015", "dd120d8b8a1b2974f97f3d1a866e7ae4"),
            new Blueprint("Cue_0011", "54040c1da639468eaaca394098ae341f"),
            new Blueprint("WorldwoundEdge_GMBE", "c68fad6a2d296f54f825eb1557153923"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.PlayerHasNoCharactersOnRoster),
          new()
          {
            new Blueprint("Cue_0021", "6d1aead07823d1642be37d05b37ee4ce"),
            new Blueprint("Cue_0023", "e44174a44be472249869b451f553bb0c"),
            new Blueprint("Cue_0046", "a60a1d0078dfc364494c50de8661930c"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.PlayerHasRecruitsOnRoster),
          new()
          {
            new Blueprint("Cue_0016", "79b2d4385e23cc44bbb31bbe4044cb74"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.CheckConditionsHolder),
          new()
          {
            new Blueprint("Answer_0058", "70feca2bda2039f4fa472f0f4d09edde"),
            new Blueprint("Slot_3_3_ItemRestriction", "4f0361cf4f7412d49b0aef6b8061c8a8"),
            new Blueprint("Slot_7_5_ItemRestriction", "b9e743b4c4b467a409a37905af58ce4b"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.MonthFromList),
          new()
          {
            new Blueprint("Answer_0023", "bb30ee6ab838dac4cba66ca2da58d394"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.DayOfTheMonth),
          new()
          {
            new Blueprint("Answer_0023", "bb30ee6ab838dac4cba66ca2da58d394"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.CheckItemCondition),
          new()
          {
            new Blueprint("AreshkagalDungeon_Arena", "67fb6b5c69c149ecb2aed1b38d299fb7"),
            new Blueprint("Cue_0214", "165086c84dfc4c14ca9e9583f7b17adb"),
            new Blueprint("Cue_0221", "36d7a9a7d4e40684ea6ac72668fb8e36"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.HasEnoughMoneyForCustomCompanion),
          new()
          {
            new Blueprint("Answer_0003", "2295c50c6e3d4d93a86a9086aada9833"),
            new Blueprint("Answer_0089", "8639e5fa92c97d24886ae8c90acd38fe"),
            new Blueprint("Answer_3", "40b8e29fb08f4f59bd037e33519002ed"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsRespecAllowed),
          new()
          {
            new Blueprint("Answer_0001", "808ac1acf5a4421790209f192d376e9d"),
            new Blueprint("Answer_0027", "e75acba3688113a40afa7a46f7fd7bb8"),
            new Blueprint("Answer_0095", "deae4190a11f1ca4c9617d9dc2307ba7"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.HasEnoughMoneyForRespec),
          new()
          {
            new Blueprint("Answer_0005", "a92755e3dfa24ad8b2f2f7654071ccbb"),
            new Blueprint("Answer_4", "b8eca38b3d874bcdbf0e0e5f2a1d763c"),
            new Blueprint("MercenaryTrouble6", "0a8297764e3f9bf4ba5757a0edecd019"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.SummonPoolExistsAndEmpty),
          new()
          {
            new Blueprint("Cue_0017", "4565910d19f940688a09c3e50a48f3b2"),
            new Blueprint("Graveyard_HillSkipped", "d36afdd4f689406ebdc2593b066fb129"),
            new Blueprint("XCOM_Triggers", "d10e9d61d16925845be53a113cc7db44"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.RespecIsFree),
          new()
          {
            new Blueprint("Cue_2", "48c4790378964832ae733ff5e26c7e20"),
            new Blueprint("Cue_2", "c8a45cb530054b0d896148e4e02263b9"),
            new Blueprint("Cue_3", "e72dfc57d76a4c29b823349babb68420"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Conditions.KingdomLeaderIs),
          new()
          {
            new Blueprint("Answer_0260", "fb07588e668af2f4b93ea5628ab833bc"),
            new Blueprint("Cue_0263", "082fed3c287c9054593eebc2101e79b2"),
            new Blueprint("Cue_0264", "63845fd8cb8868b4f95bdf5cdc3e73b8"),
          }
        },

        {
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsListContainsItem),
          new()
          {
            new Blueprint("areeluPuzzle_ItemRestriction", "abd21b102fd546a0bd53dff0b566076f"),
            new Blueprint("MaskPuzzleLootCont_3_CloseAction", "2573e02967e95014c93266c845bc9f2e"),
            new Blueprint("Slot_2_1_ItemRestriction", "14081f100ba2a284b9f1d99cfd0c1363"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.MapObjectDestroyed),
          new()
          {
            new Blueprint("Graveyard_BushesInCheck", "7d19a4d9deda414194a450b343eac99f"),
            new Blueprint("Graveyard_BushesOutCheck", "2f61e729c22a4a59a810466e9db43a6e"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.IsUnitMythicExperience),
          new()
          {
            new Blueprint("DLC1_Levelup", "dca1299c933b43dd8078cdf078ee6121"),
            new Blueprint("MythicLevel", "dc66b7adec0e41c2b948b4bc9c31ec99"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UnitLogic.Mechanics.Conditions.ContextConditionDungeonStage),
          new()
          {
            new Blueprint("DLC3_BoonsTutorial", "656933737f3d4ee4b8be54a54df48d3f"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.DungeonIsBoon),
          new()
          {
            new Blueprint("CheckBoonFlags", "87a65a30a6f5424b86fed226dbc2d101"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Assets.Designers.EventConditionActionSystem.Conditions.CampaignCompleted),
          new()
          {
            new Blueprint("DLC1_MythicPowersAfterCompletion", "637667bed8e04ffdbf40de38794b6228"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.UnitIsInFogOfWar),
          new()
          {
            new Blueprint("PeacefullUnitsInCombatState", "dff0fbdbd83672e429df0dc14b0db79e"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.ElementsSystem.IsleStateCondition),
          new()
          {
            new Blueprint("Alushinyrra_MediumCity_AssasinsGuild", "66fac7083737ab0449932caf327667cd"),
            new Blueprint("AlushinyrraLowerCity_BattleblisAvailble", "fa9c548fa28e4b979db3bf6cefa09c32"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.DayOfTheWeek),
          new()
          {
            new Blueprint("EmberQ1_EmberPreachingInPrison", "2d696d7e4ae237947832954d602dbaff"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.EventConditionActionSystem.Conditions.CompanionIsLost),
          new()
          {
            new Blueprint("Sosiel_Q2_KTC", "4ff659434ee301e4d99cad924df322fe"),
          }
        },
      };
  }
}
