using BlueprintCoreGen.CodeGen.Methods;
using System;
using System.Collections.Generic;

namespace BlueprintCoreGen.CodeGen.Overrides.Examples
{
  // Examples generated by TypeUsageAnalyzer
  internal static class ExampleBlueprintScriptableObjects
  {
    public static readonly Dictionary<Type, List<Blueprint>> Examples =
      new()
      {

        {
          typeof(Kingmaker.Blueprints.BlueprintProjectile),
          new()
          {
            new Blueprint("AcidArrow00", "89cd363b66b1df440b5281f7d3ef188d"),
            new Blueprint("Kinetic_EarthBlastLine00", "5d66a6c3cac5124469b2d0474e53ecab"),
            new Blueprint("WindProjectile00_Up", "6648c0c15eda1f14eb80e260f87c55ea"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.BlueprintProjectileTrajectory),
          new()
          {
            new Blueprint("AcidArrow00_Trajectory", "e4e54f0158d01ea4ea1e8f888ac4dc0c"),
            new Blueprint("LightningBolt00_Trajectory", "cf8dfc645f5f6de45982a86de160b865"),
            new Blueprint("WindProjectile00_Trajectory", "9fe2223c200bab9418294130b29b0e08"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Buffs.Blueprints.BlueprintBuff),
          new()
          {
            new Blueprint("1_FirstStage_AcidBuff", "6afe27c9a2d64eb890673ff3649dacb3"),
            new Blueprint("Gorum_Buff", "e3a9786b626d4b50ac58a8b3cbdc00f4"),
            new Blueprint("ZombieDeathEffectSlashingBuff", "912375890d1543ddbce40176d06bb85d"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Area.BlueprintDynamicMapObject),
          new()
          {
            new Blueprint("CorpseInteractionBlueprint", "75588478e5cc80742838c901d41a586d"),
            new Blueprint("RewardObject_LegacyExp_DynamicMapObject", "f0efc1cb480241c890e4e5d4949cad17"),
            new Blueprint("UnusedDynamicMapObject_4", "816627dd533c45e5b8c7a52fc5e75c8c"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAbility),
          new()
          {
            new Blueprint("1_FirstDeathAbility", "4445d9d1c21141c6a0bb24baf373ef78"),
            new Blueprint("HorridWilting", "08323922485f7e246acb3d2276515526"),
            new Blueprint("ZoneOfPredetermination", "756f1d07f9ae29448888ecf016fa40a7"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.BlueprintBrain),
          new()
          {
            new Blueprint("1_Areshkagal_BrainFirst", "c1da4b6948f84bc3b6e87bf3d80be6df"),
            new Blueprint("GibrilethMythicBrain", "da52a999cc764b36936f8572dcaac28d"),
            new Blueprint("ZombieWizardBrain", "015f66fbc3d4dd64197c2ffd4826a214"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Weapons.BlueprintItemWeapon),
          new()
          {
            new Blueprint("AbruptEndItem", "3ba4ce0f30e6cc945ac96b5374649efd"),
            new Blueprint("KukriPlus2", "ce7ef76c973ecfc47ba7515a743c8fd4"),
            new Blueprint("ZealousMightItem", "3ec3c7dde6cdfe4449fd8c1638b4f5a7"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.BlueprintControllableProjectile),
          new()
          {
            new Blueprint("Mythic7lvlLich_BoneLance00_ControllableProjectileBlueprint", "197f5f73c5f02274c9f577f855c20142"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.BlueprintUnit),
          new()
          {
            new Blueprint("!Octavia_Companion_Mage_Test", "f9161aa0b3f519c47acbce01f53ee217"),
            new Blueprint("DLC3_CR0.5_Cultist_FighterMelee", "a04acf0c9afc4afc81121b9216b53887"),
            new Blueprint("Ziforian_normal", "7ef2998dbeb7fda43a47ce842f4d142d"),
          }
        },

        {
          typeof(Kingmaker.Achievements.Blueprints.AchievementData),
          new()
          {
            new Blueprint("00_Platinum", "d40b3502bfdf4d6cbb02c90111eb3a31"),
            new Blueprint("55_NextDoorPlay", "4ed338d976814770a1a4e29d89eb7566"),
            new Blueprint("DLC3_21_Myth_sell", "34b74f93ab2b4c9ea036852bc93d6a03"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAbilityAreaEffect),
          new()
          {
            new Blueprint("AcidFogArea", "f4dc3f53090627945b83f16ebf3146a6"),
            new Blueprint("InciteRageAllArea", "d63dce0f272ba2d4aa13000470398d63"),
            new Blueprint("ZoneOfPredeterminationArea", "1ff4dfed4f7eb504fa0447e93d1bcf64"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.BlueprintFeature),
          new()
          {
            new Blueprint("154654654654", "aa49f649d92747e2a632476a8369b18d"),
            new Blueprint("GreaterFireElementalBurnFeature", "5129567223dcbc248a4143226ba037f4"),
            new Blueprint("ZonKuthonSacredWeaponFeature", "5c73ec301e1e3094ebb031bda43e6481"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Facts.BlueprintUnitFact),
          new()
          {
            new Blueprint("Angel4BladeOfTheSunFact", "dcaacfa8d3a0490ea4b572de750f4d94"),
            new Blueprint("DeflectionArmor3", "6b0b0aa011d26da438a999b35ca97137"),
            new Blueprint("UltimateHitPoints", "45cee177bfb232f42a3c54d3b037dcab"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.BlueprintAbilityResource),
          new()
          {
            new Blueprint("AasimarSpellLikeResource", "a4ea5b9becd98dd47b51c8742aeb70ec"),
            new Blueprint("HermitRevelationReclusesStride10Resource", "7a177b530fef4f8419b3eceddc89f456"),
            new Blueprint("WitchWanderingHexResource", "69a59a4670b17ef4dbccecd4cda6b898"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.ActivatableAbilities.BlueprintActivatableAbility),
          new()
          {
            new Blueprint("AasimarHaloToggleAbility", "248bbb747c273684d9fdf2ed38935def"),
            new Blueprint("KineticBladeBlueFlameBlastAbility", "4005fc2cd91860142ba55a369fbbec23"),
            new Blueprint("WitheringLifePhysicalToggleAbility", "a294368129a7424488a797137ceb8f45"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Mechanics.Properties.BlueprintUnitProperty),
          new()
          {
            new Blueprint("AeonAreaEffectsGazeProperty", "f363c368c37546c3a4793b348963dc28"),
            new Blueprint("PerfectFormConstitutionToStrengthProperty", "d3a9446eed7b458690904831241bac3f"),
            new Blueprint("WitchHexSpellLevelProperty", "75efe8b64a3a4cd09dda28cef156cfb5"),
          }
        },

        {
          typeof(Kingmaker.Armies.TacticalCombat.Brain.BlueprintTacticalCombatBrain),
          new()
          {
            new Blueprint("BaseLeaderBrain", "746ee9d7f1ece2b488919754245fd2e1"),
            new Blueprint("TacticalCombatArcherHatredRangedBrain", "588b9fb885354ffe85c1dda2e8ad629e"),
            new Blueprint("TacticalCombatWarpriestBrain", "a0a2c2320401478696c1953e19b713dc"),
          }
        },

        {
          typeof(Kingmaker.Armies.TacticalCombat.Brain.BlueprintTacticalCombatAiAttack),
          new()
          {
            new Blueprint("TacticalCombatAiAttack", "f6b84975c3d39b24c872005f30df8b40"),
            new Blueprint("TacticalCombatAiAttackImportantExecute", "e0d419d18f2c45f395334db16e06c96e"),
            new Blueprint("TacticalCombatAiSpreadFreeze", "b8bc7b5c5f9d411ea4102a2c4aae0512"),
          }
        },

        {
          typeof(Kingmaker.Armies.TacticalCombat.Brain.BlueprintTacticalCombatAiCastSpell),
          new()
          {
            new Blueprint("CultistLeader_Bane", "41ad996a42081dd4b8c5b9f40c1edc1c"),
            new Blueprint("TacticalCombat_AIAction_MagicMissile", "e498e407f19d42c7986154cccc9b14b0"),
            new Blueprint("TacticalCombatAiCastSpell", "d0080d8dc74981240bce6992499ef026"),
          }
        },

        {
          typeof(Kingmaker.Armies.TacticalCombat.Brain.Considerations.TacticalCombatTagConsideration),
          new()
          {
            new Blueprint("TacticalCombat_Caster", "c72aa4fb567f1d549ba42ca77ef0d90b"),
            new Blueprint("TacticalConsideration_GrandTierConsideration", "34bfecc344ec4ea396c0be190a240c4c"),
            new Blueprint("TacticalConsideration_XenophobicConsideration", "9656d523369f4224b4ed147992b9f7a5"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.StatConsideration),
          new()
          {
            new Blueprint("IntGreaterThan2", "9fe91dc89e64fe3488786d98dbe1814d"),
            new Blueprint("TacticalCombat_HitPointsConsideration_300", "796c108b203f44c2b5f5f45ba08181a0"),
            new Blueprint("WillSavingThrowLess5", "b546587c77f07b042bc92325297a16b9"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.DistanceConsideration),
          new()
          {
            new Blueprint("BlightedTreant_Consideration_TrampleRange", "a62ac14c12db2774f866ef6463e35a27"),
            new Blueprint("Omox_Consideration_LiquidLeapRange", "0e904cee965973d43a6c20716827eddb"),
            new Blueprint("Vrock_Consideration_GreaterTeleport", "65b6b528aa549b345963bb0402ccf802"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.DistanceRangeConsideration),
          new()
          {
            new Blueprint("DLC3_DistanceRangeConsideration", "57a2c110baa0421d935178a1c85ffdd8"),
            new Blueprint("DLC3_DistanceRangeConsideration45feet", "e0217b9a7933471abd6ff0f68ad05a05"),
            new Blueprint("TacticalConsideration_BrimorakBreathRangeConsideration", "3e3234a1b3599034c80d14765aec24ea"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Armies.TacticalCombat.Brain.Considerations.ArmyHealthConsideration),
          new()
          {
            new Blueprint("TacticalConsideration_ExecuteHealth", "bdb3b030d85246d7bc845aa7ebc3f629"),
            new Blueprint("TacticalConsideration_HalfHealth", "c43dbb77d5e98ca49a5bd4f9f7a3fabf"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Armies.TacticalCombat.Brain.Considerations.TacticalCombatCanAttackThisTurnConsideration),
          new()
          {
            new Blueprint("TacticalConsideration_InRange", "1d0119dadcf36724cbd6ba0c27b16519"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.UnitsAroundConsideration),
          new()
          {
            new Blueprint("AoE_AvoidFriends", "8e6f34026b34c3d4ba831bb94548904a"),
            new Blueprint("AoE_ChooseMoreFriends", "5ffa06bb750ad294cbaf4ab3dec09fb5"),
            new Blueprint("TacticalConsideration_TargetsAroundConsideration", "9ae6bee103a0d624995f53ccdbe52b92"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Blueprints.BlueprintKingdomBuff),
          new()
          {
            new Blueprint("Aeon2FireElementalsCooldown", "f2d98d5b49e34d1998b9f4d21a935609"),
            new Blueprint("FlagDiplomacy8MercsIncrease", "275b1de5d47b4d6ca39b40bf9f37c4af"),
            new Blueprint("ZiforianSupport_buff", "3735e202e116466898a0e7fd54607d22"),
          }
        },

        {
          typeof(Kingmaker.Armies.Blueprints.BlueprintLeaderSkill),
          new()
          {
            new Blueprint("Aeon1SpeedStats", "62fcd9d0cdb54b59930c9b9bbb30a870"),
            new Blueprint("Leadership6IncreaseMorale", "796c4868365243cface2d36f997135a9"),
            new Blueprint("ZealousLearnerRank2", "665cb61bfcba4a2697f95b21f4249220"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.BlueprintFaction),
          new()
          {
            new Blueprint("AngelTeam", "ff7b854fc400a64419f4f45273eed7ee"),
            new Blueprint("HellsDecreeAbilityTargetedRageFaction", "cd8d42c97e3dc134193cb8d5d4d35a73"),
            new Blueprint("WildAnimals", "b1525b4b33efe0241b4cbf28486cd2cc"),
          }
        },

        {
          typeof(Kingmaker.Armies.BlueprintArmyLeader),
          new()
          {
            new Blueprint("ArmyLeader_GeneralTest", "efcdfea53c72a2c47b3193e64e7cfea5"),
            new Blueprint("Warlord_SwarmOmnipresent", "f52b9cd3bd804018af28654753c7975c"),
            new Blueprint("WarlordLeaderWarrior4", "c2f459f7de4a463bb9673030bd8443b8"),
          }
        },

        {
          typeof(Kingmaker.Armies.BlueprintLeaderSkillsList),
          new()
          {
            new Blueprint("AbilityRangerChoice1", "f5bbda67aad14bcfadce4ac3e439a3e1"),
            new Blueprint("FeatWarriorCommonChoice1", "b3a79cdcdb3246edb754ecbc8894c63b"),
            new Blueprint("RitualWarriorChoice5", "2dd9d5af884546d48ee8523f6a675f8c"),
          }
        },

        {
          typeof(Kingmaker.Armies.BlueprintLeaderProgression),
          new()
          {
            new Blueprint("WarlordMageProgression", "33b8bf9e76d698d41a23a14720917ecb"),
            new Blueprint("WarlordRangerProgression", "51b612805a0a4b709c54881c1c575c28"),
            new Blueprint("WarlordWarriorProgression", "e644dc6971424504aaad9ca02705bad2"),
          }
        },

        {
          typeof(Kingmaker.Armies.TacticalCombat.Blueprints.BlueprintTacticalCombatObstaclesMap),
          new()
          {
            new Blueprint("NoObstaclesMap", "9ae49d439d369d34ea3bd5729a155cd7"),
            new Blueprint("ObstaclesMapDesert8", "96fa08b270c24707bd47e9c96530f29c"),
            new Blueprint("ObstaclesMapWinter9", "c7ffd966abe94598873afa5cc9273730"),
          }
        },

        {
          typeof(Kingmaker.Armies.Blueprints.BlueprintArmyPreset),
          new()
          {
            new Blueprint("AeonAirElementals", "fb51fa16d02741e88de3ea37ae6bd682"),
            new Blueprint("Encounter34GhoulsNabasuFavorSource", "47031664c9a9168469f9f52629b17564"),
            new Blueprint("Trickster5ThugPaladin", "626ec936830a4976be6c28d1acfeab10"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.Selection.BlueprintFeatureSelection),
          new()
          {
            new Blueprint("AasimarHeritageSelection", "67aabcbce8f8ae643a9d08a6ca67cabd"),
            new Blueprint("MagusFeatSelection", "66befe7b24c42dd458952e3c47c93563"),
            new Blueprint("ZenArcherWayOfTheBowSelection", "53420038fdc76944695bf927f7bcd51c"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.BlueprintAiCastSpell),
          new()
          {
            new Blueprint("1_Areshkagal_First_DemonTeleport_AiAction", "c5c4211d6ea24a0f94c5fc6bcc36b584"),
            new Blueprint("HeroismGreaterAiAction", "2cd769aff48fdc34c8a19cf607292706"),
            new Blueprint("ZombieFearAIAction", "7cff1a10bbe680f4b835017c4671704a"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.BlueprintAiAttack),
          new()
          {
            new Blueprint("AngryIncubusRanger_AiAction_Attack", "e57e9f9754674706b0fb3ad8617cf798"),
            new Blueprint("HellknightAttackAiAction", "3e945a165553406394d7f05b171f7c22"),
            new Blueprint("Zanedra_SpellCombatAIAction", "affa28e7b809b2a4cab57e44161050b4"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.BlueprintAiFollow),
          new()
          {
            new Blueprint("AirElementalFollowEnemyAiAction", "565c49da5aa97274a9e93bb7c2a6868e"),
            new Blueprint("DLC3_Move", "165389d6bdbd4cd4a0d9316f4f106639"),
            new Blueprint("VescavorFollowEnemyAiAction", "26201d239d3a92c4294db93b4f098316"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.BlueprintAiTouch),
          new()
          {
            new Blueprint("Darek_AiAction_TouchSpell", "75a1084de86a46798539f2bdb440219c"),
            new Blueprint("ManualTouchSpellAiAction", "f774019d0755a514886874e0e9c78588"),
            new Blueprint("TouchSpellAiAction", "abbd64175ed53f3429c5cf988e255914"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.BlueprintAiSwitchWeapon),
          new()
          {
            new Blueprint("SwitchToMeleeAiAcition", "c3a92873b2591de4bb9930bee393d610"),
            new Blueprint("SwitchToRangedAiAcition", "0b4f3b688f91a9b4882fbe2af8248177"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.BuffsAroundConsideration),
          new()
          {
            new Blueprint("Abrogail_Consideration_GuardsAround", "5930219f49c54ba2b4a827d9a3d8c247"),
            new Blueprint("AlliesNoBuff_ResistFire", "647d5f83acd33414a9eef9281b032e56"),
            new Blueprint("Valmallos_Consideration_BuffsAroundSummoned", "a90d35d8af7b4c09bedbc95d7e8b688b"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.TargetClassConsideration),
          new()
          {
            new Blueprint("AnimalConsideration", "ae38d3f18cc6265478f2df0917f6880c"),
            new Blueprint("NotAnimalCompanionConsideration", "011f7646eb27b184fa4840d2ba143118"),
            new Blueprint("Shrine_Consideration_Healers", "930a163fcd328fa4993237ef59c4bd44"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.TargetMainCharacter),
          new()
          {
            new Blueprint("AssassinationConsideration", "83bf9d72c91fe4041a4c6e523919f1d3"),
            new Blueprint("AvoidMainCharacterConsideration", "f770798dd7cb48b7aa29f7f688d98828"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.ComplexConsideration),
          new()
          {
            new Blueprint("AttackTargetsPriority", "7a2b25dcc09cd244db261ce0a70cca84"),
            new Blueprint("HelpTargetsPriority", "36010f75540818a48879f220efd2fa6f"),
            new Blueprint("SwiftAction", "f335c9d35bc608648af2ca45ef2e096c"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.CanUseSpellCombatConsideration),
          new()
          {
            new Blueprint("CanUseSpellCombatConsideration", "cf686ad8da41d4444b2bdc738e8474a7"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.FactConsideration),
          new()
          {
            new Blueprint("AlushinyrraCasterMIniboss_Consideration_AntiArcher", "da1952105199459db40e9d083948c0c8"),
            new Blueprint("NoCaster", "22d91eb7dceec4249810c476ab7d5a56"),
            new Blueprint("UnicornConcideration", "6c8c34d57234f0d488ef0c2ea21ce928"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.RandomConsideration),
          new()
          {
            new Blueprint("ChaoticBehaviour", "aad346ba597e8aa45bb4b589d9f9d0ea"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.AlignmentConsideration),
          new()
          {
            new Blueprint("BlackFireAdeptVampire_GoodConsideration", "517f96bb6ea38c1438f97503de53a1a4"),
            new Blueprint("EvilConsideration", "edf863c12297a514ea834bd4cc22fe72"),
            new Blueprint("Mephisto_Consideration_NoEvilAlignment", "cb1ee9f67dc6454bbc009896d53c3dc8"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.UnitConditionConsideration),
          new()
          {
            new Blueprint("DisabledMovementCondition", "dcaa2ecdb79525642aadbd9907bb3841"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.HasAutoCastConsideraion),
          new()
          {
            new Blueprint("DisableWhenAutoCast", "1e48424e2848cef4c98ee79ace210c79"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.BuffConsideration),
          new()
          {
            new Blueprint("5_CritHitBuffTeleportConsideration", "fa020623ab46476a85a1ee938f08f0cc"),
            new Blueprint("NoBuffFalseLifeGreater", "be623d7b7be75434db340052806d8374"),
            new Blueprint("WillOWispInvisibilityConsideration", "ae50f85d7c3051b49b44de1e21424f1b"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.LineOfSightConsideration),
          new()
          {
            new Blueprint("HasLineOfSightConsideration", "2b6fd30bf8a522f43aafd9192c89d5d0"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.HasManualTargetConsideration),
          new()
          {
            new Blueprint("HasManualTarget", "eaba7974353669c4c8346c83241f8ee0"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.HealthConsideration),
          new()
          {
            new Blueprint("DLC3_ShipGolemPossesionConsiderationAroundHealthConsideration", "b51b3fb97344463fb0f1f9f63f2dcbd6"),
            new Blueprint("InjuryMedium", "e4c1bad4edae22d42995ca0da3bb6e23"),
            new Blueprint("Svendack_Consideration_Health", "e6e5a902df66d6e4a8471fdc1cfc8e4e"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.ArmorTypeConsideration),
          new()
          {
            new Blueprint("HeavyArmorConsideration", "c376d918c01838b48befcb711cc528ff"),
            new Blueprint("LightArmorConsideration", "2ba801c8a6f585749b7fd636e843e6f0"),
            new Blueprint("OnlyLightArmorConsideration", "b4248462c4f3f3a4ca627d8cdf52c973"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.HitThisRoundConsideration),
          new()
          {
            new Blueprint("HitThisRoundConsideration", "c59156891517d2c448950ce3df12a0bc"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.HealthAroundConsideration),
          new()
          {
            new Blueprint("BanditInjuryAround", "35197d884b2e0c041a615bfe28dcbbc7"),
            new Blueprint("InjuryAround", "2a2cfff1d585f3142aadaafe0c1a74e6"),
            new Blueprint("InjuryAroundMedium", "8dbc5d7304fd6be4fa34a226aeedfef8"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.InRangeConsideration),
          new()
          {
            new Blueprint("InRangeConsideration", "804d2cf0fb1815948b04ec697cbfdbf4"),
            new Blueprint("StandStill", "da2c75bc93165b749b18654b21759ea3"),
            new Blueprint("StandStillInAOO", "f083257df5834aa459be020f9b291f21"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.ThreatedByConsideration),
          new()
          {
            new Blueprint("IsThreatedConsideration", "ec8e11fa0ccbf274ba557f3c26443bb5"),
            new Blueprint("NoThreateningUnitsConsideration", "ce325ec9fa497f841a74d79b2002b04b"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.LastTargetConsideration),
          new()
          {
            new Blueprint("KeepTarget", "24c23afd50cba6149a2452f8ea10c548"),
            new Blueprint("KeepTarget_Always", "a2633c72b7133d145ae8a8c3bc36a97d"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.ManualTargetConsideration),
          new()
          {
            new Blueprint("ManualOnly", "363bee4c5b6aeb140bf12762dba596e1"),
            new Blueprint("ManualPriority", "fda4a8b5a8daa1f43bd192397a81adda"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.NotImpatientConsideration),
          new()
          {
            new Blueprint("NotImpatient", "16d45be25a7cb894d958772bc8f74f6d"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.ActiveCommandConsideration),
          new()
          {
            new Blueprint("NotMoving", "b0939505096379643a4aecd997043623"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.CommandCooldownConsideration),
          new()
          {
            new Blueprint("StandardActionOffCooldown", "a82d061edd18ce748a1a7f97e7e6d9d2"),
            new Blueprint("SwiftActionOffCooldown", "c2b7d2f9a5cb8d04d9e1aa4bf3d3c598"),
            new Blueprint("SwiftActionOnCooldown", "09452fb4457a9974dafb9e9f15cb68d1"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.BuffNotFromCasterConsideration),
          new()
          {
            new Blueprint("SwarmBuffConsideration", "e80fcfb258f44755a59ebaea236828a1"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.SwarmTargetsConsideration),
          new()
          {
            new Blueprint("SwarmTargetsConsideration", "6ede4d9d3350e89489a260fae2bcb2c4"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.TargetSelfConsideration),
          new()
          {
            new Blueprint("TargetOther", "f4be6fc6f46b61044a44715f99f1918d"),
            new Blueprint("Wintersun_SpectreDruid_NotSelfConsideration", "250a50e06ed7fab4dbd3f93e51fb122d"),
            new Blueprint("Xantir_NotSelfConsideration", "ecf7ab4d44a08834daf76b47b10a7ac0"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.LifeStateConsideration),
          new()
          {
            new Blueprint("UnconsciousBonus", "07e8c3596fac6574f8fa96a47874250f"),
            new Blueprint("UnconsciousPenalty", "bf033da33480da84f8265f5f8bcdd467"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.UnitsThreateningConsideration),
          new()
          {
            new Blueprint("BrassGolemBreathConsideration", "337506b9ab983b14487443bea0dbb778"),
            new Blueprint("IronGolemBreathConsideration", "57588fc9120c79343b64b665ae1f87fc"),
            new Blueprint("UnitsEnoughForWhirlwind", "dce40e2004109804baadb7c9f3e787ef"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.BlueprintItem),
          new()
          {
            new Blueprint("AbadarPriestLetter_azata_bad", "69fff4acfbd641cea12e1ed38db21029"),
            new Blueprint("Eggs", "759a3d9856b4d5d4fa6123150bf46eda"),
            new Blueprint("ZoeyPendantTeleport", "9a90929e2db1be448b495509170a4251"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Loot.BlueprintUnitLoot),
          new()
          {
            new Blueprint("BanditConspiratorVendorTable", "94c0dbce9f68ca64eae711aefb2b1a54"),
            new Blueprint("FullVariant3CR5", "fb39c3edb2dfd7e41b8adf8435bdbb4e"),
            new Blueprint("WyvernMeatLoot", "abe034c3a49a1854496fa6fe1f439114"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.BlueprintRace),
          new()
          {
            new Blueprint("AasimarRace", "b7f02ba92b363064fb873963bec275ee"),
            new Blueprint("HalfElfRace", "b3646842ffbd01643ab4dac7479b20b0"),
            new Blueprint("ZombiesRace", "b9668860eed943eca2419fd8c371f481"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.Selection.BlueprintParametrizedFeature),
          new()
          {
            new Blueprint("AbilityFocus", "b689c0b78297dda40a6ae2ff3b8adb5c"),
            new Blueprint("LoremasterWizardSecretSorcerer", "a26834acd0f797c4e948660f4eb6ccd9"),
            new Blueprint("WeaponSpecializationMythicFeat", "d84ac5b1931bc504a98bfefaa419e34f"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.BlueprintSummonPool),
          new()
          {
            new Blueprint("1stFight", "1eb2a98d5e95e7f49a78c961cdc68738"),
            new Blueprint("HigherToMediumGuards", "945717614c712ab4eac4ff894a8eb4e8"),
            new Blueprint("ZombieWave3", "d45ec2e51b0b57e40bb573f6e2d35db2"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.BlueprintSharedVendorTable),
          new()
          {
            new Blueprint("Aminas_Chapter5VendorTable", "8b2dae3f8da96f640995594f6bcf7a29"),
            new Blueprint("DLC3_VendorFirstTable", "45f027c06962df249b8c014a4b4e95e3"),
            new Blueprint("Weapon_DefendersHeartVendorTable", "5f17d3b47752fb94abe8c98534af8920"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.BlueprintCharacterClass),
          new()
          {
            new Blueprint("AberrationClass", "e40e01860956b8b4d80059d4437996f5"),
            new Blueprint("LegendClass", "3d420403f3e7340499931324640efe96"),
            new Blueprint("WizardClass", "ba34257984f4c41408ce1dc2004e342e"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.BlueprintProgression),
          new()
          {
            new Blueprint("AberrationProgression", "692a51e61be994e4499e36b88637b45f"),
            new Blueprint("KineticKnightElementalFocusFire", "d4a2a75d01d1e77489ff692636a538bf"),
            new Blueprint("WreckerProgression", "c3ecafa8e5c5c2942af7cac0157cf8be"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.Spells.BlueprintSpellbook),
          new()
          {
            new Blueprint("AccursedWitchSpellbook", "b897fe0947e4b804082b1a687c21e6e2"),
            new Blueprint("LichSkeletalInquisitorMinorSpellbook", "d71cb34f8a66a2c479ba8289a1683112"),
            new Blueprint("WizardSpellbook", "5a38c9ac8607890409fcb8f6342da6f4"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.Spells.BlueprintSpellsTable),
          new()
          {
            new Blueprint("AeonSpellKnownTable", "7f2e1369e05a9ab4982fa1f05c8f95bd"),
            new Blueprint("EldritchFontSpellSlots", "67682cefce9401e469bee46dac597051"),
            new Blueprint("WizardSpellLevels", "78bb94ed2e75122428232950bb09e97b"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.Spells.BlueprintSpellList),
          new()
          {
            new Blueprint("AeonSpellList", "24b0c796f723a144e9891b6c4794c595"),
            new Blueprint("LuckDomainSpellList", "9e756552e9b05ce459feac658dd2d8fb"),
            new Blueprint("WizardTransmutationSpellList", "becbcfeca9624b6469319209c2a6b7f1"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.BlueprintArchetype),
          new()
          {
            new Blueprint("AccursedWitchArchetype", "c5f6e53e71059fb4d802ce81a277a12d"),
            new Blueprint("IncenseSynthesizerArchetype", "6faf49766d8156c419d08f556a40374f"),
            new Blueprint("ZenArcherArchetype", "2b1a58a7917084f49b097e86271df21c"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.BlueprintFeatureReplaceSpellbook),
          new()
          {
            new Blueprint("ArcaneTricksterArcanist", "7cab956d45dc51c4ea9e71bba366a250"),
            new Blueprint("HellknightSigniferSageSorcerer", "9ff63ae68eb6f8f4296f63dced80da50"),
            new Blueprint("WinterWitchWitchLeyLineGuardian", "56adf819599827f4695395924a060996"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.BlueprintStatProgression),
          new()
          {
            new Blueprint("ArmyXPTable", "72cc67d1699657147aa5c9af03098b66"),
            new Blueprint("LegendXPTable", "11c77f6853ac46aa8e2d004d6dca5f9f"),
            new Blueprint("ZeroProgression", "059c61483910c77408d0473b11d1b922"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.DialogSystem.Blueprints.BlueprintDialogExperienceModifierTable),
          new()
          {
            new Blueprint("DialogXPTable", "6e37dcecb2f9450dab1d6ca4e8667bcb"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Ecnchantments.BlueprintWeaponEnchantment),
          new()
          {
            new Blueprint("AbruptEndEnchantment", "66f1ac1f205e99f4e83c9b3aa8f0b0b1"),
            new Blueprint("InsomniacBladeEnchantment", "8cae995f6c1ce734ea0d4d7c14dc959c"),
            new Blueprint("ZealousMightItemEnchantment", "819877d9ef15d9d45ac876ca21030279"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Ecnchantments.BlueprintArmorEnchantment),
          new()
          {
            new Blueprint("2DCagainstNecroticPlus2Enchant", "0bc09adac665a7647b39ca76b897ddd5"),
            new Blueprint("HagsDemiseEnchantment", "a7efe327fc3347e594ff20bbdf199388"),
            new Blueprint("ZachariusFallenWandEnchantment", "7391002fb801497695a8556e2b4fcc72"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Designers.Mechanics.Collections.BuffCollection),
          new()
          {
            new Blueprint("NewBuffCollection", "1727161aaf654b1cbc368ca6d8583127"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.BlueprintCharacterClassGroup),
          new()
          {
            new Blueprint("Alchemist", "acb8d8d897926004bbf6513a8f4642e5"),
            new Blueprint("Kineticist", "2b07b1c577b9c1c45a03899292ac08af"),
            new Blueprint("Performers", "9267ebac8dc2ba64faf936b81418512c"),
          }
        },

        {
          typeof(Kingmaker.Craft.BlueprintIngredient),
          new()
          {
            new Blueprint("AlchemistsKit1Item", "d604d7e1d190bd44c90241c028fa7313"),
            new Blueprint("MandrakeRootItem", "20dddd5a81cd237429b080548fb59651"),
            new Blueprint("Wood", "5e32d30498e74bd4dad91d14a4ceaf16"),
          }
        },

        {
          typeof(Kingmaker.Crusade.GlobalMagic.BlueprintGlobalMagicSpell),
          new()
          {
            new Blueprint("GlobalSpellActOfIntimidation", "f7874750f5c94bdea2b84b8ea376af6f"),
            new Blueprint("GlobalSpellDragonPowerOfGold", "bfa2e556478ef5b4fb7cd156ad7ded52"),
            new Blueprint("New BlueprintGlobalMagicSpell", "574ba5c65f905ea4db93d1b6540fef39"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.Root.ConsoleRoot),
          new()
          {
            new Blueprint("ConsoleRoot", "d9ba3d03221949347bb0c5bd57912f24"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.Console.GamePadTexts),
          new()
          {
            new Blueprint("GamePadTexts", "87102f063b7b6a34f8c5fd6a64df05f7"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Credits.BlueprintCreditsGroup),
          new()
          {
            new Blueprint("EndGame", "eb99ab2061f5d984794b69d460dbbf19"),
            new Blueprint("Outsource", "0ff8fd304d5d24242bb2c77d733fa972"),
            new Blueprint("Test", "09928007c0088454e82ea5e9b6521641"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Credits.BlueprintCreditsRoles),
          new()
          {
            new Blueprint("GEMCapitalRoles", "045e3ca3bc8941a8bcb3c6d700b6de64"),
            new Blueprint("PaizoRoles", "07cff962f3fe7814fb2b8da265aaa6e5"),
            new Blueprint("SpecialThanksSectionRoles", "745a3b2209732834091e376fb307c24e"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.Credits.BlueprintCreditsTeams),
          new()
          {
            new Blueprint("PrimeMatterTeams", "8784cf0613102554e9e415bdc70bb421"),
            new Blueprint("Teams", "3164ae5088a43d14b8b5dada87d083f1"),
          }
        },

        {
          typeof(Kingmaker.DLC.BlueprintDlc),
          new()
          {
            new Blueprint("Dlc1", "8576a633c8fe4ce78530b55c1f0d14e5"),
            new Blueprint("DlcPreorder", "cce1376687d1452c9f451b0d921bcd4e"),
            new Blueprint("FreeDlc4", "a9262dad08654d3dbad64476978c0f95"),
          }
        },

        {
          typeof(Kingmaker.DLC.BlueprintDlcReward),
          new()
          {
            new Blueprint("DlcCommanderPackReward", "52e2a91ac53442a594a413007c302d83"),
            new Blueprint("FreeDlc1Reward", "60d87338684842c0bae702ea6592d800"),
            new Blueprint("FreeDlc4Reward", "89e5119ac73f4e32a0906b66482539cf"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Root.BlueprintCampaign),
          new()
          {
            new Blueprint("Dlc1Campaign", "d79943b9b59b446ea5bfc14fa4005b26"),
            new Blueprint("Dlc3Campaign", "e1bde745d6ad47c0bc9fb8e479b29153"),
            new Blueprint("MainCampaign", "fd2e11ebb8a14d6599450fc27f03486a"),
          }
        },

        {
          typeof(Kingmaker.DLC.BlueprintDlcRewardCampaign),
          new()
          {
            new Blueprint("Dlc1RewardCampaign", "313fb87e4c0143bd84b3fc997c3c2266"),
            new Blueprint("Dlc2RewardCampaign", "3380030f72954976a775c2e9a1e9ae07"),
            new Blueprint("Dlc3RewardCampaign", "04b3bf450b1e44438854f25ba1290a98"),
          }
        },

        {
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonArmy),
          new()
          {
            new Blueprint("DungeonArmy_Abberations_Tier1_2(1Room)", "284fade5f6564b63a9d926089bd0e477"),
            new Blueprint("DungeonArmy_Golems_Tier2-3(1Room)", "828353f6612949f4b61ed4f7280c03aa"),
            new Blueprint("RE_DungeonArmy_Undead", "1a60b252e25b4bb4ae2d7b9a9b5c6527"),
          }
        },

        {
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonBoon),
          new()
          {
            new Blueprint("DungeonBoon_Acid", "30d5a9af67c844eaba0a9eccd0e10c39"),
            new Blueprint("DungeonBoon_Gnome", "3c86efed41f7426292148ae079d881a6"),
            new Blueprint("DungeonBoon_UnarmedStrikes", "5c7a5a0220e84b3fa5d78d427d10bf6b"),
          }
        },

        {
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonIsland),
          new()
          {
            new Blueprint("Alushinyrra_whorehouse_1", "5d9d98214ef54228b7b8b1f6edd35f56"),
            new Blueprint("Goddam_city_4", "63b2d520384e4926831cd439b8d9f88f"),
            new Blueprint("Toxic_prison5", "9cb00299d84b469ba0d1a1d76d6c4ae7"),
          }
        },

        {
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonMap),
          new()
          {
            new Blueprint("CampaignMap1", "1ff8f4d47e5f4ef8a5f6c1d3e64d8517"),
            new Blueprint("DungeonMap08", "49325cfb957341978aad8e46f5c9b24f"),
            new Blueprint("DungeonMap3", "501d10104e4d40cfb4f25bfd424b3357"),
          }
        },

        {
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonDifficultyCurve),
          new()
          {
            new Blueprint("DungeonDifficultyCurveEasy", "0fc74ba15c184243a1f8c8f1275b8897"),
            new Blueprint("DungeonDifficultyCurveHard", "bfd32e7156b14d4fb8cda8b28cf706e6"),
            new Blueprint("DungeonDifficultyCurveNormal", "b66706d82b8d4154a259d0fac8d40185"),
          }
        },

        {
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonExpedition),
          new()
          {
            new Blueprint("Expedition1", "431d71f2f8ba4b848d9d308fc44262a9"),
            new Blueprint("Tier2_exp_2", "10a66fdcbedd4e0189cf7efbf076f22c"),
            new Blueprint("Tier4_exp_1", "300c9b0da271466292b8b8888cf4792a"),
          }
        },

        {
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonLoot),
          new()
          {
            new Blueprint("DungeonLoot_VendorRare_Grade1", "ce33d49bbdb546579c2f43fd67d3f5bc"),
            new Blueprint("DungeonLootCookingRecipes", "8a50117aa43d454cbd3ca1ac63e2646f"),
            new Blueprint("DungeonLootWands", "b097f1875abe4004bd6b04bdec279590"),
          }
        },

        {
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonLootBudget),
          new()
          {
            new Blueprint("DungeonLootBudgetCookingRecipes", "ce6647b74e9748c1a73a1a83554b1ac8"),
            new Blueprint("DungeonLootBudgetRare", "e8780c70cf944807b72e4add642e89df"),
            new Blueprint("DungeonLootBudgetWands", "c2c67a4c6d264cd8a3b48f4553681df5"),
          }
        },

        {
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonModificator),
          new()
          {
            new Blueprint("DungeonModificatorArcane", "4328c8b0356b4e21b13400fbf14412a2"),
            new Blueprint("DungeonModificatorGigantic", "bbf7bbb3544942018b949e5b2a5814cf"),
            new Blueprint("DungeonModificatorWildMagic", "9106be5b6d5d4423bbd538be3dfe6464"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonIslandRewardGold),
          new()
          {
            new Blueprint("RewardGold", "38765f74b739430f905b26e14f029113"),
          }
        },

        {
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonIslandRewardLoot),
          new()
          {
            new Blueprint("RewardLoot_BesmaraBoss", "bc8bf25e3038475e9a2cc9cfddfc1ee6"),
            new Blueprint("RewardLoot_ConsumablePotion_Tier2", "31e85f3a88834eb2a5d408d7dee0f591"),
            new Blueprint("RewardLoot_UnqiueRanomItem", "5f64801c22e34752a7854f03b20e2494"),
          }
        },

        {
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonIslandRewardObject),
          new()
          {
            new Blueprint("RewardObject_CorruptionCleanse", "3dbf788309074705b6f01169dc3c5e17"),
            new Blueprint("RewardObject_PermanentBonusHitPointsBuff_Tier1only", "4f1255167ca840e087e038a2202364af"),
            new Blueprint("RewardObject_RandomFeat", "1f14ad28076b41af928b0a47b167b4b1"),
          }
        },

        {
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonIslandRewardUnit),
          new()
          {
            new Blueprint("RewardTrader_Mercenary", "68fe5bbe916741af97b12a2a55026660"),
            new Blueprint("RewardTrader_Tier1", "eafdfd0604324a439b92b19e99d8bb51"),
            new Blueprint("RewardTrader_Tier3", "b92e487220524c0f945a36436994d2f8"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.BlueprintUnitTemplate),
          new()
          {
            new Blueprint("Branded", "b3fb486ae387c6b4ab8bc52afa6d4131"),
            new Blueprint("DungeonTemplateAdvanced_X4", "b37744503a5647e6a816090f308960f6"),
            new Blueprint("Template healer", "21294f60731f81f479d83b46e7a7df57"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonTheme),
          new()
          {
            new Blueprint("DungeonThemeCold", "08c1a8adc7484ecf87d137b7d3988aab"),
            new Blueprint("DungeonThemeHot", "e67f751590404ba195c0931a4e8712f8"),
          }
        },

        {
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonTier),
          new()
          {
            new Blueprint("DungeonTier1", "d68be5d8f98948948733a36430c80583"),
            new Blueprint("DungeonTier3", "d56fca8053974a30bf53a8b4004add71"),
            new Blueprint("DungeonTier4", "503d0d4a270c435cbd3cc59f828c447a"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonTrapSpellList),
          new()
          {
            new Blueprint("TrapSpellsDefault", "2b699ae45b7c4d04b3c2a99e09e25ccd"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Encyclopedia.BlueprintEncyclopediaPage),
          new()
          {
            new Blueprint("Ability_Scores", "1eb3fcb7d15fdac449d731a9d16e2e4e"),
            new Blueprint("Race", "e48d0ce09b907a74bb3cc399f38840d7"),
            new Blueprint("XP", "045b77a2c3f7da54284cb7cb0f07bec3"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Encyclopedia.BlueprintEncyclopediaChapter),
          new()
          {
            new Blueprint("Basics", "93a70d1e4968f0145a3fb24b21d71aff"),
            new Blueprint("Equipment", "144b264b2bfe4952a40a0167c42b3cc5"),
            new Blueprint("Tutorial_Crusade", "e3fb9d6db74c4516aa054ffd57895199"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Equipment.BlueprintItemEquipmentNeck),
          new()
          {
            new Blueprint("AmuletOfAgileFists", "afd04948b8f211c448f1cc4bd9a67e3e"),
            new Blueprint("CitrineNecklace", "426068b72e8055b45a6b8dcfc92c637c"),
            new Blueprint("XavornsCrossItem", "4537e2beb46b28a47bde3e3e1ac95255"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Ecnchantments.BlueprintEquipmentEnchantment),
          new()
          {
            new Blueprint("AbyssWalkersEnchantment", "502459ea2f9390745864dbd27ef6677a"),
            new Blueprint("HeadbandOfRigorousTrainingEnchantment", "299f71ea466049d47859699f41c1cc46"),
            new Blueprint("ZeorisDaggerRing_GoverningEnchantment", "2a4e61dcd2b74da3b742e1e67837b825"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Equipment.BlueprintItemEquipmentRing),
          new()
          {
            new Blueprint("AcerbicRingItem", "1f34a6b309907a44681c689709976bff"),
            new Blueprint("RingOfEnhancedSummonsItem", "c4e6665dbb126624991d78072ff919aa"),
            new Blueprint("ZeriexRing", "0f1307e138be01d4ba8bdeb489b98c4a"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Armors.BlueprintItemArmor),
          new()
          {
            new Blueprint("AdamantineBanded", "ed04d2a914a93e046aadee8cc3109f65"),
            new Blueprint("HaramakiStandartPlus5", "8a8963d7c3936e041884189d40eb61ca"),
            new Blueprint("WyrmwallArmorItem", "2b0ef21fbc688a74fa20540f93a01aff"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Equipment.BlueprintItemEquipmentShirt),
          new()
          {
            new Blueprint("AlchemistsClothItem", "004e05369fd13e2428bf7eb84bcd38ec"),
            new Blueprint("Robe2ST2DC_CorrectItem", "a5160a52ad404bd6a3a3eef8f1a455f3"),
            new Blueprint("WanderingConmanItem", "fdc89dbe3502c7843ac5685099aac211"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Armors.BlueprintArmorType),
          new()
          {
            new Blueprint("BandedType", "da1b160cd13f16a429499b96636f6ed9"),
            new Blueprint("HalfplateType", "a59bf41f441456a4e8b04b09cb889af8"),
            new Blueprint("StuddedType", "aae2cb63162d6334b9a9150398124d46"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Equipment.BlueprintItemEquipmentBelt),
          new()
          {
            new Blueprint("AssailantsBeltItem", "8d48d164b7a729b459db96ab7d5cf55a"),
            new Blueprint("BeltOfStrengthDexterity4", "519cc630ba3402543af4267b4f75548a"),
            new Blueprint("UnceasingSlaughterItem", "cd015f36cdccb134e86a0b4daa0283e8"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Equipment.BlueprintItemEquipmentFeet),
          new()
          {
            new Blueprint("AbyssWalkersItem", "9d93b46898e710544bf125ba7b227cee"),
            new Blueprint("BootsOfTheLightStepItem", "815cc85ce13ab64428253aea3b6708a8"),
            new Blueprint("SureFootingItem", "2e367ed3db88c714cb35612a7d82f713"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Equipment.BlueprintItemEquipmentWrist),
          new()
          {
            new Blueprint("ArmExtendersItem", "7e4432d76a824571b3965c6bda73f763"),
            new Blueprint("BracersOfOverwhelmingVigorItem", "3ef2c9ea26cd01f419ae4afc5a44a632"),
            new Blueprint("VeteranMarksmansBracersItem", "ddc7f55ecbc1b6d45a0dd1840217e07c"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.BlueprintItemNote),
          new()
          {
            new Blueprint("AboutAshyLady", "513ba66c1c7c4eccbddb507b8d8ea99b"),
            new Blueprint("LEXICON_Part2", "dec4cca417114684b750736cc81ee3e4"),
            new Blueprint("ZachariusNecromancy", "de12840a4662481f937ff9542a6beb6b"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Equipment.BlueprintItemEquipmentShoulders),
          new()
          {
            new Blueprint("Artifact_AeonCloakItem", "b24d6185acea1f949b026c3b58e47947"),
            new Blueprint("CloakOfSharpFangs", "79d4c7eb1cafab94984205bb2fe54dcd"),
            new Blueprint("WrathOfTheUndeadItem", "5e8470733b954db686cd2dbfaaf1f058"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.BlueprintUnlockableFlag),
          new()
          {
            new Blueprint("1Wave_FirstCleric", "38be8d6ddc3d450db71ae17ae895afa3"),
            new Blueprint("ForestQuestFirstDIalogHeal_flag", "9b8ccbeaa8d360049b442ecf9b23b5b9"),
            new Blueprint("ZombieRoomEnter2", "61f52bd1057441adbf7ce9901f535e3e"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Equipment.BlueprintItemEquipmentGloves),
          new()
          {
            new Blueprint("ALR_GlovesItem", "cb9ba081b011453597a4f4dd25bad2e6"),
            new Blueprint("GlovesOfEntropyItem", "5a4866e699544b2ab4feb18d3d7224cf"),
            new Blueprint("ViciousStompersItem", "efe72fa3d5164cdc93135c9e3cd91a22"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Equipment.BlueprintItemEquipmentHead),
          new()
          {
            new Blueprint("AngelFlowerCrownItem", "23b5ec958ec340eba7fb1dd18048ff82"),
            new Blueprint("HelmetFullplateRichSilverBlueItem", "282393f860a510b429432e13943f27c0"),
            new Blueprint("ZeorisDaggerHeadband_IntermediateItem", "51500154900d46ac9bd4d7ef758b3808"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Equipment.BlueprintItemEquipmentGlasses),
          new()
          {
            new Blueprint("CinderGogglesItem", "7e8fdec022c503a4ab8feddd08a712c9"),
            new Blueprint("GogglesOfMalocchioItem", "8f476e6a796971a48b1c87e822aca941"),
            new Blueprint("RatcatchersGogglesItem", "0285111eb68f0da429409ee16c40f868"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Shields.BlueprintItemShield),
          new()
          {
            new Blueprint("AncestralDwarwenShieldItem", "c62344a8b887b1f4d98d85b7c5b975b5"),
            new Blueprint("HeavyShieldItemPlusCultist3", "7ae5e6ce236b4dc3a2b4495653b98adb"),
            new Blueprint("WyrmwallShieldItem", "a3c44b8d08b634d479fd1ff01ab5fc08"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Armors.BlueprintShieldType),
          new()
          {
            new Blueprint("BucklerType", "26fcc43f7d20374498d2e1643381d345"),
            new Blueprint("LightShieldType", "d38e8ea23ce653c4582eb3e002555483"),
            new Blueprint("TowerShieldType", "5f0f4b6e480e7054b8592b5a8b55854a"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Equipment.BlueprintItemEquipmentUsable),
          new()
          {
            new Blueprint("AcidFlask", "4639724c4a9cc9544a2f622b66931658"),
            new Blueprint("ScrollOfInflictLightWoundsMass", "c6aedff3a8b16cb42847f3e9e9640328"),
            new Blueprint("ZachariusFallenWandItem", "622bb73ea55945b6a3d082e73166cc5c"),
          }
        },

        {
          typeof(Kingmaker.Visual.CharacterSystem.KingmakerEquipmentEntity),
          new()
          {
            new Blueprint("Blueprints", "04bef71f77fd414b9ee350c85a4a45a4"),
            new Blueprint("KEE_CapeWolfBlack", "dbff3cd156b24b1b8d571ab7e0ab7d55"),
            new Blueprint("KEE_Wizard", "3599bb75b6be4a59a638d5a98b7f3462"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.CharGen.BlueprintRaceVisualPreset),
          new()
          {
            new Blueprint("Aasimar_Standard_VisualPreset", "640e57f7890fa044ea78914930ddac5b"),
            new Blueprint("Halfling_VisualPreset", "639cebe8cbc098345af429d62fd79578"),
            new Blueprint("Zombie_VisualPreset", "f3f89ebfcb8e4dbdbb70837c97c4bcbb"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.Items.Weapons.BlueprintCategoryDefaults),
          new()
          {
            new Blueprint("DefaultsForWeaponCategories", "567dc59213fd9664c8cb291643439714"),
            new Blueprint("WeaponFocusColdIronStarting", "3da85a61d30d4bc483671f58b05bfd90"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Footrprints.BlueprintFootprintType),
          new()
          {
            new Blueprint("AnimalHoof_Footprint_Type", "13ec22b395ee448bbe9227cf9b3bf29c"),
            new Blueprint("AnimalPaw_Footprint_Type", "7644d89f154047ca8b0d61cd85245b44"),
            new Blueprint("Humanoid_Footprint_Type", "c1a1b28f9848437bb97dc8b53cb4a68a"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Footrprints.BlueprintFootprint),
          new()
          {
            new Blueprint("AnimalHoof_Footprint_Dust", "0d4fe54080db43c0b30fc635faa21c95"),
            new Blueprint("AnimalPaw_Footprint_Generic", "18a723039a9e46eb93b609f21def28bd"),
            new Blueprint("Humanoid_Footprint_Snow", "d1d8741286684caca5f0160b7c74f933"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAreaEffectPitVisualSettings),
          new()
          {
            new Blueprint("BlackHole_Settings", "12c1cf9d3d674cf47ae748ea3caf4d38"),
            new Blueprint("CreatePit_Settings", "98f7571740ad43648b63e6137b6988ef"),
            new Blueprint("DLC3_Nahyndri_Golemlike_Single_AnchorSlam_CustomPitSettings", "afb3023bf5d6456a84522ed3b42457f0"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Root.Fx.CastsGroup),
          new()
          {
            new Blueprint("DoubleHandCastGroup", "780a2d5ad49ca2349be6a572b59f9c70"),
            new Blueprint("SingleHandCastGroup", "cf2e8b48e31deea4ea62868c0e1784cd"),
            new Blueprint("TorsoCastGroup", "9a6f13652af861540aedf7a3552104b2"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Visual.LightSelector.BlueprintTimeOfDaySettings),
          new()
          {
            new Blueprint("Camp_Bonfire00", "40c05daf1bdf17243b7941475010e5d2"),
            new Blueprint("TorchLightSelection", "ea94b4cbda7a63441896c37ac4ba01fb"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Globalmap.Blueprints.BlueprintGlobalMap),
          new()
          {
            new Blueprint("KenabresMap", "5a903425adbaa02439df63ee129a6fb8"),
            new Blueprint("WorldWoundGM", "38ef391d8b3ee9742ad713ada0b62bed"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Area.BlueprintArea),
          new()
          {
            new Blueprint("Aeon_AreeluLabHouseInThePast", "5d975faa81f871c4da6d96485721dd7c"),
            new Blueprint("DLC3_ToxicPrison_3", "b3bd89f710b14cf89cabd85b0d3a95a9"),
            new Blueprint("Ziggurat", "e8f1160e960935344a8aa7466484506d"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Area.BlueprintAreaEnterPoint),
          new()
          {
            new Blueprint("AbyssA2FromA3", "3389bd198c5a30f499eae4b0212f1586"),
            new Blueprint("DrezenCitadel_Level1_FromGateC_Right", "dec2fff9a215b2747a63a3d76b56296f"),
            new Blueprint("ZigguratF1NearSkullPillar", "37f1e8a1a8cc0554fbfc554963aee870"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Area.BlueprintAreaPreset),
          new()
          {
            new Blueprint("Aeon_AreeluLabHouseInThePast_Default_Preset", "88413451fcaac634e81ef147d315cf97"),
            new Blueprint("DrezenCitadel_Level1_HellKnightsWay", "a0e6e1128f9f5944a862d41daf80233a"),
            new Blueprint("Ziggurat_Riot_Preset", "f780e21a07c198544be1eaa9a18c474f"),
          }
        },

        {
          typeof(Kingmaker.Globalmap.Blueprints.BlueprintGlobalMapEdge),
          new()
          {
            new Blueprint("Edge_02Army_DretchesFinances_01Army_CultistsFinances", "9e22245d4944dba458a43d0f3a9ea77d"),
            new Blueprint("Edge_Crossroads_Chapter05_13_Crossroads_Chapter05_17", "a9e24ead7eab7b040930008b35e42d9d"),
            new Blueprint("Edge_WoundwormsLair_08Army_CultistsRetreiversFavors", "53e170fe486793b4396615a0d5594fbb"),
          }
        },

        {
          typeof(Kingmaker.Globalmap.Blueprints.BlueprintGlobalMapPoint),
          new()
          {
            new Blueprint("01Army_CultistsFinances", "cef672902e676b14490bedcd99270b6a"),
            new Blueprint("Crossroads_NearNothernWW03", "0fbf823a6b9379441aeb15161fb781bb"),
            new Blueprint("Point_UndeadLair", "38a3dc6744c5a434dbdd96c3451a389a"),
          }
        },

        {
          typeof(Kingmaker.Globalmap.Blueprints.BlueprintGlobalMapPointVariation),
          new()
          {
            new Blueprint("Location_AreeluLab_True", "d2b827711b1669543a1444a411b9ac10"),
            new Blueprint("Location_Iz_normal", "d55569c0c2824a75a40bef9ba5dce4da"),
            new Blueprint("Point_LostChapel_Variation_1", "4425393168401e2439c90031fcc0ddd9"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Area.BlueprintAreaMechanics),
          new()
          {
            new Blueprint("Aeon_AreeluLabHouseInThePast_AeonRiftMechanic", "f0a6f3d20f05508468853964acba89c6"),
            new Blueprint("EcorcheLair_MythicLich", "24beb7f08d70cbf4f99d6d141e2828e1"),
            new Blueprint("WoundWormsLair_GamePlayMechanics", "dcf721fe056ae474e8726342cbf727cc"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.BlueprintItemKey),
          new()
          {
            new Blueprint("CircuarRoomKey", "64c8fa8c22473654294dff1cc6d1f1a9"),
            new Blueprint("EchoLairKey", "dac32e88810a20941a53a5960e581b3d"),
            new Blueprint("LetterFromVellexia", "eb90e06d98b9f4a4186e8c5145c2625b"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.Items.BlueprintItemThiefTool),
          new()
          {
            new Blueprint("ConsumableLockpickPlus10", "21d9f25b1f085e747b45621f28908e90"),
            new Blueprint("ConsumableLockpickPlus5", "39e4982215f14d44d93a864320df62bd"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Kingdom.Blueprints.BlueprintKingdomEventTimeline),
          new()
          {
            new Blueprint("Kingdom Event Timeline", "32138d56e3e0fa14a9471b5fee6629a9"),
            new Blueprint("KingdomEventTimeline", "621b55521be137247b13913dc9fd4c52"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Kingdom.KingdomUIRoot),
          new()
          {
            new Blueprint("KingdomUIRoot", "4baf8d7185eb4d942a06920c990e3dec"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Settlements.BlueprintSettlementBuilding),
          new()
          {
            new Blueprint("AlchemistLaboratory", "6ecb3570375b4ff899731851bc6eb676"),
            new Blueprint("Inn", "e036ddec60aa6c044a5830f2e1528329"),
            new Blueprint("Watchtower", "6cd75d70e2024eb699ad44fa2b7c942b"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Blueprints.BlueprintKingdomProject),
          new()
          {
            new Blueprint("Aeon2FireElementals", "63364fac363349a99dd7fe96ca86dc7c"),
            new Blueprint("Event61DrakeLeader", "a3db486aa8cc4108a61206727223e5a3"),
            new Blueprint("ZeorisDaggerRingProject_Enchanting", "0dc3a4e036064970857b3c3e296a7d94"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Blueprints.BlueprintCrusadeEvent),
          new()
          {
            new Blueprint("AbductedSouls_event", "446e4191ab45485ca8316e4b388d4671"),
            new Blueprint("CrusadeEvent67", "e26d6e736ada45868ad5da00723becb3"),
            new Blueprint("ZeorisDagger_Reforge_event", "abc63262848a4e8d8d0d055b9e0a7d67"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Blueprints.BlueprintKingdomEvent),
          new()
          {
            new Blueprint("AeonQ10_StartKTC", "9b7fdf9a6d722d942879c7922daa507f"),
            new Blueprint("KTC_DragonsDusk_LatimasComes", "bd63f8d6b1b54c839fdec2e5082fdbe3"),
            new Blueprint("WenduagKTC_WenduagComeNeathholm", "b0281d9068d670845927a1827be6e7bb"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Kingdom.AI.SettlementBuildList),
          new()
          {
            new Blueprint("DrezenCh3BuildList", "d5e63ee43b724ad0a478709ba6db7a5f"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Flags.BlueprintKingdomMoraleFlag),
          new()
          {
            new Blueprint("KingdomMoraleFlagChapter2", "6195e82164ff47d3a67ff5fd0d74d5e3"),
            new Blueprint("KingdomMoraleFlagChapter5", "feb5d6bf90404f41b573f096a9f5d93a"),
            new Blueprint("TestKingdomMoraleFlag3", "1711a55113a843ce8032dfaa513be9fd"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Blueprints.BlueprintRegion),
          new()
          {
            new Blueprint("Region01", "f77b533b72bb47a2951384f61e44de52"),
            new Blueprint("Region06", "2a5f009c48d042fd8dee4764631f17b4"),
            new Blueprint("Region10", "a2c96f4b17864c0bad38901f726ae345"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.BlueprintSettlement),
          new()
          {
            new Blueprint("0_AutumnForest_Settlement", "a74b2be33e6b3f44c974b1a17a4a84ee"),
            new Blueprint("Settlement06_Reg4_1", "54db9b19960241ef9068910e81fb9212"),
            new Blueprint("TestSettlement", "79ec83f90dea56b4c97c822525e4c999"),
          }
        },

        {
          typeof(Kingmaker.Armies.TacticalCombat.Blueprints.BlueprintTacticalCombatArea),
          new()
          {
            new Blueprint("TacticalCombatAutumnForest", "997dcf12373adc1488926cd025a4ac0b"),
            new Blueprint("TacticalCombatWorldWound01", "03c2cda4d3b155841a0be9acb3048909"),
            new Blueprint("TestTacticalCombatArea", "46b8248a7204c1347a087d85c8a2439c"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Loot.BlueprintLoot),
          new()
          {
            new Blueprint("2wine_bottle (1)", "e7f447e2306708443bcbd6c05983d1e3"),
            new Blueprint("PF2_Demons_MimicChestObject1", "d7ff134427e69b540a8a4961b7375336"),
            new Blueprint("ZantirRuneLootContainer", "f65148f38532e0a4ebacad5e5fe18fd7"),
          }
        },

        {
          typeof(Kingmaker.Globalmap.Blueprints.BlueprintMultiEntranceEntry),
          new()
          {
            new Blueprint("AlushinyrraBadLuckMultiEntranceEntry", "20f5b7a3b32ba0a419e1406e965d54ed"),
            new Blueprint("DrezenBarracksMultiEntranceEntry", "7ecd6d49c5d742fe9a5162d7508f8172"),
            new Blueprint("DrezenThroneRoomMultiEntranceEntry", "828674d1b8fe23641bdc71c192f9f10f"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Globalmap.Blueprints.BlueprintMultiEntrance),
          new()
          {
            new Blueprint("AlushinyrraMultiEntrance", "5f531d59bbf5b754cb82439c2376aea3"),
            new Blueprint("DrezenMultiEntrance", "a179d214cbab4ee40b0ea3f7f312fb57"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.BlueprintClassAdditionalVisualSettings),
          new()
          {
            new Blueprint("Aeon_1_Visual", "730fc1cac06843618bfffeed2722952f"),
            new Blueprint("Devil_2_Visual", "780242191b6249baa0a33db80deae2dc"),
            new Blueprint("Trickster_2_Visual", "5146db32f73f4b1e9b6fc111cc485727"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.BlueprintClassAdditionalVisualSettingsProgression),
          new()
          {
            new Blueprint("Aeon_Progression", "b9a8399e2d3341bca4ec30ed4cee05a2"),
            new Blueprint("Devil_Progression", "63e3f149fc024ed8969e6fcb87b1b783"),
            new Blueprint("Trickster_Progression", "9301b0648cbf4024871addea1e373a2d"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.Classes.BlueprintFeatureSelectMythicSpellbook),
          new()
          {
            new Blueprint("AngelIncorporateSpellbook", "e1fbb0e0e610a3a4d91e5e5284587939"),
            new Blueprint("LichIncorporateSpellbookFeature", "3f16e9caf7c683c40884c7c455ed26af"),
          }
        },

        {
          typeof(Kingmaker.QA.Arbiter.BlueprintArbiterInstruction),
          new()
          {
            new Blueprint("Act1_HorgusManorBasement", "d4d886b0e5e54d9d9f1bb79ccd886260"),
            new Blueprint("GrayGarrison_Legend", "086a3185e2dc48f5a7a3733e906a9cf0"),
            new Blueprint("Ziggurat", "fe94dc31669628948b1c3290148f3112"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.QA.Arbiter.BlueprintArbiterRoot),
          new()
          {
            new Blueprint("ArbiterRoot", "14b876bb540b47978760242b0919e355"),
          }
        },

        {
          typeof(Kingmaker.RandomEncounters.Settings.BlueprintCampingEncounter),
          new()
          {
            new Blueprint("ArueshalaeAfterLab_CampingEncounter", "b1501473507eb00418ab14db5fd9f23a"),
            new Blueprint("MythicDemonDreamBE1", "1eb2a0f420971f44ba7a2e0aac53f954"),
            new Blueprint("WenduRom_SomeThingsAboutMyFather_CampingEncounter", "a659923cdc1497044a2e385212c114f6"),
          }
        },

        {
          typeof(Kingmaker.Controllers.Rest.Cooking.BlueprintCookingRecipe),
          new()
          {
            new Blueprint("AcornPieRecipe", "fe4c7fac8007fdc4698ff6c0d56e78ca"),
            new Blueprint("GodspeedSaladRecipe", "4d80045a70ccefa4a968293461e7d6f7"),
            new Blueprint("Test_Bebilith Blueprint Cooking Recipe", "293bc27a21f5e7a47b064898863aae78"),
          }
        },

        {
          typeof(Kingmaker.Visual.Sound.BlueprintUnitAsksList),
          new()
          {
            new Blueprint("Abrikandilu_Barks", "97c7b7df236d38d4083756c6e71e038b"),
            new Blueprint("Lilithu_Barks", "08184ae01ef7a414da9edbd05a58144c"),
            new Blueprint("Zombie_Barks", "5b77c4c031391294b920f5a1e119b959"),
          }
        },

        {
          typeof(Kingmaker.AreaLogic.Etudes.BlueprintEtude),
          new()
          {
            new Blueprint("01_DevouredByDarkness", "67d3321ed01a4e58a9ed3e13f94f1d04"),
            new Blueprint("IncubusBandLair_MainEtude", "57ae0e478ced5634fbfc33ec950eb0c8"),
            new Blueprint("ZosielQ0", "6d1bb3f8743892a4aaf498f7fc5212f0"),
          }
        },

        {
          typeof(Kingmaker.QA.Clockwork.BlueprintClockworkScenario),
          new()
          {
            new Blueprint("123", "535217378b8a4ca3ba5a45f0002de07c"),
            new Blueprint("Drezen_MainEntrance", "07ea805ba97187745bbdc14526af7626"),
            new Blueprint("WarCamp_Start_Simple", "cc9b472d6185c754f9f7f8090aef6c8b"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Classes.BlueprintLevelUpPlanFeaturesList),
          new()
          {
            new Blueprint("Clockwork_Aeon_LevelupPlan", "ad1fd4c61fcc4e9c973b65b1b57c5c9d"),
            new Blueprint("Clockwork_GoldenDragon_LevelupPlan", "1e0d276b44ea4bbfb81c2169330c3a31"),
            new Blueprint("Clockwork_Trickster_LevelupPlan", "8728ded3608647958dfbf12d5f474939"),
          }
        },

        {
          typeof(Kingmaker.QA.Clockwork.BlueprintClockworkScenarioPart),
          new()
          {
            new Blueprint("CameliaQ", "101d0616dbd24b3188d8e18130c11e3c"),
            new Blueprint("mAeon3chap", "1c0b53dad1b14730a1928fc4262b8da2"),
            new Blueprint("WoljifQ", "d79f05dbd35b468fa16312f30d61a5e1"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonCampaign),
          new()
          {
            new Blueprint("BlueprintDungeonCampaign", "e211897d17504b9a804b41fbda91d0d4"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.Root.BlueprintRoot),
          new()
          {
            new Blueprint("BlueprintRoot", "2d77316c72b9ed44f888ceefc2a131f6"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.UI.BlueprintUISound),
          new()
          {
            new Blueprint("BlueprintUISound", "9ca148bb795619c478e9fbcc969acd61"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Corruption.BlueprintCorruptionRoot),
          new()
          {
            new Blueprint("CorruptionRoot", "048628b2f365c8b429ec05a4bf5363f7"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Craft.CraftRoot),
          new()
          {
            new Blueprint("CraftRoot", "ecf0bbd052e4d7f44892dfd0601c812e"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.CustomAiConsiderationsRoot),
          new()
          {
            new Blueprint("CustomAiConsiderations", "85b340cfdfad6bd4795dd6beda230539"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.Root.CutscenesRoot),
          new()
          {
            new Blueprint("CutscenesRoot", "32e79d16ebca6054790028407bcc1b71"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonLocalizedStrings),
          new()
          {
            new Blueprint("DungeonDLC3Localization", "3f882abc4ca2c0946b3b3be8b13fdedd"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonRoot),
          new()
          {
            new Blueprint("DungeonRoot", "096f36d4e55b49129ddd2211b2c50513"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.Root.Fx.FxRoot),
          new()
          {
            new Blueprint("FxRoot", "c5adca94da7c1bd48947a5cfb3a92c9a"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Visual.HitSystem.HitSystemRoot),
          new()
          {
            new Blueprint("HitSystem", "b13820523d5b98e4fafdc868e8fb27df"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Interaction.BlueprintInteractionRoot),
          new()
          {
            new Blueprint("InteractionRoot", "1a14f0e76dc1d4746bb26d473b50a76f"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintPhotoModeRoot),
          new()
          {
            new Blueprint("PhotoModeRoot", "64aad67f92c7478ebcff0b51dbeb885c"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.Root.SpellSchoolRoot),
          new()
          {
            new Blueprint("SpellSchoolRoot", "dafff0045dcf4f5c8c21d79af064cb93"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Armies.TacticalCombat.Blueprints.BlueprintTacticalCombatRoot),
          new()
          {
            new Blueprint("TacticalCombatRoot", "7be62f97e9de9f741a60d9924b934b64"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Loot.TrashLootSettings),
          new()
          {
            new Blueprint("RE_TrashLootSettings", "daf5872cc909705428f4a092d05351d1"),
            new Blueprint("TrashLootSettings", "b2554a2be56f1c6478c14a442b0f64f3"),
            new Blueprint("TrashLootSettings_DLC3", "77fe4de4c707e51439971ee480e94efc"),
          }
        },

        {
          typeof(Kingmaker.DialogSystem.Blueprints.BlueprintAnswer),
          new()
          {
            new Blueprint("Answer_0001", "a5ea39b6ccc54b8cbf5f4afee192d860"),
            new Blueprint("Answer_0022", "86c03df059a6a7f4386ab059b63eef2f"),
            new Blueprint("WintersunQuestComplitingIrabeth", "5eef43d4b657ff84b960777b2fa7b53c"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.DialogSystem.Blueprints.BlueprintMythicsSettings),
          new()
          {
            new Blueprint("MythicsSettings", "3b8a6729da1e13a4e8e606e9f0fa38d8"),
          }
        },

        {
          typeof(Kingmaker.DialogSystem.Blueprints.BlueprintMythicInfo),
          new()
          {
            new Blueprint("AeonUnlocked", "58650dffca246f244853af263ed38126"),
            new Blueprint("PlayerIsAngel", "e5c0623ab47e361429ad66a3d687cccd"),
            new Blueprint("TricksterUnlocked", "a6c23a6ce6ab8864da50563af0ddd952"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.Root.FormationsRoot),
          new()
          {
            new Blueprint("FormationsRoot", "d5fe855c2ee3dfe4fae440979505dd33"),
          }
        },

        {
          typeof(Kingmaker.Formations.BlueprintPartyFormation),
          new()
          {
            new Blueprint("Formation_Auto", "1528ed7057903244f98c2d3c2851b3ec"),
            new Blueprint("Formation_Custom_03", "a38b14ca3fb0c05409c5c8e45fb5687c"),
            new Blueprint("Formation_Custom_05", "16bee6581f72d8f4b8028d5307f67d8d"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Formations.FollowersFormation),
          new()
          {
            new Blueprint("Formation_Followers_Default", "a198d360f0d0cc643a1b104d6c5346ac"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Kingdom.Blueprints.ArmyRoot),
          new()
          {
            new Blueprint("ArmyRoot", "da5bb9a901139f54499f38f12278299d"),
          }
        },

        {
          typeof(Kingmaker.Kingdom.Blueprints.BlueprintArmyPresetList),
          new()
          {
            new Blueprint("Chapter2TravellingArmyList", "e24237d36f6972246b27a78141370bb2"),
            new Blueprint("Chapter3TravellingArmyList", "11ad5b669d1caf243acd84bcf4fca80d"),
            new Blueprint("Chapter5TravellingArmyList", "735e7b05503c440992b3c90804cdcb7c"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Kingdom.Blueprints.BlueprintCrusadeEventTimeline),
          new()
          {
            new Blueprint("CrusadeEventTimeline", "ff66e77f5be74b7ba85588df91afb9f7"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Kingdom.Blueprints.BlueprintKingdomDeck),
          new()
          {
            new Blueprint("KingdomDeck", "5f62fd51df12c83498b2f93e966c7d18"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Kingdom.Blueprints.KingdomRoot),
          new()
          {
            new Blueprint("KingdomRoot", "f6bd33651fb0ad64d8fa659d3df6e7df"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Kingdom.Blueprints.LeadersRoot),
          new()
          {
            new Blueprint("LeadersRoot", "4877146e3e476754586717388ef45e5c"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Armies.Blueprints.MoraleRoot),
          new()
          {
            new Blueprint("MoraleRoot", "d320ebdcfd2aac44e94a18f3d3879f4c"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintPersonageLimits),
          new()
          {
            new Blueprint("BlueprintPersonageLimits", "2a609e8ce9844f98ae11097bef7be8bb"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.BlueprintTrapSettingsRoot),
          new()
          {
            new Blueprint("BlueprintTrapSettingsRoot", "099fe2b5a9c0d0e449375cb7c491cc25"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.BlueprintTrapSettings),
          new()
          {
            new Blueprint("TrapSettings_CR0", "0bd985f084223d5419b9c0e004782a2b"),
            new Blueprint("TrapSettings_CR22", "1cb8ef6922f74624d8e49ed82a1ef70a"),
            new Blueprint("TrapSettings_CR9", "4e1d3a94b2f42874784858461492e1f6"),
          }
        },

        {
          typeof(Kingmaker.EntitySystem.Persistence.Versioning.BlueprintUnitUpgrader),
          new()
          {
            new Blueprint("PF-229479-RecreateAreshkagalOnLoad", "c048cb6cb12c4c578c312cf1ea5ebdce"),
            new Blueprint("PF-340663-RecreateUnitOnLoad", "0a013e4bab2b456fbd9a265fd32907b2"),
            new Blueprint("UpgradeUnitRobe2ST2DC", "0da99f59dbfc45b49864819a5ad0c3ec"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Area.BlueprintAreaPart),
          new()
          {
            new Blueprint("AbyssBridgePart", "c5a7a2db417d4e05ae0bef27f31bf339"),
            new Blueprint("GiantsLair_Cave", "6231a4e681b4eeb4e80021cd5eea6cd4"),
            new Blueprint("WoundWormsLairGreenhouse", "5a0b876904793e444bb232c0a228571d"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Area.BlueprintLogicConnector),
          new()
          {
            new Blueprint("AltarDamage_Actions", "35995aa895b843ab9c2d75d3a158487e"),
            new Blueprint("GateDLeverLogicConnector", "40ec21a61892adc429b43667f5b497bc"),
            new Blueprint("TestDamagedMapobject", "149d05c335f0cd24ca4a8866e968bb1d"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Area.BlueprintTrap),
          new()
          {
            new Blueprint("Blueprints[NOTUSED]", "e6713f4a0bde49648b43e93bf372b0d2"),
            new Blueprint("Lvl7_DraftFireballTrap", "3a9e14a3d6727f14ab684f395c2d722b"),
            new Blueprint("TestTrap", "42e2e9b03f91f824eb1ff8200a6b17de"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Dungeon.Blueprints.BlueprintDungeonIslandReward),
          new()
          {
            new Blueprint("Reward1", "c3323b1c1cc94a59a5df85692baaf227"),
            new Blueprint("Reward2", "c66fd9d6710342a192c1c4326c5072e3"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.Items.BlueprintHiddenItem),
          new()
          {
            new Blueprint("FinneanBaseItem", "95c126deb99ba054aa5b84710520c035"),
            new Blueprint("TestFinneanItem", "508d135c08de4661ba32b27e424e6a4c"),
          }
        },

        {
          typeof(Kingmaker.Tutorial.BlueprintTutorial),
          new()
          {
            new Blueprint("ContextTutor_AbilityDamage", "f579133d7ad865e488551b7aa59c22da"),
            new Blueprint("CrusadeTutorial_12_Chapter3Morale_Gamepad", "a65b683d61cd4c8fa786c127e5f4a3ee"),
            new Blueprint("TestTutorialSC", "2e48c8330634d544489e1fc14ccf5eaa"),
          }
        },

        {
          typeof(Kingmaker.DialogSystem.Blueprints.BlueprintDialog),
          new()
          {
            new Blueprint("AasimarSlaves_dialogue", "304ee413422cde24a9cfb21bd4d49d9d"),
            new Blueprint("KTC_AfterRankUp8_dialogue", "4917f7c37a9767d46a94ee6eac8459ad"),
            new Blueprint("Ziforian_HailNewLord_dialogue", "36ebdcd5de9a56541b546ef9bcec463e"),
          }
        },

        {
          typeof(Kingmaker.DialogSystem.Blueprints.BlueprintCue),
          new()
          {
            new Blueprint("AgressiveEnd", "6d321264a441daf498f1493c9f13dba1"),
            new Blueprint("Cue_0030", "9e13e4293e91dd54cb436252c738d723"),
            new Blueprint("Xorges_shared12_2", "518e96fc4479fec44b98fa1f35c42da1"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Area.BlueprintScriptZone),
          new()
          {
            new Blueprint("02_ScoutsDead_objZone", "3ffadf67fe817d444b1cb9c6cff78744"),
            new Blueprint("Irabeth_FirstAttack", "7f744b26db329304a94c6d0d3dac2f39"),
            new Blueprint("Zone3_Epigraph_SZ", "fde009ee2ae62024baaac478de277b28"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.BlueprintLoadingScreenSpriteList),
          new()
          {
            new Blueprint("BlueprintLoadingScreenSpriteList", "33093c567d0042ffbc3cf5ec327a7949"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.BlueprintUIInteractionTypeSprites),
          new()
          {
            new Blueprint("BlueprintUIInteractionAction", "9985e6a4e6b948f988fcd3ca37ac0bc7"),
            new Blueprint("BlueprintUIInteractionInsturment", "63e22fd4bf54484991b8e1ee9ef42387"),
            new Blueprint("NewBlueprintUIInteractionGravedigger", "c335a40583d24a198753c9fab069a742"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.UnitAnimationActionSubstitution),
          new()
          {
            new Blueprint("CentipedeLocomotion", "e14f88dabb1c479389a35eb9f349c8a1"),
            new Blueprint("HumanLocomotion", "cbde3045a9ab46319c8bf9e987bba304"),
            new Blueprint("MonitorLizardLocomotion", "a3d8ec9931ff4a7f963c8fc14dbb6cd7"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Customization.UnitCustomizationPreset),
          new()
          {
            new Blueprint("Bandits_CustomizationPreset", "7033ff076a464555bac0a43a43351492"),
            new Blueprint("CP_UrgathoaPatrol", "1f5e95d8275542179e72da6529dd11d8"),
            new Blueprint("Test_CustomizationPreset", "f2fde6100e2842bb9b08555c11a5a75f"),
          }
        },

        {
          typeof(Kingmaker.UnitLogic.Customization.RaceGenderDistribution),
          new()
          {
            new Blueprint("Barbarian_Distribution", "3f15d11f49cf456cb6c7bc16cbfb1f2f"),
            new Blueprint("Distribution_Standart_male", "0395873092a3491d8ad68da5d81155e1"),
            new Blueprint("Noble_Distribution", "fa02ce3a43c24bb0b9fe48e6a28a5307"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.Weapons.BlueprintWeaponType),
          new()
          {
            new Blueprint("BalorWhipType", "5d6eb4bac6963594c95a03bf7c79c907"),
            new Blueprint("IncoporealBiteType", "c6ca9495acc490c44958e1f9da1b2538"),
            new Blueprint("WingType", "e03738c69ae8c914c827e72a3ca91f83"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.CanMakeFullAttackConsideration),
          new()
          {
            new Blueprint("CR23Protean_CanMakeFullAttack", "df49459080f54448a507c450c223c013"),
            new Blueprint("Gallu_Consideration_NoFullAttack", "0e8d7aca50028e4479b360c381a20d47"),
            new Blueprint("Painajai_Consideration_NoFullAttack", "be855ad5ceff58b46bae629078ab048d"),
          }
        },

        {
          typeof(Kingmaker.AI.Blueprints.Considerations.DirectionConsideration),
          new()
          {
            new Blueprint("DLC3_DirectionConsideration", "767d23f6e78a4dd1957a7d7171895eeb"),
            new Blueprint("DLC3_DirectionConsideration_Front_180", "d4e643e1f7404ca8846f0a48d91a2e51"),
            new Blueprint("DLC3_DirectionConsideration_Front_90_Clear", "5e6f5dc2f4f14f67b842c0a97dbfa66b"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.ConditionConsideration),
          new()
          {
            new Blueprint("DLC3_Nahyndri_Golemlike_MoveConsideration", "245100d2aa5f4d3590f18258033b0fc0"),
            new Blueprint("DLC3_Nahyndri_Golemlike_OverRunConsideration", "2bbbbe7f5dd141b1a1e43dfbafa43abf"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.BlueprintAiRoam),
          new()
          {
            new Blueprint("DLC3_Nahyndri_Walk_HighScore", "625a141edc4c4a8e96d78e51953a606a"),
            new Blueprint("DLC3_Nahyndri_Walk_LowScore", "11e5722e40e74cf48e45f216806c7294"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.AI.Blueprints.Considerations.CasterClassConsideration),
          new()
          {
            new Blueprint("CorruptedHerald_Phase1_CR25_DivineCasterConsideration", "b0c795692cba98e4cbc96c07a87f519a"),
            new Blueprint("Kestoglyr_ChargeConsideration", "986584b8f54b56b4a919218f75173711"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.BlueprintPortrait),
          new()
          {
            new Blueprint("00215987193f18a42a2e0edcb24d9cf0_BCT_AeonViram", "af7b32dd4aaf40bbb0e08f6736f036f2"),
            new Blueprint("BCT_Cultist_Fullplate_Baphomet", "1d37a7f1362246a5ab9f0dd422e8f31e"),
            new Blueprint("Ygefels", "d53a2a03fc4945aeafe3b4c27aeaf810"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.BlueprintUnitType),
          new()
          {
            new Blueprint("AeonBythos", "939b1d85aed5520438285bb2dc6ea7f1"),
            new Blueprint("HellHound", "fb26bf690143ebb48b692b1dfdd22830"),
            new Blueprint("Zombie", "0bd298db2bfec6b409c5ca90cd3c8c4c"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Area.BlueprintAreaTransition),
          new()
          {
            new Blueprint("2ALR_BlueprintAreaTransition", "caa1a113bb2c18e4bb187348664d4c99"),
            new Blueprint("HeavenDoorstep_Exit", "65c0814c7b17e1149a65e2d340368656"),
            new Blueprint("ZigguratEnter_AreaTransition", "c8a709930aa977d499dc797c22f42bb9"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.BlueprintComponentList),
          new()
          {
            new Blueprint("GargoyleAttack_ComponentList", "973e83220db9f474289a572f1d953987"),
            new Blueprint("LC_Outdoor", "163aad1de63fe1043acc8fb1143c9fd0"),
            new Blueprint("WoundWormsLair_ComponentList", "b6820bb2462fd2d4f8a9f87dc013c262"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.RandomEncounters.Settings.RandomEncountersRoot),
          new()
          {
            new Blueprint("RandomEncountersRoot", "3002b382d7973b04bb151c5a1d127a1b"),
          }
        },

        {
          typeof(Kingmaker.RandomEncounters.Settings.BlueprintSpawnableObject),
          new()
          {
            new Blueprint("SpawnableObject_Box_02", "63a9056736123084aa1c2128eb881794"),
            new Blueprint("SpawnableObject_StumpKarelia", "8100cc2df19bf614cbec48f94ac4d4d5"),
            new Blueprint("SpawnableObject_StumpSnow", "84db35b80c642e5499feb122f6914d85"),
          }
        },

        {
          typeof(Kingmaker.RandomEncounters.Settings.BlueprintRandomEncounter),
          new()
          {
            new Blueprint("BP_RE_KareliaCanyon", "fca2b85a9ff5b8340952d97260227edd"),
            new Blueprint("SE_DevilSnatchGMBE", "9e053370d18dd5c499561347c5f9b385"),
            new Blueprint("SE_YakerInWarCamp", "b03555b40a2916a409436a2afb313f8e"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Area.BlueprintSettlementAreaPreset),
          new()
          {
            new Blueprint("AutumnForestSettlement_Preset", "95bc434cb33b4d8b9579314a14b5c851"),
            new Blueprint("DrezenSettlement_Preset", "4d5a7ced794d4e7cbe85aa27e474e219"),
            new Blueprint("WinterForestSettlement_Preset", "7137d71f66394c05a59dc9e5bf8842de"),
          }
        },

        {
          typeof(Kingmaker.Crusade.SettlementBlueprintArea),
          new()
          {
            new Blueprint("Capital", "69a8a5d331f0d7f4c983a1de63b925b0"),
            new Blueprint("Settlement_Drezen", "a8f1b3c4a1fc45bd92f57a1b3c70f5fe"),
            new Blueprint("Settlement_WinterForest", "0f8354e867b24b6399491e74c4f93a2f"),
          }
        },

        {
          typeof(Kingmaker.DialogSystem.Blueprints.BlueprintAnswersList),
          new()
          {
            new Blueprint("AnswersList_0001", "9476bee1e1a84f9abe1d5a72fcf7b7e3"),
            new Blueprint("AnswersList_0013", "d8a9f7bca63ad7f44834173007fdc23e"),
            new Blueprint("AnswersList_9", "5b860d34c56245e28ddeaa7a2d925ab4"),
          }
        },

        {
          typeof(Kingmaker.DialogSystem.Blueprints.BlueprintCueSequence),
          new()
          {
            new Blueprint("CueSequence_0001", "a545d5b5b3c34513a191cc4ae0190c77"),
            new Blueprint("CueSequence_0034", "d381ef71ecf0a9540b2548ace1957c03"),
            new Blueprint("CueSequence_Special", "f8d7f50e3bb88c143834d234c0b24474"),
          }
        },

        {
          typeof(Kingmaker.DialogSystem.Blueprints.BlueprintSequenceExit),
          new()
          {
            new Blueprint("SequenceExit_0001", "8eb716b10f2548d59ba106b7b38f5793"),
            new Blueprint("SequenceExit_0037", "6eeaeba81e203664196702c906486520"),
            new Blueprint("SequenceExit_exit", "1a55629b13dd0264e9799988422c4d4e"),
          }
        },

        {
          typeof(Kingmaker.DialogSystem.Blueprints.BlueprintCheck),
          new()
          {
            new Blueprint("Check_0001", "22c9e05be1754b92afe88f1cb42e25cf"),
            new Blueprint("Check_0027", "9722f2a87d27f9842be05b8fb216d531"),
            new Blueprint("Check_9", "00ff28a25f3e4294ba40fa13fac872dc"),
          }
        },

        {
          typeof(Kingmaker.AreaLogic.Cutscenes.Cutscene),
          new()
          {
            new Blueprint("1stFight_Final", "8ef514ae57a6c704ba2e125a4e0f78ad"),
            new Blueprint("Horgus_Comes", "761e97240b3e7a34b81a1921b33bf498"),
            new Blueprint("Zone3_Epigraph", "00f1dceaedf422e41f2d9cd0d9c6e571"),
          }
        },

        {
          typeof(Kingmaker.AreaLogic.Cutscenes.Gate),
          new()
          {
            new Blueprint("gate", "fc268500370d415da9cf27c32043ace3"),
            new Blueprint("gate 2", "84b0415b2591cc84c99a93006d3f0d91"),
            new Blueprint("gate9", "5b1a0b6731eb475692ebef9f02f1808b"),
          }
        },

        {
          typeof(Kingmaker.BarkBanters.BlueprintBarkBanter),
          new()
          {
            new Blueprint("Banter_Arueshalae_ch3_1", "2f1cc9c8d49a440448a2ec226a33b2de"),
            new Blueprint("Banter_Nenio_ch1_2", "b65d48a37123f4d47b829461bf95c764"),
            new Blueprint("DLC2_banter_test_3", "28714753d4194ac6b1bdf8751808cf13"),
          }
        },

        {
          typeof(Kingmaker.DialogSystem.Blueprints.BlueprintBookPage),
          new()
          {
            new Blueprint("BookPage_0001", "ee776f7d205f3484e9def0e007c5623f"),
            new Blueprint("BookPage_0052", "ded4a9f16119446dae22b338fdbe8135"),
            new Blueprint("BookPage_Room7Trap", "9e5fd16501f11e9499229751921dc4e5"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.BlueprintCompanionStory),
          new()
          {
            new Blueprint("Arueshalae_Evil", "7faca0a0dfa6eac4ca7fa04c2200b52e"),
            new Blueprint("Lann_Q1", "b1a07412f0a8fbe4b964dfd7ccce5402"),
            new Blueprint("Woljif_q3_HumanEnding", "b3b6105959e0c0541b0b16cb85c012dc"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Quests.BlueprintQuest),
          new()
          {
            new Blueprint(" JoCat_Errand", "182aeccdeab24ef5b32e6d09c170e545"),
            new Blueprint("HepzaTrap", "abad633c8e954194788fee3807a238ed"),
            new Blueprint("ZanedraEscape", "62689e32325839e40b9ee3fc6a110f10"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Quests.BlueprintQuestObjective),
          new()
          {
            new Blueprint("00_FindEchoLair", "876fc5d40aa5d8b47ac0138cf0a680ae"),
            new Blueprint("Obj_03_FindStone", "1ccd6c0894394ec099e007687d3e0ece"),
            new Blueprint("ZanedraEscape_HiddenFail", "68ed42df16e2a614aa6b5eb02c23fc59"),
          }
        },

        {
          typeof(Kingmaker.Blueprints.Items.BlueprintItemsList),
          new()
          {
            new Blueprint("AreeluPuzzleItems", "bdb5058ff8c9424a9d992abdfe050247"),
            new Blueprint("Orange_04_OtherSlotDirect", "c113c519092e1ce4592ef2f9447d0832"),
            new Blueprint("YellowPuzzleItems", "5affd77d973a81f4a98dc307a8d76792"),
          }
        },

        {
          typeof(Kingmaker.AreaLogic.Etudes.BlueprintEtudeConflictingGroup),
          new()
          {
            new Blueprint("Aeon_AreeluLab_Rift", "6edd9a3e36c586545852c481d2cdbdab"),
            new Blueprint("Capital_NPC_Socotbenoth", "e317ddf58ed338b4a95eaee0cb501fc9"),
            new Blueprint("YozzInGuild", "dcce7cde02934584a3f87f479ac856b6"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.Quests.BlueprintQuestGroups),
          new()
          {
            new Blueprint("QuestGroups", "ef88df6af8491fc45aef8511a33a89a4"),
          }
        },

        {
          // Flag for review
          typeof(Kingmaker.Blueprints.BlueprintRomanceCounter),
          new()
          {
            new Blueprint("CamelliaRomanceRomanceCounter", "74882d9746172bb47beba26e6ee86b5b"),
            new Blueprint("SosielRomanceRomanceCounter", "420fe10d958094b409dec479fa358bce"),
          }
        },
      };
  }
}
