using BlueprintCoreGen.CodeGen.Methods;
using System;
using System.Collections.Generic;
using Kingmaker.Designers.EventConditionActionSystem.Conditions;
using Kingmaker.UnitLogic.Mechanics.Conditions;
using Kingmaker.Kingdom.Conditions;
using Kingmaker.Assets.Designers.EventConditionActionSystem.Conditions;
using Kingmaker.Kingdom.Flags;
using Kingmaker.UnitLogic.Buffs.Conditions;
using Kingmaker.ElementsSystem;

namespace BlueprintCoreGen.CodeGen.Overrides.Examples
{
  // Examples generated by TypeUsageAnalyzer
  internal static class ExampleConditions
  {
    public static readonly Dictionary<Type, List<Blueprint>> Examples =
      new()
      {

        {
          typeof(ItemsEnough),
          new()
          {
            new Blueprint("AcidButton1_CheckPassedActions", "2a969038211346358597f80d271d9b94"),
            new Blueprint("Answer_6", "11dcb93a9d964a1ab005b10f899db142"),
            new Blueprint("ZeorisDagger_ReforgeProject", "22e8219563e84f11b6aed62661030770"),
          }
        },

        {
          typeof(ContextConditionIsCaster),
          new()
          {
            new Blueprint("AllRoundDefenseAreaEffect", "5e56c4ff29094864aa23ec9b5b4ccf57"),
            new Blueprint("HalfOfPairedPendantArea", "8187fd9306b8c4f46824fbba9808f458"),
            new Blueprint("ZeroState", "c6195ff24255d3f46a26323de9f1187a"),
          }
        },

        {
          typeof(ContextConditionIsAlly),
          new()
          {
            new Blueprint("AeonAoOGazeArea", "bc346635e3d04df7968249d59ea756ba"),
            new Blueprint("EclipseChillOnBuff", "1d585582fbe72e14aadc5cd7985c06f4"),
            new Blueprint("WrathOfTheUndeadArea", "22e31702587142ddb99391d589ba538b"),
          }
        },

        {
          typeof(ContextConditionTargetIsYourself),
          new()
          {
            new Blueprint("ArcanistExploitArmoredMaskAbility", "2d7d510c6e2e3e54ab9eee84a41fa2cf"),
            new Blueprint("EnlargeSelf", "549e9fcaadc861348b05bf01624387aa"),
            new Blueprint("Valmallos_Area_Gaze", "d031e701dee3487f8a8b7da39e722267"),
          }
        },

        {
          typeof(TargetHasArmyTag),
          new()
          {
            new Blueprint("Aeon5BaneOfDemonsAbility", "843145bc1b9b45229c40b1a2128095f0"),
            new Blueprint("RangerBlindingTrapArea", "b4b532d5cd6f81642a6783a93ace06d1"),
            new Blueprint("RitualHealAbility", "08c5571e87eccfc47a8325f530e3693c"),
          }
        },

        {
          typeof(ContextConditionCasterHasFact),
          new()
          {
            new Blueprint("AcidBomb", "fd101fbc4aacf5d48b76a65e3aa5db6d"),
            new Blueprint("GreaterCognatogenIntelligenceCharismaBuff", "1c2fdba3b33dacd41afd5b74d84c7332"),
            new Blueprint("WrathOfAncestorEnchantment", "4dbc03bd6223b484d8cd9afc3e0369b0"),
          }
        },

        {
          typeof(ContextConditionAlignment),
          new()
          {
            new Blueprint("AeonAoOGazeArea", "bc346635e3d04df7968249d59ea756ba"),
            new Blueprint("HolyWhisper", "5f1ca17be3ba44949be427f18e696d9b"),
            new Blueprint("WordOfChaos", "69f2e7aff2d1cd148b8075ee476515b1"),
          }
        },

        {
          typeof(ContextConditionHasBuff),
          new()
          {
            new Blueprint("AngelSwordEffectBuff", "f5f500d6a2a39fc4181af32ad79af488"),
            new Blueprint("JoltingPortentBuff", "27fa15e9738aee1499aed308cdef7084"),
            new Blueprint("ZeorisDaggerRing_BetrayalFeature", "1f6fabee66d54992bc912236d36b50f8"),
          }
        },

        {
          typeof(ContextConditionHasFact),
          new()
          {
            new Blueprint("1_FirstDeathAbility", "4445d9d1c21141c6a0bb24baf373ef78"),
            new Blueprint("GreaterMutagenDexterityStrength", "78d953b296fb2154aa2c85e6e724ce56"),
            new Blueprint("ZeorisDaggerRing_GoverningAllyBuff", "02680be495534b629d543daa89b47079"),
          }
        },

        {
          typeof(ContextConditionSharedValueHigher),
          new()
          {
            new Blueprint("AmiriCampBuff", "f04177fdba7bb324589b7f2b0fd67604"),
            new Blueprint("ShamanBonesSpiritWanderingFeature", "a3862152ae6010445bc25915ac58fc8e"),
            new Blueprint("WitchHexMajorHealingAbility", "3408c351753aa9049af25af31ebef624"),
          }
        },

        {
          typeof(ContextConditionIsEnemy),
          new()
          {
            new Blueprint("AcidBomb", "fd101fbc4aacf5d48b76a65e3aa5db6d"),
            new Blueprint("HexChannelerChannelPositiveHarm", "fb917ad147d846e42ad22c8e14f44b79"),
            new Blueprint("ZippyMagicFeature", "30b4200f897ba25419ba3a292aed4053"),
          }
        },

        {
          typeof(ContextConditionHasBuffFromCaster),
          new()
          {
            new Blueprint("AnomalyDistortionBuff", "599b46d94d454526bf5893a4724d4fbe"),
            new Blueprint("Gibrileth_StenchAreaEffect", "d7a38ef5bd1fffa4aa85a69ff6fe23d4"),
            new Blueprint("WoundWormsLair_BlackDragonFrightfulPresenceArea", "382910feb429e1449b3f8f2a633e3244"),
          }
        },

        {
          typeof(TacticalCombatSquadHitPointsCondition),
          new()
          {
            new Blueprint("ArmyFingerOfDeath", "16da1e53252444cc9f14bcf1c72f58fb"),
            new Blueprint("ArmyMeleeCounterAttackFeature", "9f86b8f30438920458feda7313591ec2"),
            new Blueprint("ArmyRangedCounterAttackFeature", "4d59f676f59579944948f8c461731ab8"),
          }
        },

        {
          typeof(ContextConditionStatValue),
          new()
          {
            new Blueprint("AeonAoOGazeAllyBuff", "a85b9737fba146dcb3468526d67fbc0e"),
            new Blueprint("DevilApostateEvangelizationAbility", "91ba374366c748348a5c1bf85a8685ea"),
            new Blueprint("Valmallos_Buff_AeonGazeEnemy_Core", "217c83b902de44ffa2602d52bafe3d2e"),
          }
        },

        {
          typeof(GreaterThan),
          new()
          {
            new Blueprint("Aeon_CheckCountersAfterCh3", "5cc29b42d3264930b8e56d6005dad1d7"),
            new Blueprint("CommandUnitAttack9", "ed2b90dc0562422dbf5f4db4daec5687"),
            new Blueprint("VaultOfGraves_MythicDemonChapter03", "e3fb405c90492e946a02e176a10268ef"),
          }
        },

        {
          typeof(KingdomRegionIsConquered),
          new()
          {
            new Blueprint("FlagDiplomacy7CrusadeResourcesForRegions", "8663e81969a647fe9d6e8c3afd7d9172"),
            new Blueprint("KingdomMoraleFlagChapter5Regions", "b01624ee06444738964b678259f31a20"),
            new Blueprint("Obj2_1", "31325a3a01ba44a69d3c205784cc1816"),
          }
        },

        {
          typeof(ContextConditionIsMainTarget),
          new()
          {
            new Blueprint("AbandonedKeep_AcidTrap", "e7dadeb8b1d78a341bb4357b502da424"),
            new Blueprint("CurseWeaknessBomb", "197624a197c10cb48bc4dcb229efb91b"),
            new Blueprint("WideSweepAbility", "69811d984ba4ab8419873b09c1641e36"),
          }
        },

        {
          typeof(ContextConditionCasterHasBuffWithDescriptor),
          new()
          {
            new Blueprint("AnimalisticPerseveranceFeature", "1a3d8a5e342c47a7b721ca699a9613ed"),
            new Blueprint("BlindingEnlightenmentFeature", "e343b492d1182404c91048186b7b58fb"),
            new Blueprint("LizardTailFeature", "036d7e6bf5c14defa8fd90fd83a15e15"),
          }
        },

        {
          typeof(ContextConditionDifficultyHigherThan),
          new()
          {
            new Blueprint("AngelRepelTheProfaneBuff", "50a18ee630a4973479e9950011425748"),
            new Blueprint("GiantFly_Feature_Disease", "1fa6430e6064d5f4f8553c67257a1878"),
            new Blueprint("WightEnergyDrainAbility", "35a7f7e6ad5b4374e812fc10ec1c836c"),
          }
        },

        {
          typeof(ContextConditionWeaponAnimationStyle),
          new()
          {
            new Blueprint("GreyGarrison_SuperMythicBuff", "4b11247a4988c254fb9d1cd67f0b1e4a"),
          }
        },

        {
          typeof(ContextConditionIsInCombat),
          new()
          {
            new Blueprint("AngelHaloArea", "7aa654dc15f051b4e865dc82b6765b0c"),
            new Blueprint("DeathAttackAbility", "14f11007d016ec94682af6de83959a83"),
            new Blueprint("WoundingBattleaxeBleedBuff", "b6452a2ac912260409a18aa8e69e60f7"),
          }
        },

        {
          typeof(ContextConditionIsPartyMember),
          new()
          {
            new Blueprint("AngelBringBackTouch", "067035da0186d6e43bb4138f433911ee"),
            new Blueprint("EstrodColumnPoint", "053b1550a2a74d75a6debfcd52e3291e"),
            new Blueprint("WoundingBattleaxeBleedBuff", "b6452a2ac912260409a18aa8e69e60f7"),
          }
        },

        {
          typeof(EtudeStatus),
          new()
          {
            new Blueprint("[DLC1_Taberdine]_BarkConditions", "c1bbb11f93d44e13b5587d4c9701515d"),
            new Blueprint("Cue_0005", "ef16f026e72107d4492aa6861b66739f"),
            new Blueprint("ZombiesOnStreets", "ffcf5bca11694784686d9947ed226a88"),
          }
        },

        {
          typeof(CurrentAreaIs),
          new()
          {
            new Blueprint("AeonEyeEnemyVisualBuff", "9815f77129674e8e886de2d458ecdf49"),
            new Blueprint("Cue_64", "0e8be804be2a4a97b102a3f36d21f240"),
            new Blueprint("WoljifQ", "d79f05dbd35b468fa16312f30d61a5e1"),
          }
        },

        {
          typeof(UnitIsInAreaPart),
          new()
          {
            new Blueprint("AeonEyeEnemyVisualBuff", "9815f77129674e8e886de2d458ecdf49"),
            new Blueprint("CommandMoveUnit3", "dfa1abb2ed114f65bc42a31d2b6a71f5"),
            new Blueprint("Venduag_Q2_interlude_spawnConditions", "7d2e7755a041e0241ad6babe959f8454"),
          }
        },

        {
          typeof(QuestStatus),
          new()
          {
            new Blueprint("30_HeroicVictory", "a43192eddffb455db6004059811ac92d"),
            new Blueprint("Cue_0007", "0479d1ab08a5c2a44837227804085e15"),
            new Blueprint("ZigguratNoMoreLich", "ca82ea555e8408c4e8839cdd5079e099"),
          }
        },

        {
          typeof(HasBuff),
          new()
          {
            new Blueprint("AlushinyrraBeggar_Actions", "a5a61ef3563441544bc2763003c9e653"),
            new Blueprint("CommandAction 9", "a36aa9372df6f9b4b9fc9e02c0feca7c"),
            new Blueprint("WhispersOfMadnessAttach", "72d6ba35e78ff9e4f8e59ef16f192c60"),
          }
        },

        {
          typeof(ContextConditionCompare),
          new()
          {
            new Blueprint("Areelu_UnbreakableDefenseBuff", "57572f514d5b49bf98432026c80382c3"),
            new Blueprint("DragonLevel2MaxAbilityIntelligenceFeature", "21c84e44bf6c4639a0db1a515c0ee3c0"),
            new Blueprint("TransmutationSchoolStrengthAbility", "aadee249a033b2747b63344a758e91be"),
          }
        },

        {
          typeof(ContextConditionBuffRank),
          new()
          {
            new Blueprint("BearerOfSorrowEnchantment", "8a7d0e599fe6b8c4c9ee034eb6af1830"),
            new Blueprint("GowrowAquaticShortspearEnchantment", "c845e1109500f9a4aaabf7a494c4068d"),
            new Blueprint("RangingShots", "2b558167862b05d47b8472d176257f82"),
          }
        },

        {
          typeof(ContextConditionCharacterClass),
          new()
          {
            new Blueprint("AasimarHaloToggleAbility", "248bbb747c273684d9fdf2ed38935def"),
            new Blueprint("HealingJudgmentAbility", "00b6d36e31548dc4ab0ac9d15e64a980"),
            new Blueprint("ViperFamiliarAbility", "52b0d34465ad50545836fddd437cf5c9"),
          }
        },

        {
          typeof(OrAndLogic),
          new()
          {
            new Blueprint("!Octavia_Companion_Warrior_Test", "0f5938a10fd0d3644be33747d6d2b11c"),
            new Blueprint("Cue_0068", "9a7eb4e4d7ff1d345bdb299aa65d46c6"),
            new Blueprint("ZigguratZachariusInZiggurat", "2844d387f27a0bb468f72603dd15eda2"),
          }
        },

        {
          typeof(False),
          new()
          {
            new Blueprint("2ALR_BlueprintAreaTransition", "caa1a113bb2c18e4bb187348664d4c99"),
            new Blueprint("IvorySanctum_SecretEntrance_toSunctum", "d77ef67768ef87e4e98464e2c49cb747"),
            new Blueprint("ZigguratEnter_AreaTransition", "c8a709930aa977d499dc797c22f42bb9"),
          }
        },

        {
          typeof(ContextConditionIsAnimalCompanion),
          new()
          {
            new Blueprint("AnimalInsightArea", "d3c9117d43833df49a253df19377bbfe"),
            new Blueprint("FightDefensivelyToggleAbility", "09d742e8b50b0214fb71acfc99cc00b3"),
            new Blueprint("ScapegoatAbilityAlly", "b9c07dc0df2977c479d19735d956284a"),
          }
        },

        {
          typeof(ContextConditionHasBuffWithDescriptor),
          new()
          {
            new Blueprint("AngelfireApostleVersatileChannelRestorationLesser", "95e3e99ea2f5932408b0310ebc7e9af1"),
            new Blueprint("KineticRestorationAbility", "1dc60bdbf5843f342aaa5e838b66e43a"),
            new Blueprint("WrathOfTheUndeadBuff", "6a30b625459e421d862debf0b3d0214f"),
          }
        },

        {
          typeof(ContextConditionHitDice),
          new()
          {
            new Blueprint("Arbitrament", "0f5bd128c76dd374b8cb9111e3b5186b"),
            new Blueprint("Halaseliax_FrightfulPresenceArea", "b2114357604b47809a3808ea6973ce72"),
            new Blueprint("WoundWormsLair_BlackDragonFrightfulPresenceArea", "382910feb429e1449b3f8f2a633e3244"),
          }
        },

        {
          typeof(ContextConditionIsWeaponEquipped),
          new()
          {
            new Blueprint("AnomalyTemplateDefensiveRandomizerBuff", "1a72d85f20f14f1b84d20b8b6e44734e"),
            new Blueprint("GogglesOfMalocchioFeature", "782027e68010df048af8289ceb6f3c31"),
            new Blueprint("SwordlordSteelNetBuff", "dc9738ee4e71f5c4287e37f3b74c6fe6"),
          }
        },

        {
          typeof(ContextConditionIsPetDead),
          new()
          {
            new Blueprint("AnimalFocusBearBuff", "fa25fec82271c93478194c52a20ce733"),
            new Blueprint("AnimalFocusMouseBuff", "127de9efe375a364d94fc68d94ad231a"),
            new Blueprint("AnimalFocusTigerBuff", "18e0d3842308de14ca3fde356bf92b92"),
          }
        },

        {
          typeof(ContextConditionSharedValueHitDice),
          new()
          {
            new Blueprint("BloodHazeEffectBuff", "06bd4a59646b7fa468166d1c745f31dc"),
            new Blueprint("SecretOfHookingAndSummoning", "72ae181281075c74ea2d1ae74ad95597"),
            new Blueprint("WitchHexLayToRestAbility", "1bb5466b9bfcb5e47b9f667dad5784f9"),
          }
        },

        {
          typeof(ContextConditionAlive),
          new()
          {
            new Blueprint("AngelBringBackTouch", "067035da0186d6e43bb4138f433911ee"),
            new Blueprint("InspiringRecoveryCheckBuff", "dc9a8ddf45adbc74aaff7b309f232072"),
            new Blueprint("SwarmFeastArea", "23d8c63c3af634843aa11f5a169683b5"),
          }
        },

        {
          typeof(ContextConditionMaximumBurn),
          new()
          {
            new Blueprint("ElementalEngineBurnoutTriggerFeature", "090d39a5813d4537ba24b55fff7fe6be"),
          }
        },

        {
          typeof(HasFact),
          new()
          {
            new Blueprint("Answer_0001", "3d7ba59b443f44e1b6a830cd0c3e9550"),
            new Blueprint("Answer_0295", "0de07fdc5f66c104bb4cf6e416d1322f"),
            new Blueprint("ThirdElementWater", "86eff374d040404438ad97fedd7218bc"),
          }
        },

        {
          typeof(ContextConditionCompareTargetHP),
          new()
          {
            new Blueprint("BoneSpearConjure", "ca8bc7d438e6b004a87222f3c32572f2"),
            new Blueprint("ImpalerEnchantment", "a70838190b8751e4c93f5c410d8ca356"),
            new Blueprint("Unused_SZ_1", "204c7132bafa41c993ffdb9ae675d5eb"),
          }
        },

        {
          typeof(ContextConditionFavoredEnemy),
          new()
          {
            new Blueprint("MasterHunterCasterBuff", "90889f69c21b32446a21a1c0770237ee"),
            new Blueprint("MasterSpyCasterBuff", "ff2e84b215b187347a406670ab2f5cf7"),
          }
        },

        {
          typeof(ContextConditionTargetIsBlueprint),
          new()
          {
            new Blueprint("EnhancementBonusWilloWisp", "012f72c2749c2e94eb3c389f3f077aac"),
            new Blueprint("ShamanBattleSpiritAbility", "7eda685d53423de4281d8bc0f1197442"),
            new Blueprint("ThunderingClawPet", "e95c2acd75e1d964eaece4a9958d31d5"),
          }
        },

        {
          typeof(ContextConditionSize),
          new()
          {
            new Blueprint("AeonNormalizeSizeGazeEnemyBuff", "dc42e955adbd444fbb3082687080117b"),
            new Blueprint("MasterSlayerBuff", "d474f18e89348bf4db1ff634040ad283"),
            new Blueprint("WintersMarkEnchantment", "0641db56869d87c4bb387e5ae4a18a0e"),
          }
        },

        {
          typeof(ContextConditionAlignmentDifference),
          new()
          {
            new Blueprint("DeterminedZeal", "a59b08fdf85465a48b036fd9ef4bcc71"),
            new Blueprint("DivineAnathema", "1777a6ff0ae558749b76766a7a575802"),
          }
        },

        {
          typeof(ContextSwarmHasEnemiesInInnerCircle),
          new()
          {
            new Blueprint("BloodlineSerpentineDenOfSpidersSpiderSwarmDamageBuff", "9c414efda39e67344846171c1547edc1"),
            new Blueprint("MandragoraSwarmDamageBuff", "0f4923163104a8748b88e91ec7e14837"),
            new Blueprint("VescavorSwarmDamageBuff", "ddc847a49246ded4f93fe2bf0e2a7dab"),
          }
        },

        {
          typeof(ContextConditionIsShieldEquipped),
          new()
          {
            new Blueprint("AbruptEndEnchantment", "66f1ac1f205e99f4e83c9b3aa8f0b0b1"),
            new Blueprint("MagicalVestmentShieldBuff", "2e8446f820936a44f951b50d70a82b16"),
            new Blueprint("WarpriestShieldbearerChannelPositiveHarm", "894e20539c353c74ab2733a056351947"),
          }
        },

        {
          typeof(AlignmentCheck),
          new()
          {
            new Blueprint("LootCondition", "d1d246fc5c3df5d48aaee5dd199e75ab"),
            new Blueprint("RighteousMight", "90810e5cf53bf854293cbd5ea1066252"),
            new Blueprint("RobeOfVirtueFeature", "f3b1a7b396fc0b048b93967c6738708f"),
          }
        },

        {
          typeof(ContextConditionCasterWeaponInTwoHands),
          new()
          {
            new Blueprint("BracersOfDominanceFeature", "cdc4f29bc423d454e9af87a514a14de7"),
          }
        },

        {
          typeof(ContextConditionCompareCasterHP),
          new()
          {
            new Blueprint("BracersOfOverwhelmingVigorFeature", "b34921b9358e1154783b98fb6aac3cae"),
            new Blueprint("PlagueDeathQuarterstaffFeature", "357d9df84a28fa949a575e8841c4e75e"),
            new Blueprint("ZealousMightItemEnchantment", "819877d9ef15d9d45ac876ca21030279"),
          }
        },

        {
          typeof(ContextConditionPeaceful),
          new()
          {
            new Blueprint("SoulsCloakCurseBuff", "40f948d8e5ee2534eb3d701f256f96b5"),
          }
        },

        {
          typeof(FlagUnlocked),
          new()
          {
            new Blueprint("!Octavia_Companion_Warrior_Test", "0f5938a10fd0d3644be33747d6d2b11c"),
            new Blueprint("Cue_0006", "fddd605a9eac4add97401daf5027f8fa"),
            new Blueprint("ZigguratRiot", "5ecb3695c95e4bd4b836a0deac1ecfd7"),
          }
        },

        {
          typeof(IsUnitLevelLessThan),
          new()
          {
            new Blueprint("SoulsCloakCurseBuff", "40f948d8e5ee2534eb3d701f256f96b5"),
          }
        },

        {
          typeof(ContextConditionDistanceToTarget),
          new()
          {
            new Blueprint("ChameleonStrideGreaterBuff", "6af02d0eed547514792f52bdb741da5d"),
            new Blueprint("DeadeyeEnchantment", "32712327ae4241f47bb7fc96027799dd"),
            new Blueprint("SurefireGlovesFeature", "fe65b4d9191ce494380e3f60f41cec9e"),
          }
        },

        {
          typeof(ContextConditionIsFlanked),
          new()
          {
            new Blueprint("MarksmansSteadyHandFeature", "86baea5d6bde19d4b9845c5c33eeec1b"),
            new Blueprint("TricksterSneakyQuack", "bf41d492ff138ae4e9775e6fd9c8011e"),
          }
        },

        {
          typeof(ContextConditionIsFlatFooted),
          new()
          {
            new Blueprint("MusicOfDeathEnchantment", "183a4d2cc996c6f4db8641bed4b3b0c1"),
            new Blueprint("TeamworkFeature", "bf416f1805710104cad270bd81727274"),
            new Blueprint("VigilantWatchFeature", "d4cf7afc49b81e34989f2dfa76889fed"),
          }
        },

        {
          typeof(ContextConditionUnconsciousAllyFarThan),
          new()
          {
            new Blueprint("ParagonOfDefendersAuraBuff", "b348cf228b07b534cb315e7c54f95379"),
          }
        },

        {
          typeof(ObjectiveStatus),
          new()
          {
            new Blueprint("!Octavia_Companion_Warrior_Test", "0f5938a10fd0d3644be33747d6d2b11c"),
            new Blueprint("Cue_0006", "78f52b70b8e80b94e83b923def53360c"),
            new Blueprint("Ziggurat_ZachariusBeginRitual", "8a020a9f01405ae4fa417500e1efd2e6"),
          }
        },

        {
          typeof(CompanionInParty),
          new()
          {
            new Blueprint("Alushinyrra_HigherCity_VellodusMansion", "d062cf7333b145b8bb85d4400dbea44d"),
            new Blueprint("Cue_0029", "69f07e71ce13da3419f7d7aec40ca9e3"),
            new Blueprint("Yozz_GreyborQ2Bark_Conditions", "e25cbb4124873114ba3b75176e004517"),
          }
        },

        {
          typeof(IsDLCEnabled),
          new()
          {
            new Blueprint("AasimarRace", "b7f02ba92b363064fb873963bec275ee"),
            new Blueprint("Edge_SarkorianWedding_Chapter05_Army21", "f5867b88ae4d4b189c025df9161e75d4"),
            new Blueprint("Location_SarkorianWedding", "da3e19fa23f94fa3a563bd866189e9da"),
          }
        },

        {
          typeof(DialogSeen),
          new()
          {
            new Blueprint("[MainHall] [Tall_DesnaPriest] Final_Bark_Conditions", "7f8be13550ec4db894002cae58c9b811"),
            new Blueprint("Banter_NenioTrever_banter1_pack2", "751e505f4376dd54e9f2eeb1fcf43e41"),
            new Blueprint("ZigguratDeadRomanceTimer", "587df869a564f7046a48bbf27f017619"),
          }
        },

        {
          typeof(CueSeen),
          new()
          {
            new Blueprint("[Kerz]_BarkCondition", "59c232c2fa5e7c54baa235fee0e049d6"),
            new Blueprint("BookPage_0022", "2227fb9fab608364da1b6a2fffdae66f"),
            new Blueprint("ZanedraInTemple", "0d22fd186d557a049b46c0fb3d623f04"),
          }
        },

        {
          typeof(KingdomBuffIsActive),
          new()
          {
            new Blueprint("Aeon2FireElementals", "63364fac363349a99dd7fe96ca86dc7c"),
            new Blueprint("Event71DumpExcavation", "b0ca7e2b70c9447da43f7be86164d43c"),
            new Blueprint("Trickster5ThugPaladin", "e83a6a99081d467fb56d8afe1de6a4d5"),
          }
        },

        {
          typeof(KingdomProjectIsAvailable),
          new()
          {
            new Blueprint("Add4_GotoMoltenScar", "f6694c696284e2046b0f064f83c320c2"),
            new Blueprint("Event61DrakePoison", "23bd72781ce34695bc9af2468456b8af"),
            new Blueprint("Trickster5ThugPaladin", "e83a6a99081d467fb56d8afe1de6a4d5"),
          }
        },

        {
          typeof(ContextConditionHasItem),
          new()
          {
            new Blueprint("123", "535217378b8a4ca3ba5a45f0002de07c"),
            new Blueprint("DirtySquealerEtude", "073253b35c6147e28b603e7e4cfb2ddd"),
            new Blueprint("ZeorisDaggerEtude", "ad64557f3ad74ff0b36fce6364df6ab2"),
          }
        },

        {
          typeof(ContextConditionGarrisonClear),
          new()
          {
            new Blueprint("CreateSettlementFort21", "0b7377f7c46c6aa43bf66af6ec618836"),
            new Blueprint("CreateSettlementFort56", "ece5ff5b715642444b692d9d93b64b9c"),
            new Blueprint("CreateSettlementRiverGarrison", "947bf6259557aeb449557e4bc5228ead"),
          }
        },

        {
          typeof(KingdomProjectIsDone),
          new()
          {
            new Blueprint("CreateSettlementFort21", "0b7377f7c46c6aa43bf66af6ec618836"),
            new Blueprint("CreateSettlementNearRegill", "8b4cd3ebd7b3f3b4ea201bbfed62fa28"),
            new Blueprint("PF-300995", "f25549e2b0654ca6b20335c374e2258d"),
          }
        },

        {
          typeof(KingdomStatCheck),
          new()
          {
            new Blueprint("26!_SadisticGD_Checker_Sum", "561508e5aeba4d37b7418a363411964d"),
            new Blueprint("LogisticsRankUp3Project", "de0bfee4dca3ebc4aae466ca6e799e01"),
            new Blueprint("PF-252649", "403f8687be754fe39430819391be0c73"),
          }
        },

        {
          typeof(KingdomRankUpConditions),
          new()
          {
            new Blueprint("Chapter05", "5b01aa690202e584888dfc600a4aac0a"),
            new Blueprint("LogisticsRankUp2Project", "e2c032467f1cf0b4d9ee4da1da92857a"),
            new Blueprint("MilitaryRankUp8Project", "11904fe03bcc431d8f8fb0a2d4ca3704"),
          }
        },

        {
          typeof(IsEqual),
          new()
          {
            new Blueprint("Arrow_Puzzle_1_complete", "fc34b75fb3f147d398607271584ee70f"),
            new Blueprint("Cue_0059", "b1eb561b4bd711d46bdb85c229519f8d"),
            new Blueprint("XO_Puzzle_2_complete", "8288ad6ec196461f963d6160edbfaca4"),
          }
        },

        {
          typeof(KingdomMoraleFlagCondition),
          new()
          {
            new Blueprint("MoraleFlagSiegeChapter3Controller_buff", "bd5bfbd23acd4098b3a89100b61c3ce0"),
            new Blueprint("MoraleFlagSiegeChapter5Controller_buff", "30d599366a9e46fe992f9ca6fdf9365a"),
          }
        },

        {
          typeof(KingdomSettlementCount),
          new()
          {
            new Blueprint("SettlementsTracker_buff", "71dd611cd70443fcb04f0dce3bda76ef"),
          }
        },

        {
          typeof(ContextConditionIsMainCharacter),
          new()
          {
            new Blueprint("AeonMythicClass", "15a85e67b7d69554cab9ed5830d0268e"),
            new Blueprint("AzataMythicClass", "9a3b2c63afa79744cbca46bea0da9a16"),
          }
        },

        {
          typeof(UnitClass),
          new()
          {
            new Blueprint("AeonMythicClass", "15a85e67b7d69554cab9ed5830d0268e"),
            new Blueprint("Cue_0068", "be4db75c106fb854cbc45323e0754c5b"),
            new Blueprint("Timer_Before_KTC_MythicDemonRankUp2", "5caab08042b37f641ad9ff9ad411c44e"),
          }
        },

        {
          typeof(LessThan),
          new()
          {
            new Blueprint("AddAfterThreeCourts", "4c9fddeb883f3ec459128e484d3d5ff8"),
            new Blueprint("Cue_0003", "f727fbe0e46a02d448e0c1f1fd80c509"),
            new Blueprint("VrockSpawn2", "1afdb2a002bb1f54da2aedb2ec61a963"),
          }
        },

        {
          typeof(IsUnitMythicLevel),
          new()
          {
            new Blueprint("DevilMythicClass", "211f49705f478b3468db6daa802452a2"),
            new Blueprint("GoldenDragonClass", "daf1235b6217787499c14e4e32142523"),
            new Blueprint("SwarmThatWalksClass", "5295b8e13c2303f4c88bdb3d7760a757"),
          }
        },

        {
          typeof(HasTacticalMorale),
          new()
          {
            new Blueprint("Test_Bebilith Blueprint Camping Encounter", "f2f8355d4bc8aa34195eeb2f5cf66645"),
          }
        },

        {
          typeof(InCapital),
          new()
          {
            new Blueprint("Test_Bebilith Blueprint Camping Encounter", "f2f8355d4bc8aa34195eeb2f5cf66645"),
          }
        },

        {
          typeof(PartyUnits),
          new()
          {
            new Blueprint("BossCastSpell_zone", "5efbf1ebdf0387041b437ba46fc2773c"),
            new Blueprint("Puzzle_4", "3c329f0efd784db59f08a70597db8d49"),
            new Blueprint("WatchPoint_SZWall_FoW", "0f1fdc5a42ea41a4b87da4021e89dabd"),
          }
        },

        {
          typeof(UnitInScriptZone),
          new()
          {
            new Blueprint("Answer_0002", "d38052d00f394118945e8861f00574f5"),
            new Blueprint("Graveyard_BossFight_Drop", "73c79925eb004918ba9e09e4146f2c71"),
            new Blueprint("TrueLootHideZone9", "168ca19a2ced8d448a9944c2f0f01d72"),
          }
        },

        {
          typeof(MapObjectRevealed),
          new()
          {
            new Blueprint("chap0", "95c4212a36594186b509e87d00d2d480"),
            new Blueprint("TheiflingRevealDoor3", "9a143d61a83c0fd4ea52262ed924ff72"),
            new Blueprint("Thieflings01_TrapReveal5", "799191689150bff488597bddf7f86c35"),
          }
        },

        {
          typeof(AnswerSelected),
          new()
          {
            new Blueprint("AfterNotDate_dialog", "cbe4991d3d5bad14dac33ca4e67ae2ce"),
            new Blueprint("Answer_0042", "9384003f84564b94c9b01e7e16a1db5d"),
            new Blueprint("YozzTeleportsToShamirasPalase", "03e68d18fd2a47fc95917ba3f45d720d"),
          }
        },

        {
          typeof(CurrentChapter),
          new()
          {
            new Blueprint("Cue_0132", "0267c6f5fd920ac41b57f5dc31a16201"),
            new Blueprint("PF-332075_Restart_SosielRoman", "52c5ed8b094e471fbe4eba0b4397082f"),
            new Blueprint("PF-348009", "f694fa0ccae94d6f8be56f7e0681613b"),
          }
        },

        {
          typeof(KingdomChapterWeek),
          new()
          {
            new Blueprint("PF-218150", "d7696062df7c4b948e1ce3e1b769fc9a"),
          }
        },

        {
          typeof(FlagInRange),
          new()
          {
            new Blueprint("10State_0", "1f815765df0d4d7ba19f731dfa064081"),
            new Blueprint("Cue_0056", "193c2bbab2da4f24bb401c42986aa021"),
            new Blueprint("Zacharius_FinalBetrayal_dialogue", "5ec3e47a05de18c46b36f08c8dfbeafb"),
          }
        },

        {
          typeof(AutoKingdom),
          new()
          {
            new Blueprint("Add3_SearchMoltenScar", "39a11378f06fff740b8211686247d943"),
            new Blueprint("Cue_0252_playerheir", "a8764b751e8fb1240b998546ec6ed292"),
            new Blueprint("PF-232045", "e117b759ee6647e2a156d4c7f0637142"),
          }
        },

        {
          typeof(KingdomEventIsBeingResolved),
          new()
          {
            new Blueprint("CrusadeEvent04", "e55f2d8389a14e6e999e23a7d1a6d736"),
            new Blueprint("CrusadeEvent46", "4f210692d86841d4bcc6cbeb28bbeeca"),
            new Blueprint("PF-378483", "f5dad497239a41fd96a12d4d1b1b38ef"),
          }
        },

        {
          typeof(AnotherEtudeOfGroupIsPlaying),
          new()
          {
            new Blueprint("Aeon_FirstKTC_Ch5", "a165ac24237977340b5bfceac10a67a8"),
            new Blueprint("KTC_Malessa", "ed0ec52c7c9cbcd4c87eaf97195da4a7"),
            new Blueprint("YozzTeleportsToShamirasPalase", "03e68d18fd2a47fc95917ba3f45d720d"),
          }
        },

        {
          typeof(AnySettlementUnderSiege),
          new()
          {
            new Blueprint("PF-236233", "78ddb7dcceaf4dd5b6178807c258909c"),
          }
        },

        {
          typeof(LocationRevealed),
          new()
          {
            new Blueprint("PF-257814", "49a5027d61ec4ab7886acfb6e1daddea"),
            new Blueprint("RegillNotInParty_KickedOut", "2b2cfaa1727070c43b10729920112730"),
          }
        },

        {
          typeof(AnswerListShown),
          new()
          {
            new Blueprint("Answer_0008", "a3a7361d053ff5741a1fa619c6882d87"),
            new Blueprint("Answer_0238", "74e958b78406e494ea5a1f702bdba1e1"),
            new Blueprint("PF-277910", "7792579c4cbc48eb896c9c0d3ef478cc"),
          }
        },

        {
          typeof(AreaVisited),
          new()
          {
            new Blueprint("Answer_0007", "4df71c9b1ab9d174eaf66587e483dc61"),
            new Blueprint("PF-283449", "0711264d1b034070b86b9b524eb93b19"),
            new Blueprint("YellowPuzzleMechanic", "7e0ebe7249b75724a836537405e988bb"),
          }
        },

        {
          typeof(ArmyInLocationDefeated),
          new()
          {
            new Blueprint("PF-296978", "983af9815687400f897ef380ec8e6b09"),
          }
        },

        {
          typeof(IsLootEmpty),
          new()
          {
            new Blueprint("CavesShortcutUnlocked", "d1f433e953409144d914f15597db6e34"),
            new Blueprint("Green_Slot_2_1_IsNotEmpty", "c7fbd363a489d674cb4a29150b2526e2"),
            new Blueprint("Slot_3_3_IsNotEmpty", "85c097fd43ebd3940b6ea98b57e6f35e"),
          }
        },

        {
          typeof(UnitIsNull),
          new()
          {
            new Blueprint("CommandAction", "bc9bee1516bd40d4aa0ca4e70e753cf3"),
            new Blueprint("CommandSetCombatMode", "49386302edee1644197cef3cf6b28f98"),
            new Blueprint("Sitting_Param", "02c9b508081b1954e4329af6db335091"),
          }
        },

        {
          typeof(UnitFromSpawnerIsDead),
          new()
          {
            new Blueprint("52_TrulyImportantDeed_Checker_Tavern", "5470ea99ea3b4bc7a7048d7f12ecb18e"),
            new Blueprint("CommandSetCombatMode 4", "8e6f50dc88e08d141bfdc3d7ad433b6f"),
            new Blueprint("SZ_Inquis2", "11903f7d8ea24f9ea9425468adf277f2"),
          }
        },

        {
          typeof(IsCampaign),
          new()
          {
            new Blueprint("DLC1_Levelup", "dca1299c933b43dd8078cdf078ee6121"),
            new Blueprint("PF-399070", "c41ed688835e4f57a5e76334b68cd729"),
          }
        },

        {
          typeof(UnitBlueprint),
          new()
          {
            new Blueprint("Answer_0023", "7b20b077ed8be9842a561843f40fa0c9"),
            new Blueprint("Cue_0126", "7dcd9dc63ea06594294d9961f13272a9"),
            new Blueprint("Muse_Abad_info_cutscene", "098c81e45ba142f9a761d6c2ff02507e"),
          }
        },

        {
          typeof(IsInTurnBasedCombat),
          new()
          {
            new Blueprint("Tutor_TBM_DH_Buff", "8827906427fe4a5da2c33e8d67d57a23"),
          }
        },

        {
          typeof(IsInCombat),
          new()
          {
            new Blueprint("AneviaDialog", "85d9ab0f99b3f914bb10671c9c63f6a3"),
            new Blueprint("InvisibleHeraldBuff", "a4c2090e76ed6834ab12e1d27c021d93"),
            new Blueprint("WP_1_ScriptZone", "0613d54edb72463e8bcada03f359bf91"),
          }
        },

        {
          typeof(ContextConditionIsUnconscious),
          new()
          {
            new Blueprint("DeepSlumber", "7658b74f626c56a49939d9c20580885e"),
            new Blueprint("RainbowPattern", "4b8265132f9c8174f87ce7fa6d0fe47b"),
            new Blueprint("SleepKitsune", "f8a32c60ae1f878408b525bb967ef48c"),
          }
        },

        {
          typeof(ContextConditionTargetCanSeeInvisible),
          new()
          {
            new Blueprint("BlinkBuff", "c168c6a0e471e924b8c69b31c6352587"),
          }
        },

        {
          typeof(ContextConditionTargetIsArcaneCaster),
          new()
          {
            new Blueprint("Feeblemind", "444eed6e26f773a40ab6e4d160c67faa"),
          }
        },

        {
          typeof(ContextConditionHasBuffFromThisAreaEffect),
          new()
          {
            new Blueprint("PillarOfLifeaArea", "7d0cebd89884679469533be8b680d55c"),
          }
        },

        {
          typeof(BuffConditionCheckRoundNumber),
          new()
          {
            new Blueprint("ResonatingWordBuff", "45dadc2e291367b45b1110d3be039cad"),
          }
        },

        {
          typeof(ContextConditionHasUniqueBuff),
          new()
          {
            new Blueprint("DLC3_RageConfusionIsland", "6401e7d62cf6424a95a858bff65b2000"),
          }
        },

        {
          typeof(PlayerAlignmentIs),
          new()
          {
            new Blueprint("Aeon_Chapter04_Quests", "715233cf827adfe4e8a3e1adf8babad4"),
            new Blueprint("Cue_0074_PleaseFix", "17e298c6166609e438a721a714e7e7af"),
            new Blueprint("TestCrusadeEvent", "c8bcf035a7d947e09386fad55e986753"),
          }
        },

        {
          typeof(GameModeActive),
          new()
          {
            new Blueprint("CrusadeTutorial_01_Chapter2Intro", "20073002e0594c88b5af911060e8dde8"),
            new Blueprint("Tutorials_Chapter03", "1b59d48741cbf9945adde5dc62f968d8"),
            new Blueprint("Tutorials_Chapter04", "6321277cfb08bb5469b148e2a7a7cc12"),
          }
        },

        {
          typeof(KingdomExists),
          new()
          {
            new Blueprint("Chapter03", "15e0048c7daf0ac4999c2313b58df0e3"),
            new Blueprint("CrusadeTutorial_01_Chapter2Intro", "20073002e0594c88b5af911060e8dde8"),
          }
        },

        {
          typeof(ContextConditionGender),
          new()
          {
            new Blueprint("NereidBeguilingAuraAreaEffect", "466ec47d91f209646aa1b66a797b7d8d"),
          }
        },

        {
          typeof(ContextConditionHasBuffImmunityWithDescriptor),
          new()
          {
            new Blueprint("PurpleWormSwallowWholeFeature", "dee864aec4a0d344b913dd27a4b504cb"),
          }
        },

        {
          typeof(ContextConditionTargetIsDivineCaster),
          new()
          {
            new Blueprint("DemodandTarryLairMiniboss_TitansGodslayer", "e990ddcda355abd4396fac5e49895578"),
          }
        },

        {
          typeof(UnitFromSummonPool),
          new()
          {
            new Blueprint("Aranka_Area_InspireCourage", "3c0cbe32b0e1cce48b4407fd637ea203"),
            new Blueprint("CommandAction 1", "84156b459d057844a9a8427faa9562ef"),
            new Blueprint("FulsomeQueen_scene_2_failsafe", "470b6c480eedb4a46be293bca9ee705b"),
          }
        },

        {
          typeof(DifficultyHigherThan),
          new()
          {
            new Blueprint("CommandAction 3", "651c3ea9f9323e943823ed497736ac74"),
            new Blueprint("CommandSetCombatMode4", "c804cbf4f3e9427ca72b9800042cacb3"),
            new Blueprint("Valmallos_Feature_CombatTrigger", "f4621cc70bec4fe7b0373ed152e40570"),
          }
        },

        {
          typeof(ContextConditionHasTouchSpellCharge),
          new()
          {
            new Blueprint("Mageblade", "eb130f652be2dc14b9a5f63608672021"),
          }
        },

        {
          typeof(ContextConditionIsHelpless),
          new()
          {
            new Blueprint("MusicOfDeathEnchantment", "183a4d2cc996c6f4db8641bed4b3b0c1"),
            new Blueprint("SoundOfVoidEnchantment", "69df5e137a08d9b4ead5d87bf4d5d0ac"),
            new Blueprint("TheDissectorEnchantment", "3e90ab8205854cd591538c1aff04b901"),
          }
        },

        {
          typeof(ContextConditionIsTwoHandedEquipped),
          new()
          {
            new Blueprint("AbruptEndEnchantment", "66f1ac1f205e99f4e83c9b3aa8f0b0b1"),
          }
        },

        {
          typeof(ContextConditionIsAmuletEquipped),
          new()
          {
            new Blueprint("HammerOfMasterpieceAbility", "0781ebffe79c5ee4caf127956b9574eb"),
            new Blueprint("HammerOfMasterpieceEnchantment", "f0a7d830ec5bfa44ba77996938db980f"),
          }
        },

        {
          typeof(ContextConditionIsRing2Equipped),
          new()
          {
            new Blueprint("HammerOfMasterpieceAbility", "0781ebffe79c5ee4caf127956b9574eb"),
            new Blueprint("HammerOfMasterpieceEnchantment", "f0a7d830ec5bfa44ba77996938db980f"),
          }
        },

        {
          typeof(ContextConditionIsRing1Equipped),
          new()
          {
            new Blueprint("HammerOfMasterpieceAbility", "0781ebffe79c5ee4caf127956b9574eb"),
            new Blueprint("HammerOfMasterpieceEnchantment", "f0a7d830ec5bfa44ba77996938db980f"),
          }
        },

        {
          typeof(IsPartyInNaturalSetting),
          new()
          {
            new Blueprint("SE_IngerMaggor", "40ad6b04835d4c26b4fe62bb267a6143"),
            new Blueprint("SE_RenownExplorer", "b7204ae38aa346f3a584982fd8486ac2"),
          }
        },

        {
          typeof(PcRace),
          new()
          {
            new Blueprint("Answer_0005", "f2c31b4d7efe2fd49a391e65f44d8b6e"),
            new Blueprint("Cue_0035", "c1a8b930c3827b74b9a2c0f253a08910"),
            new Blueprint("WarCamp_TheatreFirstVisit", "f546a7d95bfda0e4f9cb798f00b69db3"),
          }
        },

        {
          typeof(CheckPassed),
          new()
          {
            new Blueprint("Answer_0001", "d902f8aff72348e882f84fc6aa9c8c2e"),
            new Blueprint("Cue_0034", "cab33f23f9c1f284eab13e33fbdc3df0"),
            new Blueprint("ReiforceTrixterBefore", "8e1bf1034cd7b6c449477b3888d2a659"),
          }
        },

        {
          typeof(UnitIsDead),
          new()
          {
            new Blueprint("AasimarGirlSlave_Actions", "4c1760ddc1a183b4f94ee50cc47f4c37"),
            new Blueprint("CommandUnitCastSpell 1", "135a7dc5d5a058f4891db6fc7e86f143"),
            new Blueprint("WenduTraitor_DrezensStreet", "aaa0452f52514e46bbc9a52fa95f467b"),
          }
        },

        {
          typeof(UnitEqual),
          new()
          {
            new Blueprint("AlarmZone", "a7081ca4e21e8594f93bc84a4eb2a7a8"),
            new Blueprint("GlobalPuzzle_AreshkaArena", "95952942631a4a2d9617c14c1fa989a4"),
            new Blueprint("Ziggurat_ZachariusBeginRitual", "8a020a9f01405ae4fa417500e1efd2e6"),
          }
        },

        {
          typeof(PcMale),
          new()
          {
            new Blueprint("Answer_0029", "c4d69d3fb9060c14497b2123fc408845"),
            new Blueprint("CommandAction", "e13b97f1aad64f599a2d4d3f1b537714"),
            new Blueprint("Cue_0234", "7364becdf5cc4b94dba30a9fe7c3b790"),
          }
        },

        {
          typeof(EnlargedEncountersCapacity),
          new()
          {
            new Blueprint("CommandAction 3", "651c3ea9f9323e943823ed497736ac74"),
          }
        },

        {
          typeof(UnitIsHidden),
          new()
          {
            new Blueprint("Answer_0017", "e5bf1752b172c084f8b70351d9037e1d"),
            new Blueprint("CommandMoveUnit9", "6c3bc83b962c4c3d93bfa51b98ff17d1"),
            new Blueprint("XCOM_StartCutscene", "94342ced3cb04f96bc1f7c2914ee99f4"),
          }
        },

        {
          typeof(IsUnconscious),
          new()
          {
            new Blueprint("CommandUnitLookAt", "0a467c59d8cf78b4c911aeb922b54ef1"),
            new Blueprint("Cue_0002", "7abec2ad3309e6241a77216ee24925b6"),
          }
        },

        {
          typeof(UnitGender),
          new()
          {
            new Blueprint("CommandAction", "4825507512d7234448eaa92ad6384268"),
            new Blueprint("CommandAction", "6406c24f83d2450ba83fd3a5b770ca1d"),
          }
        },

        {
          typeof(IsPartyMember),
          new()
          {
            new Blueprint("AneviaStart", "e537a72ee38591847ad2f231ab1a1f9e"),
            new Blueprint("NecromantInMall", "1b52d48e18fb11848912a24a90694ae9"),
            new Blueprint("YakerDialogue", "c0b7b22035f586d48b0f32bd094473d6"),
          }
        },

        {
          typeof(IsEnemy),
          new()
          {
            new Blueprint("CommandAction", "5d0de4fd6d752294e932745a29b0a4d9"),
            new Blueprint("ShowPartySelection", "cb81a7635afad1e4a9fb3a5dae1b0bb3"),
            new Blueprint("Unused_SZ_1", "204c7132bafa41c993ffdb9ae675d5eb"),
          }
        },

        {
          typeof(IsLegendPathSelected),
          new()
          {
            new Blueprint("CommandAction1", "bb530e9345434933ba412402ca787bf1"),
          }
        },

        {
          typeof(IsUnitCustomCompanion),
          new()
          {
            new Blueprint("CommandAction 3", "37d0bc9b4ebab6f4e9fe53edffaf4cf1"),
          }
        },

        {
          typeof(DayTime),
          new()
          {
            new Blueprint("AeonQ3Scene_DayTime", "ffb3b99adfa368444b4a46ea36e5aec9"),
            new Blueprint("VileniaStaysNearTavern", "1fc25e220db7e0b49a2efbe45c43c0ed"),
            new Blueprint("WenduagQ1Drill", "76c88c9c00369e5419d8b0c70b67eef6"),
          }
        },

        {
          typeof(BarkBanterPlayed),
          new()
          {
            new Blueprint("Banter_CameliaDaeran_banter7_pack2", "9ee702a55f580d0489e3a2529681a691"),
            new Blueprint("Banter_NenioLann_banter2", "c4592758c5cc69548b7a69f8e4775841"),
            new Blueprint("Banter_WoljifEmber_banter6", "5a59dc95c91885a459a834e464c99a1f"),
          }
        },

        {
          typeof(CheckFailed),
          new()
          {
            new Blueprint("Answer_0018", "8d05fd803d64f5c4ab9ffc8bf61d816b"),
            new Blueprint("Cue_0084", "203ef597927aeff45a02f5a766fafb82"),
            new Blueprint("Cue_9", "32716e33b77e4b6983a8dbcd2e128f49"),
          }
        },

        {
          typeof(PlayerSignificantClassIs),
          new()
          {
            new Blueprint("Answer_0001", "2a5615c36b154ef79b0f7bff878081a0"),
            new Blueprint("Cue_0020", "a66a6e34e9aa8d749921acdc7a0ae938"),
            new Blueprint("Gift_From_Stranger_Notification", "e688d0cd0791435eaf84bbe4561624bc"),
          }
        },

        {
          typeof(PlayerTopClassIs),
          new()
          {
            new Blueprint("Cue_0003", "5ab2e262087a41ef9840818c0943ccfe"),
            new Blueprint("Cue_0011", "b52f80037fa9479b8cec3f0eb4f3d053"),
            new Blueprint("Cue_9", "5a3c9ac7639c47ac9489e9b840b6ce19"),
          }
        },

        {
          typeof(IsDlcActive),
          new()
          {
            new Blueprint("Cue_3", "fd59cd739561481bae00977016d85c67"),
            new Blueprint("Cue_4", "d0421fc2ad1646debb25b9de5e452280"),
          }
        },

        {
          typeof(PartyCanUseAbility),
          new()
          {
            new Blueprint("Answer_0003", "5939379b7bd42484da6ba4aeb42e47f4"),
            new Blueprint("Answer_0007", "67824493fd984374d8b283a57a859a55"),
            new Blueprint("Answer_0065", "a4e1af2f7eff831479aeef4799cdbf59"),
          }
        },

        {
          typeof(PcFemale),
          new()
          {
            new Blueprint("Answer_0015", "dd120d8b8a1b2974f97f3d1a866e7ae4"),
            new Blueprint("Cue_0019", "1071445514a15ec42a057a987886a0b5"),
            new Blueprint("WorldwoundEdge_GMBE", "c68fad6a2d296f54f825eb1557153923"),
          }
        },

        {
          typeof(PlayerHasNoCharactersOnRoster),
          new()
          {
            new Blueprint("Cue_0021", "6d1aead07823d1642be37d05b37ee4ce"),
            new Blueprint("Cue_0023", "e44174a44be472249869b451f553bb0c"),
            new Blueprint("Cue_0046", "a60a1d0078dfc364494c50de8661930c"),
          }
        },

        {
          typeof(PlayerHasRecruitsOnRoster),
          new()
          {
            new Blueprint("Cue_0016", "79b2d4385e23cc44bbb31bbe4044cb74"),
          }
        },

        {
          typeof(CheckConditionsHolder),
          new()
          {
            new Blueprint("Answer_0058", "70feca2bda2039f4fa472f0f4d09edde"),
            new Blueprint("Slot_3_3_ItemRestriction", "bdbd56ea4b93f494e81ea3dcf49849a0"),
            new Blueprint("Slot_7_5_ItemRestriction", "b9e743b4c4b467a409a37905af58ce4b"),
          }
        },

        {
          typeof(MonthFromList),
          new()
          {
            new Blueprint("Answer_0023", "bb30ee6ab838dac4cba66ca2da58d394"),
          }
        },

        {
          typeof(DayOfTheMonth),
          new()
          {
            new Blueprint("Answer_0023", "bb30ee6ab838dac4cba66ca2da58d394"),
          }
        },

        {
          typeof(CheckItemCondition),
          new()
          {
            new Blueprint("AreshkagalDungeon_Arena", "67fb6b5c69c149ecb2aed1b38d299fb7"),
            new Blueprint("Cue_0214", "165086c84dfc4c14ca9e9583f7b17adb"),
            new Blueprint("Cue_0221", "36d7a9a7d4e40684ea6ac72668fb8e36"),
          }
        },

        {
          typeof(CompanionIsDead),
          new()
          {
            new Blueprint("Answer_0015", "72050eac97c4b944f9a99ce16a680f16"),
            new Blueprint("DaeranRomance_HolyCarpet", "a47a5d2f17acaf24fae7f86af6ba734d"),
            new Blueprint("Sosiel_Q2_KTC", "4ff659434ee301e4d99cad924df322fe"),
          }
        },

        {
          typeof(HasEnoughMoneyForCustomCompanion),
          new()
          {
            new Blueprint("Answer_0003", "2295c50c6e3d4d93a86a9086aada9833"),
            new Blueprint("Answer_0089", "8639e5fa92c97d24886ae8c90acd38fe"),
            new Blueprint("Answer_3", "40b8e29fb08f4f59bd037e33519002ed"),
          }
        },

        {
          typeof(HasEnoughMoneyForRespec),
          new()
          {
            new Blueprint("Answer_0035", "e04a20e1581a72843a53d18ac4e78408"),
            new Blueprint("Answer_6", "b410fd9e96874a849d94f792fc429d39"),
            new Blueprint("MercenaryTrouble6", "0a8297764e3f9bf4ba5757a0edecd019"),
          }
        },

        {
          typeof(IsRespecAllowed),
          new()
          {
            new Blueprint("Answer_0027", "e75acba3688113a40afa7a46f7fd7bb8"),
            new Blueprint("Answer_0095", "deae4190a11f1ca4c9617d9dc2307ba7"),
          }
        },

        {
          typeof(RespecIsFree),
          new()
          {
            new Blueprint("Cue_2", "48c4790378964832ae733ff5e26c7e20"),
            new Blueprint("Cue_2", "c8a45cb530054b0d896148e4e02263b9"),
          }
        },

        {
          typeof(KingdomLeaderIs),
          new()
          {
            new Blueprint("Answer_0260", "fb07588e668af2f4b93ea5628ab833bc"),
            new Blueprint("Cue_0263", "082fed3c287c9054593eebc2101e79b2"),
            new Blueprint("Cue_0264", "63845fd8cb8868b4f95bdf5cdc3e73b8"),
          }
        },

        {
          typeof(ItemBlueprint),
          new()
          {
            new Blueprint("BridgePuzzle_ItemRestriction", "a56ff402d9024f4b83203bf56593c13e"),
            new Blueprint("Purple_Slot_1_4_Art_2_3f", "6e9dac54bdf8fb84ca46b65ec6459814"),
            new Blueprint("YellowPuzzleSolveChecker", "00016e6128651a548b2c50f23456a3e0"),
          }
        },

        {
          typeof(IsListContainsItem),
          new()
          {
            new Blueprint("areeluPuzzle_ItemRestriction", "abd21b102fd546a0bd53dff0b566076f"),
            new Blueprint("MaskPuzzleLootCont_3_CloseAction", "2573e02967e95014c93266c845bc9f2e"),
            new Blueprint("Slot_2_1_ItemRestriction", "14081f100ba2a284b9f1d99cfd0c1363"),
          }
        },

        {
          typeof(SummonPoolExistsAndEmpty),
          new()
          {
            new Blueprint("Graveyard_AfterStartDialogue", "b179654bab55435c8164bed60aaf150d"),
            new Blueprint("Graveyard_TempleApproach_SZ", "67af5f034d3747eaa85bb6179cdc2562"),
            new Blueprint("XCOM_Triggers", "d10e9d61d16925845be53a113cc7db44"),
          }
        },

        {
          typeof(MapObjectDestroyed),
          new()
          {
            new Blueprint("Graveyard_BushesInCheck", "7d19a4d9deda414194a450b343eac99f"),
            new Blueprint("Graveyard_BushesOutCheck", "2f61e729c22a4a59a810466e9db43a6e"),
          }
        },

        {
          typeof(PartyInScriptZone),
          new()
          {
            new Blueprint("DLC1_AxisDungeon_mechanics", "3507de61854540f9920e6482d7cbb32f"),
            new Blueprint("MediumCity_FlyingIslesControls_Etude", "fa16edfae00b94048a71bab6ef5463d4"),
            new Blueprint("WatchPoint_SZWall_FoW", "0f1fdc5a42ea41a4b87da4021e89dabd"),
          }
        },

        {
          typeof(IsUnitMythicExperience),
          new()
          {
            new Blueprint("DLC1_Levelup", "dca1299c933b43dd8078cdf078ee6121"),
          }
        },

        {
          typeof(IsCampaignImported),
          new()
          {
            new Blueprint("DLC1_Levelup", "dca1299c933b43dd8078cdf078ee6121"),
          }
        },

        {
          typeof(CampaignCompleted),
          new()
          {
            new Blueprint("DLC1_MythicPowersAfterCompletion", "637667bed8e04ffdbf40de38794b6228"),
          }
        },

        {
          typeof(UnitIsInFogOfWar),
          new()
          {
            new Blueprint("PeacefullUnitsInCombatState", "dff0fbdbd83672e429df0dc14b0db79e"),
          }
        },

        {
          typeof(IsleStateCondition),
          new()
          {
            new Blueprint("Alushinyrra_MediumCity_AssasinsGuild", "66fac7083737ab0449932caf327667cd"),
            new Blueprint("AlushinyrraLowerCity_BattleblisAvailble", "fa9c548fa28e4b979db3bf6cefa09c32"),
          }
        },

        {
          typeof(DayOfTheWeek),
          new()
          {
            new Blueprint("EmberQ1_EmberPreachingInPrison", "2d696d7e4ae237947832954d602dbaff"),
          }
        },

        {
          typeof(CompanionIsLost),
          new()
          {
            new Blueprint("Sosiel_Q2_KTC", "4ff659434ee301e4d99cad924df322fe"),
          }
        },
      };
  }
}
